[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਉਦਾਸ ਹ੍ਵੈ ॥੨੧੧॥"
page = 221

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The king again came to his senses from the stupor and grievously heaved a long breath.211."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਦਾਸ ਹੋ ਗਿਆ ॥੨੧੧॥"