[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਲੇਖ ਹੈਂ ॥"
page = 3
line = 3

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Thou art Unaccountable Lord!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਤੂੰ) ਲੇਖ-ਰਹਿਤ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਅਲੇਖ ਹੈਂ ॥"