[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਾ ਕੀ ਸਰਨਿ; ਸਦਾ ਸੁਖੁ ਹੋਇ ॥੧॥"
page = 901
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "In his refuge, ever-lasting peace is obtained."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਦੀ ਸ਼ਰਣਾਗਤ ਅੰਦਰ ਸਦੀਵੀ ਆਰਾਮ ਪ੍ਰਾਪਤ ਹੋ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "In His Sanctuary, eternal peace is obtained. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਕੀ ਸਰਨ ਲੈਨੇ ਸੇ ਅਚੁਤ ਸੁਖੁ ਪ੍ਰਾਪਤਿ ਹੋਵੈ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਦੀ ਸਰਨ ਪਿਆਂ ਸਦਾ ਆਤਮਕ ਆਨੰਦ ਮਿਲਦਾ ਹੈ ॥੧॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜਾ ਕੀ ਸਰਨਿ = ਜਿਸ (ਪ੍ਰਭੂ) ਦਾ ਆਸਰਾ ਲਿਆਂ ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pues en Su Santuario uno está siempre en Éxtasis (1)"