[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਹਰਤਾ ਹਰਿ ਹੈਂ ॥੧੮੩॥"
page = 10
line = 3

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Lord! Thou art the Destroyer of the destroyers! 183"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਮਾਰਨ ਵਾਲਿਆਂ ਦਾ ਵੀ ਮਾਰਨ ਵਾਲਾ ਹੈਂ ॥੧੮੩॥"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਹਰਤਾ, ਹਰਿ ਹੈਂ ॥੧੮੩॥"