[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਸਾ ਮਹਲਾ ੪ ॥"
page = 11
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Asa Measure, Fourth Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਸਾ ਰਾਗ, ਚਊਥੀ ਪਾਤਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Aasaa, Fourth Mehl:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Asa, Mejl Guru Ram Das, Cuarto Canal Divino."