[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਾਚਿ ਲਗੈ; ਤਾ ਹਉਮੈ ਜਾਈਐ ॥੨॥"
page = 736
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "If the mortal is attached to the True Lord, then is his ego eradicated."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੇਕਰ ਪ੍ਰਾਣੀ ਸੱਚੇ ਸੁਆਮੀ ਨਾਲ ਜੁੜ ਜਾਵੇ, ਤਦ ਉਸ ਦੀ ਹੰਗਤਾ ਨਾਸ ਹੋ ਜਾਂਦੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "When someone is attached to the True Lord, his ego is taken away. ||2||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੇ ਮਨ ਹਮਾਰਾ ਤੇਰੇ ਸੱਚੇ ਨਾਮ ਮੇਂ ਲਗੇ ਤਾਂ ਹੰਤਾ ਮਮਤਾ ਜਾਇ॥੨॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਦੋਂ ਮਨੁੱਖ ਉਸ ਸਦਾ-ਥਿਰ ਪ੍ਰਭੂ ਵਿਚ ਲੀਨ ਹੁੰਦਾ ਹੈ, ਤਦੋਂ (ਇਸ ਦੇ ਅੰਦਰੋਂ) ਹਉਮੈ ਦੂਰ ਹੋ ਜਾਂਦੀ ਹੈ ॥੨॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਾਚਿ = ਸਦਾ-ਥਿਰ ਪ੍ਰਭੂ ਵਿਚ ॥੨॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Si uno está entonado en la Verdad de Dios, trasciende su ego limitado. (2)"