[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਾਧ ਕੀ ਸੋਭਾ; ਮੂਚ ਤੇ ਮੂਚੀ ॥"
page = 272
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The honour of saint is the greatness of the great."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੰਤ ਦੀ ਕੀਰਤੀ ਵਡਿਆ ਵਿੱਚੋਂ ਮਹਾਨ ਵੱਡੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The glory of the Holy people is the greatest of the great."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪੁਨਾ ਸਾਧੋਂ ਕੀ ਸੋਭਾ (ਮੂਚ ਤੇ ਮੂਚੀ) ਬਹੁਤ ਸੇ ਬਹੁਤ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤੇ ਬਹੁਤ ਵੱਡੀ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੂਚ = ਵੱਡੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "La Gloria de las personas Santas, es lo más Grande de lo grande."