[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਿਸਨਪਦ ॥ ਸਾਰੰਗ ॥"
page = 682

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "SARANG VISHNUPADA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਬਿਸਨਪਦ: ਸਾਰੰਗ:"