[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਿਨਿ ਗੁਰਿ; ਮੋ ਕਉ ਦੀਨਾ ਜੀਉ ॥"
page = 240
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "That Guru, who gave me life,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਗੁਰੂ ਨੇ ਮੈਨੂੰ ਜਿੰਦ ਜਾਨ ਦਿੱਤੀ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Guru who gave me my soul,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਿਨ ਗੁਰੋਂ ਨੇ ਮੇਰੇ ਕਉ ਜੀ ਦਾਨ ਦੀਆ ਹੈ, ਭਾਵ ਜਨਮ ਮਰਣ ਤੇ ਰਹਤ ਕਰ ਦੀਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ!) ਜਿਸ ਗੁਰੂ ਨੇ ਮੈਨੂੰ ਆਤਮਕ ਜੀਵਨ ਦਿੱਤਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜਿਨਿ ਗੁਰਿ = ਜਿਸ ਗੁਰੂ ਨੇ। ਜੀਉ = ਆਤਮਕ ਜੀਵਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Me postro siempre ante el Guru"