[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਵਾ ਗਉਣੁ ਹੈ ਸੰਸਾਰਾ ॥"
page = 1051
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The world is subject to coming and going."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਗਤ ਆਉਣ ਅਤੇ ਜਾਣ ਦੇ ਅਧੀਨ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The world is coming and going in reincarnation."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਹ ਸੰਸਾਰ ਆਵਣੇ ਜਾਵਣੇ ਵਾਲਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਹ ਜਗਤ ਜਨਮ ਮਰਨ ਦਾ ਚੱਕਰ ਹੀ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਆਵਾਗਉਣੁ = ਆਉਣਾ ਜਾਣਾ, ਜੰਮਣਾ ਮਰਨਾ, ਜਨਮ ਮਰਨ ਦਾ ਚੱਕਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "¿Qué es este mundo? Este mundo es temporal."