[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਗੁ ਆਸਾ ਮਹਲਾ ੧ ਅਸਟਪਦੀਆ ਘਰੁ ੩ ॥"
page = 417
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Asa Measure 1st Guru. Astpadis."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਆਸਾ ਪਹਿਲੀ ਪਾਤਸ਼ਾਹੀ। ਅਸ਼ਟਪਦੀਆਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Raag Aasaa, First Mehl, Ashtpadheeyaa, Third House:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਆਸਾ, ਘਰ ੩ ਵਿੱਚ ਗੁਰੂ ਨਾਨਕਦੇਵ ਜੀ ਦੀ ਅੱਠ-ਬੰਦਾਂ ਵਾਲੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Rag Asa, Mejl Guru Nanak, Primer Canal Divino, Ashtapadis."