[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਸਾਧਸੰਗਤਿ, ਸੋਹਨਿ ਗੁਰ ਭਾਈ ॥੬॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Such fellow-disciples adome the holy congregation."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਐਉਂ (ਇਕ ਲਿਵ ਵਾਲੇ ਹੋਕੇ) ਸਾਧ ਸੰਗਤ ਵਿਚ ਗੁਰਭਾਈ ਸ਼ੋਭਦੇ ਹਨ।"