[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਾਇਆ ਮੰਦਰ; ਮਨਸਾ ਥੰਭ ॥"
page = 344
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "and restrain the desires within the body palace."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਦੇਹਿ ਦੇ ਮਹਿਲ ਅੰਦਰ ਹੀ ਖ਼ਾਹਿਸ਼ਾਂ ਨੂੰ ਰੋਕ ਰੱਖ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "and restrain the desires within the temple of the body."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਔਰ ਕਾਇਆਂ ਰੂਪੀ ਮੰਦਰ ਮੇਂ ਮਨਸਾ ਵਾਸਨਾ ਕਾ ਪਰਵਾਹ ਚਲ ਰਹਾ ਹੈ, ਤਿਸ ਕੋ ਰੋਕੇ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਹ ਭਗਤੀ ਉਸ ਦੇ ਸਰੀਰ-ਘਰ ਨੂੰ ਥੰਮ੍ਹੀ ਦਾ ਕੰਮ ਦੇਂਦੀ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਾਇਆ = ਸਰੀਰ। ਮੰਦਰ = ਘਰ। ਮਨਸਾ = ਫੁਰਨੇ। ਥੰਭ = ਥੰਮ੍ਹੀ, ਸਹਾਰਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y en la mansión de su cuerpo calma sus deseos,"