[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਰਾਮ ਦਾਸ ਪੁਰ ਛਾਡਿ; ਕੀਰਤਿ ਪੁਰ ਆਇ ਕੈ ॥"
page = 825

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Leaving Ramdaspur, she came to Keeratpur and with the beat of the"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਰਾਮ ਦਾਸ ਪੁਰ ਨੂੰ ਛਡ ਕੇ ਕੀਰਤਪੁਰ ਆ ਗਈ"