[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਹਰਿ. ਹਰਿ ਹਰਿ; ਹਰਿ ਹਰਿ ਹਰੇ ॥"
page = 487
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "God, God, God, God, God, God, God."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਮ, ਰਾਮ, ਰਾਮ, ਰਾਮ, ਰਾਮ, ਰਾਮ, ਰਾਮ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Lord, Har, Har, Har, Har, Har, Har, Haray."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮਨ ਬਾਣੀ ਤਨ ਕਰ ਕੇ ਜਿਨੋਂ ਨੇ ਹਰਿ ਹਰਿ ਨਾਮ ਉਚਾਰਨ ਕੀਆ ਹੈ (ਸੋ ਹਰੇ) ਅਨੰਦਵਾਨ ਹੂਏ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮੁੜ ਮੁੜ ਸੁਆਸ ਸੁਆਸ ਹਰਿਨਾਮ ਸਿਮਰਦਿਆਂ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਹਰਿ......ਹਰੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Señor, Jar, Jar, Jar, Jar, Jar, Jar, Jari."