[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਹ ਇੱਜ਼ਤ ਅਤੇ ਸਤਿਕਾਰ ਦੇ ਮੋਤੀਆਂ ਦੀ ਚਮਕ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਜਿਲਾ ਲੂਲੂਇ ਇੱਜ਼ੋ ਤਾਅਜ਼ੀਮ ਰਾ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "He is the brilliance of the stones of respectability and honor,"