[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰੋਗ ਸੋਗ ਦੂਖ; ਤਿਸੁ ਨਾਹੀ ॥"
page = 1085
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "the disease, sorrow and distress cling to him not,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਬੀਮਾਰੀ, ਸ਼ੋਕ ਅਤੇ ਤਕਲਫ਼ਿ ਉਸ ਨੂੰ ਨਹੀਂ ਚਿਮੜਦੀਆਂ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Disease, sorrow and pain do not affect him;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਰੋਗ ਔ ਸੋਗ ਪੁਨਃ ਦੁਖ ਭੀ ਤਿਸ ਕੋ ਨਹੀਂ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਉਸ ਮਨੁੱਖ ਨੂੰ ਕੋਈ ਰੋਗ ਸੋਗ ਦੁੱਖ ਪੋਹ ਨਹੀਂ ਸਕਦੇ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤਿਸੁ = ਉਸ (ਉਸ) ਮਨੁੱਖ ਨੂੰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sí, él no es afligido por penas ni sufrimientos,"