[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਭਾਤਿ ਭਾਤਿ ਸੌ ਆਦਰੁ ਕੀਨੋ ॥੧੪॥"
page = 1001

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Be put up his camp at a nice place and was endowed honour.(14)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਭਾਂਤ ਭਾਂਤ ਨਾਲ ਆਦਰ ਕੀਤਾ ਗਿਆ ॥੧੪॥"