[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਪੁ ਤਪੁ ਸੰਜਮੁ ਕਮਾਵੈ ਕਰਮੁ ॥"
page = 1411
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Who performs the deeds of devotion, austerity and self-restrain."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਅਨੁਰਾਗ, ਤਪੱਸਿਆ ਅਤੇ ਸਵੈ-ਜਬਤ ਦੇ ਅਮਲ ਕਮਾਉਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He chants and meditates, and practices austerity and good deeds."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਪ, ਤਪ, ਸੰਜਮ ਆਦੀ ਕਰਮੋਂ ਕਾ ਕਮਾਵਣਾ ਕਰੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੋ ਇਹੀ ਜਪ-ਕਰਮ ਕਰਦਾ ਹੈ, ਇਹੀ ਤਪ-ਕਰਮ ਕਰਦਾ ਹੈ, ਇਹੀ ਸੰਜਮ-ਕਰਮ ਕਰਦਾ ਹੈ (ਜੋ ਪਰਮਾਤਮਾ ਦੀ ਭਗਤੀ ਨੂੰ ਹੀ ਜਪ ਤਪ ਸੰਜਮ ਸਮਝਦਾ ਹੈ)"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੰਜਮੁ = ਇੰਦ੍ਰਿਆਂ ਨੂੰ ਵੱਸ ਵਿਚ ਰੱਖਣ ਦਾ ਜਤਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "él canta y medita, practica austeridades y buenas acciones,"