[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਇ ਪਇਆ ਤੇਰੀ ਸਰਣਾਈ ॥"
page = 104
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "I have come and entered Thine sanctuary."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਆ ਕੇ ਤੇਰੀ ਸਰਣਾਗਤ ਸੰਭਾਲੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I have come to Your Sanctuary;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਮਹਾਰਾਜ! ਮੈਂ ਤੇਰੀ ਸਰਣ ਮੇਂ ਆਨ ਪੜਾ ਹੂੰ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਪ੍ਰਭੂ!) ਮੈਂ ਆ ਕੇ ਤੇਰੀ ਸਰਨ ਪਿਆ ਹਾਂ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਆਇ = ਆ ਕੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Yo busco Tu Santuario;"