[[content]]
assets = ["DGDG", "DDTK"]
type = "primary"
data = "ਬਾਲਾਨ ਬਾਲ ॥"
page = 5
line = 19

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Smallest of the Small."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਬਾਲਾਂ ਦਾ ਬਾਲ (ਸਰਲ ਸੁਭਾ ਵਾਲਾ) ਹੈਂ,"

