[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਮ ਕੇ ਧਾਰੇ; ਸਗਲੇ ਜੰਤ ॥"
page = 284
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By the Name are sustained all the creatures."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਨਾਮ ਨੇ ਹੀ ਸਾਰਿਆਂ ਜੀਵਾਂ ਨੂੰ ਸਹਾਰਾ ਦਿਤਾ ਹੋਇਆ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Naam is the Support of all creatures."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸ ਕੇ ਨਾਮ ਕੇ ਧਾਰੇ ਹੂਏ ਸੰਪੂਰਨ ਜੀਵ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸਾਰੇ ਜੀਆ ਜੰਤ ਅਕਾਲ ਪੁਰਖ ਦੇ ਆਸਰੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨਾਮ = ਅਕਾਲ ਪੁਰਖ। ਧਾਰੇ = ਟਿਕਾਏ ਹੋਏ, ਆਸਰੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Naam es el Soporte de todas las criaturas."