[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਲਿਵ ਲਾਵਹੁ; ਤਿਸੁ ਰਾਮ ਸਨੇਹੀ ॥"
page = 270
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "fix thy attention on that loving Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੀ ਬ੍ਰਿਤੀ ਉਸ ਪਿਆਰੇ ਪ੍ਰਭੂ ਨਾਲ ਜੋੜ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "attune yourself to that Loving Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸ ਰਾਮ (ਸਨੇਹੀ) ਪ੍ਰੀਤਮ ਮੇਂ ਬ੍ਰਿਤੀ ਲਗਾਵੋ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਪਿਆਰੇ ਰਾਮ ਨਾਲ ਲਿਵ ਜੋੜ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਨੇਹੀ = ਪਿਆਰ ਕਰਨ ਵਾਲਾ, ਸਨੇਹ ਕਰਨ ਵਾਲਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "permanece entonado a tu Señor."