[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰਮਤੀ; ਘਟਿ ਪਰਗਟੁ ਹੋਇ ॥"
page = 663
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By Guru's instruction, He becomes manifest into the mind."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੁਰਾਂ ਦੇ ਉਪਦੇਸ਼ ਦੁਆਰਾ, ਉਹ ਹਿਰਦੇ ਅੰਦਰ ਪ੍ਰਤੱਖ ਹੋ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Through the Guru's Teachings, He is revealed in the heart."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੋ ਗੁਰੋਂ ਕੀ ਸਿਖ੍ਯਾ ਦ੍ਵਾਰੇ ਹ੍ਰਿਦੇ ਅੰਤਰ ਹੀ ਪ੍ਰਗਟ ਹੋਇ ਜਾਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਪਰ) ਗੁਰੂ ਦੀ ਮਤਿ ਉਤੇ ਤੁਰਿਆਂ ਹੀ (ਮਨੁੱਖ ਦੇ) ਹਿਰਦੇ ਵਿਚ ਪਰਗਟ ਹੁੰਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਰਮਤਿ = ਗੁਰੂ ਦੀ ਮਤਿ ਉਤੇ ਤੁਰਿਆਂ। ਘਟਿ = ਹਿਰਦੇ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "uno puede ver al Señor en su corazón."