[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਦੁਹਿਤ ਰਾਇ ਰੌਸਨਾ ਤਾ ਕੇ ॥"
page = 1213

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਦੀ ਪੁੱਤਰੀ ਦਾ ਨਾਂ ਰੌਸ਼ਨਾ ਰਾਇ ਸੀ।"