[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਗੋਯਾ, ਤੂੰ ਰੱਬ ਦੇ ਨਾਮ ਤੋਣ ਬਿਨਾਣ ਹੋਰ ਕੁਝ ਨ ਕਹੁ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਗ਼ੈਰ ਹਰਫ਼ਿ ਖ਼ੁਦਾ ਮਗੋ ਗੋਯਾ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "A disrespectful (apostate/atheist) person is always chagrined and ashamed before Him. (215)"