[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਿਸ ਕੇ ਕਰਤਬ; ਬਿਰਥੇ ਜਾਤਿ ॥"
page = 286
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "but his doings go in vain."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪਰ ਉਸ ਦੇ ਕੰਮ ਨਿਸਫਲ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "but these attempts are in vain."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪਰੰਤੂ ਇਸਕੇ ਕਰਤਵ ਸੰਪੂਰਨ ਵਿਅਰਥ ਹੀ ਜਾਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਪਰ ਜੇ ਪ੍ਰਭੂ ਸਹਾਇਤਾ ਨਾਹ ਕਰੇ ਤਾਂ) ਉਸ ਦੇ ਕੰਮ ਵਿਅਰਥ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਰਤਬ = ਕੰਮ। ਬਿਰਥੇ = ਵਿਅਰਥ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pero será en vano."