[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਘਨੰ ਪੁਹਪ ਬਰਖੇ ॥"
page = 211

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "All the gods were pleased and a loot of flowers were showered."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਆਕਾਸ਼ ਤੋਂ ਫੁੱਲ ਵਰਸਾਉਣ ਲੱਗੇ।"