[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਰਬ ਨਾਸਿਯ ਹੈਂ ॥੧੭੪॥"
page = 9
line = 15

[[content]]
assets = ["JSTS"]
type = "note"
language = "pa"
data = "ਨਾਸਿਯ = ਨਾਸ਼ ਕਰਨਵਾਲਾ।"

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Lord! Thou destroyest all! 174"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਸਭ ਦਾ ਸੰਘਾਰਕ ਵੀ ਹੈਂ ॥੧੭੪॥"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਸਰਬ, ਨਾਸਿਯ ਹੈਂ ॥੧੭੪॥"