[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਭ ਕੀ ਰੇਨੁ; ਹੋਇ ਹਾਂ ॥"
page = 410
line = 4

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He, who become the dust of all men's feet,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਸਾਰਿਆਂ ਦੇ ਪੈਰਾ ਦੀ ਧੂੜ ਹੋ ਜਾਂਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "One who becomes the dust of all"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਸਭ ਕੀ ਰੇਣ ਭਏ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇ ਉਹ ਮਨੁੱਖ ਸਭਨਾਂ ਦੇ ਚਰਨਾਂ ਦੀ ਧੂੜ ਹੋਇਆ ਰਹਿੰਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਰੇਨੁ = ਚਰਨ-ਧੂੜ। ਹੋਇ = ਹੋ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Él se vuelve entonces como el polvo"