[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਵਡਭਾਗੀ ਮਿਲੁ ਰਾਮਾ ॥੧॥"
page = 173
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O man of good fortune, unite with the Pervading Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਓ ਭਾਰੇ ਨਸੀਬਾਂ ਵਾਲਿਆਂ, ਵਿਆਪਕ ਸਾਈਂ ਨਾਲ ਜੁੜ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "By great good fortune, you shall meet with the Lord. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਵਡੇ ਭਾਗੋਂ ਸੇ ਰਾਮ ਕੇ ਸੰਗ ਮਿਲਿ ਜਾਹੁ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਜਿੰਦੇ! ਮਿਲ ਰਾਮ ਨੂੰ, ਤੇਰੇ ਭਾਗ ਚੰਗੇ ਹੋ ਗਏ ਹਨ ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Y así encuentra al Señor por una buena fortuna.(1)"