[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤੈ ਸਾਹਿਬ ਕੀ; ਕਰਹਿ ਸੇਵ ॥"
page = 1172
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "They who perform Thy service O Lord!"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਤੇਰੀ ਘਾਲ ਕਮਾਉਂਦੇ ਹਨ, ਹੇ ਸੁਆਮੀ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Those who serve You, Lord,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ (ਸਾਹਿਬ) ਸ੍ਵਾਮੀ! ਜੋ ਤੇਰੀ ਸੇਵਾ ਕਰਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਮਾਲਕ! ਜਿਹੜੇ ਮਨੁੱਖ ਤੇਰੀ ਸੇਵਾ-ਭਗਤੀ ਕਰਦੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤੈ ਕੀ = ਤੇਰੀ। ਸਾਹਿਬ ਕੀ = ਮਾਲਕ ਦੀ। ਕਰਹਿ = ਕਰਦੇ ਹਨ {ਬਹੁ-ਵਚਨ}।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Dios, Maestro mío, quien sea que realice Tu Servicio, logrará el Éxtasis Supremo,"