[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਆਭਾ ਅਭੰਗ ॥"
page = 6
line = 1

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Thy glow is Eternal."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਤੇਰੀ) ਚਮਕ ਸਥਾਈ (ਅਭੰਗ) ਹੈ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਆਭਾ ਅਭੰਗ ॥"