[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਮਹਾ ਬੀਰ ਗਜੇ ॥"
page = 175

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The drums resounded violently and the mighty warriors began to roar."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਸੂਰਵੀਰ ਗਜਦੇ ਸਨ।"