[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਤਿਗੁਰ; ਹਮਰਾ ਭਰਮੁ ਗਵਾਇਆ ॥"
page = 423
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The True Guru has dispelled my doubt."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੱਚੇ ਗੁਰਾਂ ਨੇ ਮੇਰਾ ਸੰਦੇਹ ਨਵਿਰਤ ਕਰ ਦਿੱਤਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The True Guru has dispelled my doubts."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸਤਗੁਰੋਂ ਨੇ ਮੇਰਾ ਭ੍ਰਮ ਦੂਰ ਕਰ ਦੀਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਨੇ ਮੇਰੀ ਭਟਕਣਾ ਮੁਕਾ ਦਿੱਤੀ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਭਰਮੁ = ਭਟਕਣਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Verdadero Guru me quitó de dudas, y ahora enaltezco en mi mente"