[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਸ਼ਾਹਾਨ ਸ਼ਾਹ ਹੈਂ ॥"
page = 6
line = 15

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Thou art the Emperor of Emperors!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਸ਼ਾਹਾਂ ਦਾ ਸ਼ਾਹ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਕਿ, ਸਾਹਾਨ ਸਾਹ ਹੈਂ ॥"