[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਗੁਰਮੁਖਿ ਸੇਵਾ ਘਾਲਿ; ਵਿਰਲੇ ਘਾਲੀਐ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Rare are those who attain the sense of discipline and service."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਗੁਰਮੁਖਾਂ ਦੀ ਸੇਵਾ ਦੀ ਘਾਲ ਕਮਾਈ (ਕਿਸੇ) ਵਿਰਲੇ ਨੇ ਹੀ ਕੀਤੀ ਹੈ।"