[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਬਿਤੁ ॥"
page = 898

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Kabit"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕਬਿੱਤ:"