[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਨਕੁ; ਸਾਚੁ ਕਹੈ ਵੀਚਾਰੁ ॥"
page = 423
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Nanak gives vent to the true thought."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਨਾਨਕ ਸੱਚੇ ਖ਼ਿਆਲ ਦਾ ਉਚਾਰਨ ਕਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Nanak chants the true thought."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹਮ ਸੱਚ ਬੀਚਾਰ ਵਾ ਵੀਚਾਰੁ ਕਰ ਸਚੁ ਕਹਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਨਾਨਕ (ਤੈਨੂੰ) ਅਟੱਲ (ਨਿਯਮ ਦੀ) ਵਿਚਾਰ ਦੱਸਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨਾਨਕੁ ਕਹੈ = ਨਾਨਕ ਆਖਦਾ ਹੈ। ਸਾਚੁ = ਅਟੱਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Nanak canta en meditación que uno debe guardar el Naam,"