[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਬਸੰਤੁ ਮਹਲਾ ੫ ਘਰੁ ੨ ਹਿੰਡੋਲ ॥"
page = 1185
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Basant 5th Guru Hindol."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਬਸੰਤ ਪੰਜਵੀਂ ਪਾਤਿਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Basant, Fifth Mehl, Second House, Hindol:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਬਸੰਤੁ/ਹਿੰਡੋਲ, ਘਰ ੨ ਵਿੱਚ ਗੁਰੂ ਅਰਜਨਦੇਵ ਜੀ ਦੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Basant Mejl Guru Aryan Dev, Quinto Canal Divino, Hindol."