[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਜਦ ਉਸ ਦੀ ਉਮੀਦ ਫਲ ਆਈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਚੂੰ ਉਮੀਦਸ਼ ਸੂਰਤਿ ਹਾਸਲ ਗ੍ਰਿਫ਼ਤ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "And, he raises the banner of veneration and maturity high in the sky.(105)        "