[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਮਿਤ ਦਰਬੁ ਦੇ ਤਹਾ ਪਠਾਯੋ ॥"
page = 106

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Then the king called Rakat Beej and sent him after giving him enormous wealth."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਬਹੁਤ ਧਨ ਦੇ ਕੇ ਉਸ ਨੂੰ ਭੇਜ ਦਿੱਤਾ।"