[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਹਠੇ ਖਗ ਧੀਰੰ ॥੪੪੫॥"
page = 246

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The persistent warriors like Mahodar held their swords and stood firmly with forbearance.445."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤਲਵਾਰਾਂ ਫੜ ਲਈਆਂ ॥੪੪੫॥"