[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕੋਟਿ ਕਮੇਰ; ਭਰਹਿ ਭੰਡਾਰ ॥"
page = 1163
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Millions of treasures fill his treasures."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕ੍ਰੋੜਾਂ ਹੀ ਖਜਾਨਚੀ ਉਸ ਦੇ ਖਜਾਨੇ ਪਰੀਪੂਰਨ ਕਰ ਰਹੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Millions of treasurers fill His Treasury."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕ੍ਰੋੜੋਂ ਹੀ ਕੁਬੇਰ ਜਿਸ ਕੇ ਭੰਡਾਰ ਕੋ ਭਰਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਮੈਂ ਉਸ ਪ੍ਰਭੂ ਤੋਂ ਹੀ ਮੰਗਦਾ ਹਾਂ) ਜਿਸ ਦੇ ਖ਼ਜ਼ਾਨੇ ਕ੍ਰੋੜਾਂ ਹੀ ਕੁਬੇਰ ਦੇਵਤੇ ਭਰਦੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਮੇਰ = ਧਨ ਦਾ ਦੇਵਤਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Millones de Kuberas son los guardianes de Tus Tesoros"