[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਾਜੰਤ ਤੂਰ ਝਨਕੰਤ ਤਾਰ ॥"
page = 628

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The small and big drums were resounding"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੁਰੀਆਂ (ਬੀਨਾਂ) ਵਜਦੀਆਂ ਸਨ ਅਤੇ ਤਾਰਾਂ ਝਣਕਾਰ ਕਰਦੀਆਂ ਸਨ।"