[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਜੋਬਨ ਜੇਬ ਅਧਿਕ ਤਿਹ ਬਾਢੀ ॥"
page = 1326

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਦਾ ਜੋਬਨ ਅਤੇ ਸੁੰਦਰਤਾ ਇਤਨੀ ਨਿਖਰੀ,"