[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਭ ਜੁਗ ਮਹਿ; ਸਾਚਾ ਏਕੋ ਸੋਈ ॥"
page = 880
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "In all the ages, there is only the on True Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਾਰਿਆਂ ਯੁਗਾਂ ਅੰਦਰ ਕੇਵਲ ਉਹ ਇਕ ਸੱਚਾ ਸੁਆਮੀ ਹੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Throughout the ages, there is only the One True Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸਭ ਜੁਗੋਂ ਮੇਂ ਏਕ ਸੋਈ ਸਚਾ ਪੂਰਨ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਸਾਰੇ ਜੁਗਾਂ ਵਿਚ ਉਹ ਪਰਮਾਤਮਾ ਹੀ ਸਦਾ ਕਾਇਮ ਰਹਿਣ ਵਾਲਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਾਚਾ = ਸਦਾ ਕਾਇਮ ਰਹਿਣ ਵਾਲਾ। ਏਕੋ = ਇੱਕ ਹੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "A través de todas las épocas, el Uno Verdadero ha permanecido siempre Él Mismo."