[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਆਪਿ ਅਭੇਵ ਹੈਂ ॥"
page = 6
line = 13

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Thou art self-illumined!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਆਪ ਭੇਦ-ਰਹਿਤ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਕਿ, ਆਪਿ ਅਭੇਵ ਹੈਂ ॥"