[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੈਲਾ ਮਲਤਾ; ਇਹੁ ਸੰਸਾਰੁ ॥"
page = 1158
line = 4

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "This world is defiled with impurity."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਇਹ ਦੁਨੀਆਂ ਮਲੀਣਤਾ ਨਾਲ ਪਲੀਤ ਹੋਈ ਹੋਈ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "This world is polluted with pollution."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਅਗ੍ਯਾਤ ਮੈਲਤਾ ਕਰ ਏਹ ਸੰਸਾਰ ਮਲੀਨ ਹੋ ਰਹਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਹ (ਸਾਰਾ) ਸੰਸਾਰ ਮੈਲਾ ਹੈ, ਮਲੀਨ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਲਤਾ = ਮਲੀਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sí, manchado e impuro esta el mundo entero,"