[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਪਾਧੜੀ ਛੰਦ ॥"
page = 640

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "PAADHARI STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਪਾਧੜੀ ਛੰਦ:"