[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਸਮਝੋ ਉਸ ਨੇ ਬੰਦਗੀ ਦਾ ਮਾਰਗ ਫੜ ਲਿਆ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਦਰ ਤਰੀਕਿ ਬੰਦਗੀ ਪਰਦਾਖ਼ਤਾ ॥੨੩੯॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Thousands of Ishars and Inders contained in the lotus feet of Guru Nanak."