[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਹੰਸਾ ਛੰਦ ॥"
page = 563

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "HANSA STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੰਸਾ ਛੰਦ:"