[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਮੰਤ੍ਰ ਹਰੀ ॥"
page = 13

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The Lord is not in incantations!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹਰੀ ਮੰਤ੍ਰਾਂ ਤੋਂ ਰਹਿਤ ਹੈ,"