[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਮਾ ਕਹੈ; ਸੁਨਹੁ ਬਾਦਿਸਾਹ ॥"
page = 1166
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Said Nama: \"Hear thou, O king,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਨਾਮੇ ਨੇ ਆਖਿਆ: \"ਤੂੰ ਸੁਣ, ਹੇ ਪਾਤਿਸ਼ਾਹ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Naam Dayv said, \"Listen, O king:"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਨਾਮਦੇਵ ਜੀ ਕਹਤੇ ਹੈਂ: ਸੁਨੋਂ ਹੇ ਬਾਦਸ਼ਾਹ! ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਨਾਮਾ ਆਖਦਾ ਹੈ ਕਿ ਹੇ ਬਾਦਸ਼ਾਹ! ਸੁਣ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dice Namdev, escucha oh Rey,"