[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਧਨੁਰ ਬਾਨ ਧਾਰੇ ॥"
page = 42

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He seems bedecked beautifully"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਸ ਨੇ) ਤੀਰ ਕਮਾਨ ਧਾਰਨ ਕੀਤੀ ਹੋਈ ਹੈ"