[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਛਿਦੇ ਚਰਮੰ ॥"
page = 253

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The weapons, coming into contact with armours, are piercing the bodies"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਢਾਲਾਂ ਛਿਜ ਗਈਆਂ ਹਨ।"