[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੰਤ ਜਨਾ ਕੀ ਧੂਰਿ; ਮਨ ਮੰਗ ॥"
page = 295
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "and heartily pray for the dust of saints feet."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਸਾਧੂਆਂ ਦੇ ਪੈਰਾਂ ਦੀ ਧੂੜ ਦੀ ਦਿਲੋ ਯਾਚਨਾ ਕਰ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "and pray for the dust of the feet of the Saints."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੰਤ ਜਨੋਂ ਕੀ ਚਰਨ ਧੂੜੀ ਕੌ ਮਨ ਮੇਂ ਮਾਂਗ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਹੇ ਮਨ! ਸੰਤ ਜਨਾਂ ਦੇ ਪੈਰਾਂ ਦੀ ਖ਼ਾਕ ਮੰਗ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਨ = ਹੇ ਮਨ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Renuncia a tu orgullo, a la contienda,"