[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗਉੜੀ ਮਹਲਾ ੧ ॥"
page = 154
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Gauri 1st Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗਊੜੀ ਪਹਿਲੀ ਪਾਤਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Gauree, First Mehl:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Gauri, Mejl Guru Nanak, Primer Canal Divino."