[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਬ ਆਪਸ ਊਪਰਿ. ਰਖੈ ਗੁਮਾਨੁ ॥"
page = 892
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "then takes she pride on herself"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਉਹ ਆਪਣੇ ਆਪ ਉਤੇ ਹੰਕਾਰ ਕਰਦੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "then she takes pride in herself."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਬ ਵਹੁ ਮਾਇਆ ਅਪਨੇ ਉਪਰ ਗੁਮਾਨੁ ਰਖਤੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤਦੋਂ ਉਹ ਆਪਣੇ ਉਤੇ ਬੜਾ ਮਾਣ ਕਰਦੀ ਹੈ (ਰੁੱਸ ਰੁੱਸ ਕੇ ਨੱਸ ਜਾਣ ਦਾ ਜਤਨ ਕਰਦੀ ਹੈ)।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਆਪਸ ਊਪਰਿ = ਆਪਣੇ ਆਪ ਉੱਤੇ। ਗੁਮਾਨੁ = ਮਾਣ, ਅਹੰਕਾਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "ella se vuelve vana y pretenciosa,"