[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਰਿ ਕਿਰਪਾ; ਮੇਰਾ ਚਿਤੁ ਲਾਇਆ ॥"
page = 223
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Showing his benediction, the Guru attuned my mind to the Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੀ ਰਹਿਮਤ ਧਾਰ ਕੇ ਗੁਰਾਂ ਨੇ ਮੇਰਾ ਮਨ ਸੁਆਮੀ ਨਾਲ ਸੁਰਤਾਲ ਵਿੱਚ ਕਰ ਦਿਤਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "In His Mercy, He attuned my consciousness to the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਅਪਨੀ ਕਿਰਪਾ ਕਰ ਕੇ ਤਿਸ ਵਾਹਿਗੁਰੂ ਨੇ ਮੇਰਾ ਚਿਤ ਸਤਿਗੁਰੋਂ ਮੇਂ ਲਗਾਇਆ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸਤਿਗੁਰੂ ਨੇ ਮਿਹਰ ਕਰ ਕੇ ਮੇਰਾ ਚਿੱਤ ਪ੍ਰਭੂ-ਚਰਨਾਂ ਵਿਚ ਜੋੜ ਦਿੱਤਾ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਰਿ = ਕਰ ਕੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y en mi mente concibo que todo es sólo Uno."