[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਹ ਕਿਛੁ ਜਨਮੈ; ਨਹ ਕਿਛੁ ਮਰੈ ॥"
page = 281
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Nothing is born and nothing dies."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਨਾਂ ਕੁਝ ਜੰਮਦਾ ਹੈ ਅਤੇ ਨਾਂ ਹੀ ਕੁਝ ਮਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Nothing is born, and nothing dies."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਤੇ ਨਾ ਕੁਛ ਜਨਮਤਾ ਹੈ ਔਰ ਨਾ ਕੁਛ ਮਰਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਨਾਹ ਕੁਝ ਜੰਮਦਾ ਹੈ ਨਾਹ ਕੁਝ ਮਰਦਾ ਹੈ;"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Nada nace y nada muere;"