[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਜੇ ਸੋ ਸਰਬ ਸਾਜਯੰ ॥"
page = 102

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Then the demon-king gathered all the war-paraphernalis."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸਾਰਾ ਸਾਜ ਸਜਾਇਆ"