[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੈ ਅਨਾਥੁ; ਪ੍ਰਭ. ਕਹਉ ਕਾਹਿ ॥"
page = 1194
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "I am an orphan, O Lord. To whom should I make my complaint?"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਇਕ ਯਤੀਮ ਹਾਂ, ਹੇ ਪ੍ਰਭੂ! ਮੈਂ ਕੀਹਦੇ ਕੋਲ ਆਪਣੀ ਸ਼ਿਕਾਇਤ ਕਰਾਂ?"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I am a poor orphan, O God; unto whom should I complain?"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਰਭੂ! ਮੈਂ ਅਨਾਥੁ ਕਿਸ ਕੋ ਕਹੂੰ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਰਭੂ! ਮੈਂ (ਬੜਾ) ਆਜਜ਼ ਹੋ ਗਿਆ ਹਾਂ, (ਆਪਣਾ ਦੁੱਖ ਤੈਥੋਂ ਬਿਨਾ ਹੋਰ) ਕਿਸ ਨੂੰ ਦੱਸਾਂ?"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਅਨਾਥੁ = ਆਜਜ਼। ਕਹਉ ਕਾਹਿ = ਮੈਂ ਕਿਸ ਨੂੰ ਆਖਾਂ?"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Estoy indefenso, oh Dios, ¿a quien le podría pedir ayuda?"