[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਥ ਭ੍ਰਿਤ ਤ੍ਰੋਦਸਮੋ ਗੁਰੂ ਕਥਨੰ ॥"
page = 657

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Now begins the description of an Orderly as the Thirteenth Guru"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੁਣ ਦਾਸ ਰੂਪ ਤੇਰ੍ਹਵੇਂ ਗੁਰੂ ਦਾ ਕਥਨ"