[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਫਿਰਤਉ ਗਰਬ ਗੁਬਾਰਿ; ਮਰਣੁ. ਨਹ ਜਾਨਈ ॥"
page = 1363
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He wanders in the darkness of ego and does not think of his death."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਹੰਕਾਰ ਦੇ ਹਨੇਰੇ ਅੰਦਰ ਭਟਕਦਾ ਫਿਰਦਾ ਹੈ ਅਤੇ ਆਪਦੀ ਮੌਤ ਦਾ ਖਿਆਲ ਨਹੀਂ ਕਰਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He wanders lost in the darkness of pride, and never thinks of dying."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸੀ ਕੇ (ਗਰਬ) ਹੰਕਾਰ ਰੂਪੀ ਗੁਬਾਰ ਅੰਧੇਰੇ ਮੇਂ ਫਿਰਤਾ ਹੈ ਔ ਮਰਨਾ ਨਹੀਂ ਜਾਨਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਅਜਿਹਾ ਮਨੁੱਖ) ਅਹੰਕਾਰ ਦੇ ਹਨੇਰੇ ਵਿਚ ਤੁਰਿਆ ਫਿਰਦਾ ਹੈ, ਇਸ ਨੂੰ ਮੌਤ (ਭੀ) ਨਹੀਂ ਸੁੱਝਦੀ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਫਿਰਤਉ = ਫਿਰਦਾ ਹੈ। ਗਰਬ ਗੁਬਾਰਿ = ਅਹੰਕਾਰ ਦੇ ਹਨੇਰੇ ਵਿਚ। ਮਰਣੁ = ਮੌਤ। ਜਾਨਈ = ਜਾਨੈ, ਜਾਣਦਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Vaga perdido en la oscuridad de su orgullo y nunca piensa en la muerte,"