[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕੁੰਤੀ ਬਾਚ ॥"
page = 398

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of Kunti:"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕੁੰਤੀ ਨੇ ਕਿਹਾ:"