[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪੰਡਿਤ ਬੇਦੁ ਬੀਚਾਰਿ ਪੰਡਿਤ ॥"
page = 887
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O learned Pandit, reflect thou over the Vedas,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਵਿਦਵਾਨ ਪੰਡਤ! ਤੂੰ ਵੇਦਾਂ ਨੂੰ ਸੋਚ ਸਮਝ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O Pandit, O religious scholar, contemplate the Vedas."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਪੰਡਿਤ! ਤੂੰ ਪੰਡਿਤ ਹੋ ਕਰ, ਭਾਵ ਬਬੇਕ ਵਤੀ ਬੁਧੀ ਕਰ ਕੇ ਜੁਗਤ ਬੇਦੋਂ ਕੋ ਬੀਚਾਰ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪੰਡਿਤ! ਵੇਦ (ਆਦਿਕ ਧਰਮ-ਪੁਸਤਕ ਦੇ ਉਪਦੇਸ਼) ਨੂੰ (ਆਪਣੇ) ਮਨ ਵਿਚ ਵਸਾਈ ਰੱਖ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪੰਡਿਤ = ਹੇ ਪੰਡਿਤ! ਬੀਚਾਰਿ = ਸੋਚ = ਮੰਡਲ ਵਿਚ ਟਿਕਾਈ ਰੱਖ, ਮਨ ਵਿਚ ਵਸਾਈ ਰੱਖ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Pandit, medita en esos Vedas"