[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਇਹੁ ਮਨੁ ਚੰਚਲੁ; ਵਸਿ ਨ ਆਵੈ ॥"
page = 127
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "This unsteady mind comes not in grip."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਇਹ ਚੁਲਬੁਲਾ ਮਨੂਆ ਕਾਬੂ ਵਿੱਚ ਨਹੀਂ ਆਉਂਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "This unstable mind cannot be held steady."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਹ ਮਨ ਚੰਚਲ ਵਸ ਨਹੀਂ ਆਵਤਾ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਮਾਇਆ-ਵ੍ਹੇੜੇ ਮਨੁੱਖ ਦਾ ਇਹ ਮਨ ਚੰਚਲ (ਸੁਭਾਵ ਵਾਲਾ ਰਹਿੰਦਾ) ਹੈ, (ਉਸ ਦੇ ਆਪਣੇ ਉੱਦਮ ਨਾਲ) ਕਾਬੂ ਵਿਚ ਨਹੀਂ ਆਉਂਦਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Esta mente voluble, no la podemos controlar;"