[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਗੁ ਆਸਾ ਘਰੁ ੭ ਮਹਲਾ ੫ ॥"
page = 384
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Asa Measure 5th Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਆਸਾ ਪੰਜਵੀਂ ਪਾਤਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Raag Aasaa, Seventh House, Fifth Mehl:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਆਸਾ, ਘਰ ੭ ਵਿੱਚ ਗੁਰੂ ਅਰਜਨ ਦੇਵ ਜੀ ਦੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Asa, Mejl Guru Aryan, Quinto Canal Divino."