[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਬੋਹਿਥ ਪਰਬਤ ਨਾ ਚੜ੍ਹੈ; ਸਤਿਗੁਰੁ ਹਠ ਨਿਗ੍ਰਹੁ ਨ ਸਹੋਰੀ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "As a ship cannot mount the mountain forcibly similarly, forced control over the senses is not liked by the true Guru."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਪਰਬਤ ਜਹਾਜ਼ ਪਰ ਨਹੀਂ ਚੜ੍ਹਦਾ ਪਰ ਗੁਰੂ ਜੀ (ਪਰਬਤ ਸਰੀਖੇ) ਹਠੀ ਸੁਭਾਵਾਂ ਨੂੰ ਬੀ ਤਾਰਦੇ ਹਨ।"