[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਮਿਤ੍ਰ ਹਰੀ ॥"
page = 13

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The Lord is without any friend!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹਰੀ ਮਿਤਰ ਤੋਂ ਬਿਨਾ ਹੈ,"