[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਰਾਜਾ ਬਾਚ ਦਿਜ ਸੋਂ ॥"
page = 202

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The speech of the King addressed to the Brahmin:"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਰਾਜੇ ਨੇ ਬ੍ਰਾਹਮਣ ਪ੍ਰਤਿ ਕਿਹਾ-"