[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨੰਦ ਬਾਚ ਕੰਸ ਪ੍ਰਤਿ ॥"
page = 298

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of Vasudev addressed to Kansa:"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਨੰਦ ਨੇ ਕੰਸ ਪ੍ਰਤਿ ਕਿਹਾ:"