[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਮਸਤੰ ਜਲਾਸਰੇ ॥"
page = 2
line = 11

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Salutation to Thee O Water-Sustainer Lord!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਜਲ-ਆਸ਼ੇ (ਸਮੁੰਦਰ)! ਤੈਨੂੰ ਨਮਸਕਾਰ ਹੈ;"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨਮਸਤੰ, ਜਲਾਸਰੇ ॥"