[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤੂ ਆਪੇ ਕਰਤਾ; ਕਾਰਣ ਕਰਣਾ ॥"
page = 1076
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "My Creator Lord, thou thyself are the Doer of deeds."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ ਸਿਰਜਣਹਾਰ-ਸੁਆਮੀ, ਤੂੰ ਖ਼ੁਦ ਹੀ ਹੀ ਕੰਮਾਂ ਦੇ ਕਰਨ ਵਾਲਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "You Yourself are the Creator Lord, the Cause of causes."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਕਰਤਾਰ! ਤੂੰ ਆਪ ਹੀ ਸਭ ਕਰਣੋਂ ਕੇ ਕਰਨਹਾਰਾ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਰਭੂ! ਤੂੰ ਆਪ ਹੀ ਪੈਦਾ ਕਰਨ ਵਾਲਾ ਹੈਂ, ਤੂੰ ਆਪ ਹੀ ਜਗਤ ਦਾ ਮੂਲ ਹੈਂ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਰਤਾ = ਪੈਦਾ ਕਰਨ ਵਾਲਾ। ਕਰਣਾ = ਕਰਣ, ਜਗਤ। ਕਾਰਣ = ਮੂਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Dios, sólo Tú eres el Hacedor y la Causa."