[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਅਮਰਾਪਦੁ ਗੁਰ ਅੰਗਦਹੁ; ਅਤਿ ਅਲਖ ਅਭੇਉ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "After Guru Angad, the imperceptible and without duality, Guru Amas Das, the bestower of immortality has flourished."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਅੰਗਦ ਥੋਂ ਅਮਰ ਪਦਵੀ ਪਾਕੇ (ਗੁਰੂ ਅਮਰ ਦਾਸ ਜੀ) ਹੋਏ, (ਉਨ੍ਹਾਂ ਦੀ ਗਤੀ) ਅਲਖ ਅਤੇ ਅਭੇਉ ਹੋਈ।"