[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਲਵਸਤੁਆ ਅਲੇਖੰ ॥"
page = 138

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Thou art affectionate and accountless"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਲਿਪਤ ਹੋਣ ਵਾਲਾ ਅਤੇ ਲੇਖੇ ਤੋਂ ਪਰੇ ਹੈਂ,"