[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਾਮ ਕ੍ਰੋਧ ਲੋਭ ਮਦ ਮਾਤਾ ॥"
page = 1004
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He is intoxicated with the wine of lust, wrath and avarice,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਵਿਸ਼ੇ ਭੋਗ, ਗੁੱਸੇ ਅਤੇ ਲਾਲਚ ਦੀ ਸ਼ਰਾਬ ਨਾਲ ਮਤਵਾਲਾ ਹੋਇਆ ਹੋਇਆ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He is intoxicated with the wine of sexual desire, anger and greed;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕਾਮ, ਕ੍ਰੋਧ, ਲੋਭ ਕੇ ਮਦ ਮੇਂ ਮਸਤ ਹੂਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਮੂਰਖ!) ਤੂੰ ਕਾਮ ਕ੍ਰੋਧ ਲੋਭ (ਆਦਿਕ ਵਿਕਾਰਾਂ) ਦੇ ਨਸ਼ੇ ਵਿਚ ਮਸਤ ਹੈਂ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਦ = ਨਸ਼ਾ। ਮਾਤਾ = ਮਸਤ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y vive intoxicado con el vino de la lujuria, del enojo y la avaricia,"