[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰ ਕੀ ਸੇਵਾ; ਕਰਹੁ ਦਿਨੁ ਰਾਤਿ ॥"
page = 741
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Serve thou the Guru, day and night."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ, ਗੁਰਾਂ ਦਾ ਦਿਨ ਰਾਤ ਟਹਿਲ ਕਮਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Serve the Guru, day and night."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਤੇ ਗੁਰੋਂ ਕੀ ਸੇਵਾ ਰਾਤ ਦਿਨ ਕਰੋ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਦਿਨ ਰਾਤ ਗੁਰੂ ਦੀ (ਦੱਸੀ ਹੋਈ) ਸੇਵਾ ਕਰਿਆ ਕਰੋ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sirve al Guru día y noche"