[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਅਬ ਮਤਿ ਬਿਨਸੀ; ਦੁਸਟ ਬਿਗਾਨੀ ॥"
page = 183
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Now my evil and alien intellect is eliminated,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੁਣ ਮੇਰੀ ਮੰਦੀ ਤੇ ਓਪਰੀ ਅਕਲ ਨਾਸ ਹੋ ਗਈ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Now, my evil sense of alienation is eliminated,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਮਨ! ਜੋ ਬੇਗਾਨੇ ਕਰਨ ਵਾਲੀ, ਅਰਥਾਤ ਅਗ੍ਯਾਨ ਸਹਤ ਦੁਸਟ ਭਾਵ ਕੇ ਧਾਰਨੇ ਵਾਲੀ ਥੀ ਵਹੁ ਬੁਧੀ ਅਬ ਨਸ਼ਟ ਹੂਈ ਹੈ॥☬ਪ੍ਰਸ਼ਨ: ਕਬ ਬਿਨਸੀ ਹੈ?☬ਉੱਤ੍ਰ:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਤਦੋਂ ਤੋਂ ਮੇਰੀ ਭੈੜੀ ਤੇ ਬੇ-ਸਮਝੀ ਵਾਲੀ ਮਤਿ ਦੂਰ ਹੋ ਗਈ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਦੁਸਟ = ਭੈੜੀ। ਬਿਗਾਨੀ = ਬੇਗਿਆਨੀ, ਬੇਸਮਝੀ ਵਾਲੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El sentido malvado del “otro” me ha dejado"