[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਲੰਕੰ ਪ੍ਰਣਾਸ ਹੈਂ ॥"
page = 8
line = 15

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Thou art the Destroyer of blemishes!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਹੇ ਪ੍ਰਭੂ!) ਤੂੰ ਕਲੰਕ ਨੂੰ ਨਸ਼ਟ ਕਰਨ ਵਾਲਾ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਕਲੰਕੰ, ਪ੍ਰਣਾਸ ਹੈਂ ॥"