[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਜਿਉਂ ਜਾਨਹੁ; ਤਿਉਂ ਲੇਹੁ ਸੁਧਾਰਾ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "What ever may be the means, please regenerate us,"