[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਨ੍ਹਾਣ ਦੇ ਚਰਿੱਤ੍ਰ ਉਤੇ ਰੱਬ ਦੀ ਮਿਹਰ ਹੋਵੇ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਰਹਿਮਤਿ ਹੱਕ ਬਾਦ ਬਰ ਔਜ਼ਾਇ ਸ਼ਾਣ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Guru Gobind Singh is the grace of the entire brilliance. (106)"