[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਕੀ ਈਰਾਨ ਦਾ ਸੁਲਤਾਨ ਤੇ ਕੀ ਖ਼ੁਤਨ ਦਾ ਖ਼ਾਨ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਚਿ ਸੁਲਤਾਨਿ ਈਰਾਂ ਚਿ ਖ਼ਾਨਿ ਖ਼ੁਤਨ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Whether it be the Sultaan of Iran, or Khan of Khutan"