[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਨਮੰਡ ਰਾਜ ਜੁਝਾਰ ॥"
page = 155

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "An impetuous warrior-king"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਬਿਨਾ ਕਿਸੇ ਦੀ ਸਹਾਇਤਾ ਦੇ ਜੁਝਾਰੂ ਸੂਰਮਾ ਸੀ।"