[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਨਖੰਡ ਰਾਜੁ ਕਮਾਇ ॥"
page = 155

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He then ruled uninterrupted."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਸ ਨੇ) ਅਖੰਡ ਰਾਜ ਕਮਾਇਆ"