[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਪਰਸੁ ਰਾਮ ਬਾਚ ॥"
page = 215

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of Parashuram :"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਪਰਸੁਰਾਮ ਕਹਿਣ ਲੱਗਾ-"