[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨ ਤਾਤੈ ਨ ਮਾਤੈ ॥"
page = 8
line = 9

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Lord !  Thou art Fatherless and Motherless. O Lord !"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਨਾ ਤੇਰਾ ਕੋਈ ਪਿਤਾ ਹੈ ਨਾ ਮਾਤਾ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨ ਤਾਤੈ, ਨ ਮਾਤੈ ॥"