[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਰਬ ਕਲਾ; ਸੋਈ ਪਰਬੀਨ ॥"
page = 1298
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He alone is versed in all arts and is wise,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕੇਵਲ ਉਹ ਹੀ ਸਾਰਿਆਂ ਹੁਨਰਾਂ ਦਾ ਮਾਹਰ ਤੇ ਸਿਆਣਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Those whom the Guru blesses with the Mantra of the Naam"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸਰਬ (ਕਲਾ) ਸਕਤੀਓਂ ਕਰ ਸੋਈ ਪੁਰਸ ਪ੍ਰਬੀਨ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਹੀ ਮਨੁੱਖ ਸਾਰੀਆਂ ਆਤਮਕ ਤਾਕਤਾਂ ਵਿਚ ਸਿਆਣਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਲਾ = ਆਤਮਕ ਤਾਕਤ। ਪਰਬੀਨ = ਸਿਆਣਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "A quienes el Guru bendice con el Mantra del Naam,"