[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੋਹਿ ਦੀਨ; ਹਰਿ ਹਰਿ ਹਰਿ ਸੇਵਾ ॥੬॥"
page = 913
line = 4

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "I, the humble one, serve my God, the Lord Master."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਆਜ਼ਿਜ਼, ਆਪਣੇ ਵਾਹਿਗੁਰੂ ਸੁਆਮੀ ਮਾਲਕ ਦੀ ਘਾਲ ਕਮਾਉਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I am meek; I serve the Lord, Har, Har, Har. ||6||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਗਰੀਬ ਨੇ ਮਨ ਬਾਣੀ ਸਰੀਰ ਕਰ ਕੇ ਹਰੀ ਕੋ ਹੀ ਸੇਵਿਆ ਹੈ॥੬॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰ ਮੈਂ ਗ਼ਰੀਬ ਸਿਰਫ਼ ਪਰਮਾਤਮਾ ਦੀ ਭਗਤੀ ਹੀ ਕਰਦਾ ਹਾਂ ॥੬॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੇਵਾ = ਭਗਤੀ ॥੬॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pero yo, el Devoto de Dios, sólo Lo sigo a Él. (6)"