[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਇਕੋ ਮੇਰਾ ਮਸਲਤੀ; ਭੰਨਣ ਘੜਨ ਸਮਰਥੁ ॥"
page = 958
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "God alone is my counselor, who is potent to destroy and to create."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕੇਵਲ ਵਾਹਿਗੁਰੂ ਹੀ ਮੇਰਾ ਸਲਾਹਕਾਰ ਹੈ ਜੋ ਢਾਹੁਣ ਅਤੇ ਰਚਨ ਦੇ ਯੋਗ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He is my only counselor, all-powerful to destroy and create."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਕ ਹਰੀ ਹੀ ਮੇਰਾ ਸਲਾਹਕਾਰ ਹੈ, ਜੋ ਭੰਨਣੇ ਔ ਘੜਨੇ ਕਉ ਸਾਮਰਥ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਸਭ ਜੀਵਾਂ ਨੂੰ) ਪੈਦਾ ਕਰਨ ਤੇ ਮਾਰਨ ਦੀ ਤਾਕਤ ਰੱਖਣ ਵਾਲਾ ਇਕ ਪਰਮਾਤਮਾ ਹੀ ਮੇਰਾ ਸਲਾਹਕਾਰ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਸਲਤੀ = ਸਲਾਹਕਾਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Tomo consejo sólo de nuestro Dios."