[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਸਾ ਮਹਲਾ ੫ ॥"
page = 457
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Asa 5th Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਸਾ ਪੰਜਵੀਂ ਪਾਤਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Aasaa, Fifth Mehl,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Asa, Mejl Guru Aryan, Quinto Canal Divino."