[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਐਸੀ ਬਾਤ ਸੁਨੀ ਨਹਿ ਹੇਰੀ ॥"
page = 1213

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਜੋ ਤੁਹਾਡੀ ਇਸਤਰੀ ਦੀ ਹਾਲਤ ਹੋਈ ਹੈ,"