[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਇਮ ਆਗਿਆ ਤਹ ਤੈ ਤਿਨਿ ਆਈ ॥੩॥"
page = 174

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "There they eulogized KAL, the destroyer Lord and received the following message.3."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਥੋਂ ਉਨ੍ਹਾਂ ਨੂੰ ਇਸ ਤਰ੍ਹਾਂ ਦੀ ਆਗਿਆ ਹੋਈ ॥੩॥"