[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗਿਆਨੀ; ਗਿਆਨੁ ਕਮਾਵਹਿ ॥"
page = 71
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The theologian practises theology."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਬ੍ਰਹਿਮ-ਬੇਤਾ ਬ੍ਰਹਿਮ ਵਿਦਿਆ ਦਾ ਅਭਿਆਸ ਕਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "and the wise practice spiritual wisdom,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "(ਗਿਆਨੀ) ਗ੍ਯਾਨ ਕਮਾਉਣੇ ਸੇ ਹੀ ਮਾਨਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਵਿਦਵਾਨ ਲੋਕ ਧਰਮ-ਚਰਚਾ ਕਰਦੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗਿਆਨੀ = ਵਿਦਵਾਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "el sabio la sabiduría,"