[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੈ ਖੋਜਤ ਖੋਜਤ ਜੀ; ਹਰਿ ਨਿਹਚਲੁ ਸੁ ਘਰੁ ਪਾਇਆ ॥"
page = 785
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Searching, searching, I have found immovable Home of the Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਭਾਲਦਿਆਂ, ਭਾਲਦਿਆਂ, ਮੈਂ ਪ੍ਰਭੂ ਦਾ ਅਹਿੱਲ ਗ੍ਰਹਿ ਲੱਭ ਲਿਆ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I searched and searched, and found the immovable, unchanging home of the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਖੋਜਤਿਆਂ ਖੋਜਤਿਆਂ ਹਰੀ ਜੋ ਨਿਸਚਲ ਘਰ ਹੈ, ਸੋ ਪਾਇਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਭਾਲ ਕਰਦਿਆਂ ਕਰਦਿਆਂ ਮੈਂ ਹਰੀ ਪ੍ਰਭੂ ਦਾ ਉਹ ਟਿਕਾਣਾ ਲੱਭ ਲਿਆ ਹੈ, ਜੋ ਕਦੇ ਭੀ ਡੋਲਦਾ ਨਹੀਂ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਖੋਜਤ ਖੋਜਤ = ਭਾਲ ਕਰਦਿਆਂ ਕਰਦਿਆਂ। ਜੀ = ਹੇ ਭਾਈ! ਸੁ ਘਰੁ = ਉਹ ਘਰੁ, ਉਹ ਟਿਕਾਣਾ। ਨਿਹਚਲੁ = ਕਦੇ ਨਾਸ ਨਾ ਹੋਣ ਵਾਲਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Lo busqué, encontré Su Hogar Eterno y me di cuenta de que todo lo demás es ilusorio y me quedé con Sus Pies de Loto."