[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾ ਕੋ ਚਤੁਰੁ; ਨਾਹੀ ਕੋ ਮੂੜਾ ॥"
page = 238
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By himself none in wise and none unwise."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੇ ਆਪ ਨਾਂ ਕੋਈ ਸਿਆਣਾ ਹੈ ਤੇ ਨਾਂ ਹੀ ਮੂਰਖ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "No one is clever, and no one is foolish."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਅਪਨੇ ਬਲ ਤੇ ਨਾ ਕੋਈ ਚਤਰ ਹੈ ਔਰ ਨਾ ਕੋਈ ਮੂਰਖ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਪਰ ਆਪਣੇ ਆਪ) ਨਾਹ ਕੋਈ ਮਨੁੱਖ ਸਿਆਣਾ ਬਣ ਸਕਦਾ ਹੈ, ਨਾਹ ਕੋਈ ਮਨੁੱਖ (ਆਪਣੀ ਮਰਜ਼ੀ ਨਾਲ) ਮੂਰਖ ਟਿਕਿਆ ਰਹਿੰਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਚਤੁਰੁ = ਚਾਲਾਕ, ਸਿਆਣਾ। ਮੂੜਾ = ਮੂਰਖ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "No hay nadie sabio, ni nadie tonto;"