[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕ੍ਰਿਸਨਾਵਤਾਰ ॥"
page = 290

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "CHAUBIS AVTAR(Contd.)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕ੍ਰਿਸਨਾਵਤਾਰ:"