[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਤੇਰੀ ਗਲੀ ਵਿਚ ਮੰਗਣ ਦਾ ਕੰਮ ਬਾਦਸ਼ਾਹੀ ਨਾਲੋਣ ਚੰਗੇਰਾ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਗਦਾਈ ਕਰਦਨਿ ਕੂਇ ਤੂ ਬਿਹ ਜ਼ਿ ਸੁਲਤਾਨੀਸਤ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "And, one can get to know him only through meditation. (224)"