[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਭਗਤ ਜੀਵਹਿ; ਗੁਣ ਗਾਇ ਅਪਾਰਾ ॥"
page = 103
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The saints sustain life by singing the praises of the endless One."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੰਤ ਅੰਤ-ਰਹਿਤ ਪੁਰਖ ਦਾ ਜੱਸ ਗਾਇਨ ਕਰਨ ਦੁਆਰਾ ਜੀਉਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "His devotees live by singing the Glorious Praises of the Infinite Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਔਰ ਭਗਤ ਜਨ ਤੇਰੇ ਗੁਣ ਗਾਇ ਕਰ ਜੀਵਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਭਗਤ ਬੇਅੰਤ ਪ੍ਰਭੂ ਦੇ ਗੁਣ ਗਾ ਕੇ ਆਤਮਕ ਜ਼ਿੰਦਗੀ ਹਾਸਲ ਕਰਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜੀਵਹਿ = ਆਤਮਕ ਜੀਵਨ ਪ੍ਰਾਪਤ ਕਰਦੇ ਹਨ। ਗਾਇ = ਗਾ ਕੇ। ਅਪਾਰਾ = ਬੇਅੰਤ ਪ੍ਰਭੂ ਦੇ ਗੁਣ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "el Devoto vive para cantar Su Eterna Alabanza."