[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਕੀ ਤਾਰੇ ਕੀ ਆਸਮਾਨ, ਸਾਰੇ ਹੀ ਉਸਦੀ ਪਰਜਾ ਹਨ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਚਿਹ ਅੰਜਮ ਚਿਹ ਅਫ਼ਲਾਕ ਮਹਿਕੂਮਿ ਊ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Whether (we talk about) the stars or the skies, all are his subjects,"