[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਹੁ ਨਾਨਕ; ਜਾ ਕੇ ਨਿਰਮਲ ਭਾਗ ॥"
page = 807
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Says Nanak, he who has an immaculate destiny,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਜੀ ਆਖਦੇ ਹਨ, ਜਿਸ ਦੀ ਪਵਿੱਤਰ ਪ੍ਰਾਲਬਧ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Says Nanak, one who has such immaculate destiny"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਜਿਨਾਂ ਪੁਰਸਾਂ ਕੇ (ਨਿਰਮਲ) ਉਜਲ ਭਾਗ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਨਾਨਕ ਆਖਦਾ ਹੈ- ਜਿਸ ਮਨੁੱਖ ਦੇ ਚੰਗੇ ਭਾਗ (ਜਾਗਦੇ ਹਨ)"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨਾਨਕ = ਹੇ ਨਾਨਕ! ਜਾ ਕੇ = ਜਿਸ (ਮਨੁੱਖ) ਦੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dice Nanak, aquél que tiene un Destino inmaculado,"