[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤੇਰੇ ਬੰਕੇ ਲੋਇਣ; ਦੰਤ ਰੀਸਾਲਾ ॥"
page = 567
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Beauteous are Thy eyes and relish giving Thy teeth."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੁੰਦਰ ਹਨ ਤੇਰੇ ਨੈਣ ਅਤੇ ਰੱਬ ਦਾ ਘਰ (ਅਨੰਦ-ਦਾਇਕ) ਤੇਰੇ ਦੰਦ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Your eyes are so beautiful, and Your teeth are delightful."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਪਰਮੇਸ੍ਵਰ! ਤੇਰੇ ਨੇਤ੍ਰ (ਬੰਕੇ) ਸੁੰਦਰ ਹੈਂ ਔਰ ਦੰਤ ਭੀ ਸੁੰਦਰ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਸੁੰਦਰ ਹਨ ਨੈਣ ਅਤੇ ਰਸੀਲੇ ਦੰਦ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਬੰਕੇ = ਬਾਂਕੇ। ਲੋਇਣ = ਅੱਖਾਂ। ਦੰਤ = ਦੰਦ। ਰਸੀਲਾ = (ਰਸ-ਆਲਯ) ਸੋਹਣੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Bellos son Tus ojos, relucientes Tus dientes; Tu nariz tiene tanta gracia,"