// Generated by packages/design/scripts/generate-icons.mjs — do not edit.
// Source of truth: packages/design/icons.md

package com.shabados.android

/**
 * Icon names shared with the iOS app, keyed by what they *mean* rather than by what
 * they look like.
 *
 * Values are **drawable resource names**, not resource ids: the vector assets are
 * imported by hand (Android Studio > New > Vector Asset > Clip Art) and this file is
 * generated, so it cannot reference an `R.drawable` entry that does not exist yet
 * without breaking every build until every icon is imported. Resolve with
 * `context.resources.getIdentifier`, or switch these to `R.drawable.*` once the
 * full set is in `res/drawable/` — at which point a missing icon becomes a compile
 * error, which is better.
 *
 * The Material Symbols name intended for each is in packages/design/icons.md.
 */
object AppIcons {
  /** Open the Journeys sidebar. Specified by the author. */
  const val journeys = "ic_journeys"

  /** Journeys sidebar is open; tapping returns to the viewer. Same shape, filled. */
  const val journeysActive = "ic_journeys_active"

  /** Open the Controls sidebar. Lucide `settings-2`. */
  const val controls = "ic_controls"

  /** Controls sidebar is open. PROPOSED, as above. Lucide `settings-2`. */
  const val controlsActive = "ic_controls_active"

  /** Enter fullscreen. PROPOSED. */
  const val fullscreen = "ic_fullscreen"

  /** Exit fullscreen. Unlike journeysActive/controlsActive this is a distinct Lucide glyph, not the same shape filled — Lucide has no fullscreen fill variant. PROPOSED. */
  const val fullscreenActive = "ic_fullscreen_active"

  /** Font size of the reading area. Specified by the author. */
  const val zoom = "ic_zoom"

  /** Secondary text size relative to the Gurmukhi line. Specified by the author. */
  const val ratio = "ic_ratio"

  /** Font weight. Specified by the author. */
  const val weight = "ic_weight"

  /** Reading column width. Wide surfaces only. PROPOSED — not specified. */
  const val width = "ic_width"

  /** Rendering mode: classic / saral / reader / presenter. Specified by the author. */
  const val mode = "ic_mode"

  /** Centre the text. Specified by the author. */
  const val centered = "ic_centered"

  /** Larivaar — remove spaces from the Gurmukhi line. Specified by the author. */
  const val continuous = "ic_continuous"

  /** Colour vishraam words. Specified by the author. */
  const val pauses = "ic_pauses"

  /** Transliteration schemes, computed by packages/gurmukhi. Specified by the author. */
  const val pronunciations = "ic_pronunciations"

  /** Translation languages. Specified by the author. */
  const val translations = "ic_translations"

  /** Toggle a line-notes panel in Controls. PROPOSED. */
  const val notes = "ic_notes"

  /** Choose a full-screen card — Blank, Waheguru, Fateh, Mul Mantar, Bole So Nihal — to display over the text. PROPOSED. */
  const val slideshow = "ic_slideshow"

  /** Light / dark / auto. Specified by the author. */
  const val appearance = "ic_appearance"

  /** Filter in All recents: All / Pinned / Recent / Inactive. PROPOSED. */
  const val filter = "ic_filter"

  /** Trailing chevron on the All recents row. PROPOSED. */
  const val disclosure = "ic_disclosure"

  /** Open the Library — collections, bookmarks, assets and their tables of contents. Pinned below Recents in the Journeys sidebar. Specified by the author ([library.md](../../docs/requirements/library.md), [reading-shell.md](../../docs/requirements/reading-shell.md#getting-between-them)). */
  const val library = "ic_library"

  /** About Shabad OS — links, social, feedback. PROPOSED. */
  const val about = "ic_about"

  /** Search. PROPOSED — the shell has no specified entry point yet. */
  const val search = "ic_search"

  /** Pin a journey. PROPOSED. */
  const val pin = "ic_pin"

  /** Pinned state. PROPOSED. */
  const val pinned = "ic_pinned"

  /** Rename a journey. PROPOSED. */
  const val rename = "ic_rename"

  /** Move an entry to a journey's Removed section. Not a delete. PROPOSED. */
  const val remove = "ic_remove"

  /** Restore a removed entry to its original position. PROPOSED. */
  const val undo = "ic_undo"

  /** Share a journey — a bookmark position, or a Defined journey. PROPOSED. */
  const val share = "ic_share"

  /** Next entry in a journey. PROPOSED. */
  const val next = "ic_next"

  /** Previous entry in a journey. PROPOSED. */
  const val previous = "ic_previous"

  /** Consecutive days with a complete Defined instance. PROPOSED. */
  const val streak = "ic_streak"

  /** Advanced settings, one level beyond the Controls sidebar. PROPOSED. */
  const val settings = "ic_settings"

  /** Return from Settings to the Controls sidebar. PROPOSED. */
  const val back = "ic_back"

  /** Close a tab. Removes it from the journey permanently; the timeline keeps it. PROPOSED. */
  const val close = "ic_close"

  /** A tracked collection or bookmark. PROPOSED. */
  const val tracked = "ic_tracked"
}
