package com.shabados.android

import android.content.res.AssetManager
import org.json.JSONObject

/**
 * A line of gurbani. [id] is the corpus line id and is stable across corpus
 * versions — see docs/requirements/data-model.md. Nothing here addresses a line by
 * its position.
 */
data class Line(val id: String, val gurmukhi: String)

data class Bani(
  val id: String,
  val latin: String,
  val gurmukhi: String,
  /** The bani's own grouping, not the source's structure. */
  val sections: List<List<Line>>,
)

/**
 * A bani flattened into one addressable sequence.
 *
 * The reader needs stable, unique keys per row so the scroll position can be
 * anchored to a specific line while the type size changes.
 */
sealed interface ReaderItem {
  val id: String

  data class LineItem(override val id: String, val gurmukhi: String) : ReaderItem
  data class Divider(override val id: String) : ReaderItem
}

fun Bani.items(): List<ReaderItem> = buildList {
  sections.forEachIndexed { sectionIndex, section ->
    section.forEachIndexed { lineIndex, line ->
      add(ReaderItem.LineItem("$sectionIndex.$lineIndex", line.gurmukhi))
    }
    if (sectionIndex < sections.lastIndex) add(ReaderItem.Divider("d$sectionIndex"))
  }
}

object Corpus {
  /**
   * Generated by `bun run database:export-bundled` in `database/`.
   * Never hand-edited: scripture edits go through the database component.
   *
   * Parsed with org.json, which ships in the platform — a JSON library would be a
   * dependency, a Gradle plugin, and a version to keep in step, for ~20 lines.
   */
  fun load(assets: AssetManager): List<Bani> {
    val text = assets.open("banis.json").bufferedReader().use { it.readText() }
    val banis = JSONObject(text).getJSONArray("banis")

    return List(banis.length()) { b ->
      val bani = banis.getJSONObject(b)
      val name = bani.getJSONObject("name")
      val sections = bani.getJSONArray("sections")

      Bani(
        id = bani.getString("id"),
        latin = name.optString("Latn", bani.getString("id")),
        gurmukhi = name.optString("Guru", ""),
        sections = List(sections.length()) { s ->
          val lines = sections.getJSONArray(s)
          List(lines.length()) { l ->
            val line = lines.getJSONObject(l)
            Line(line.getString("id"), line.getString("gurmukhi"))
          }
        },
      )
    }
  }
}
