// Generated by packages/design/scripts/generate-tokens.mjs — do not edit.
// Source of truth: packages/design/tokens.md

package com.shabados.android

import androidx.compose.ui.graphics.Color

/** Colour and type shared with the iOS app. */
object DesignTokens {
  /** light-dark(#f4f1ee, #000000) */
  val backgroundLight = Color(0xFFF4F1EE)
  val backgroundDark = Color(0xFF000000)

  /** light-dark(#ffffff, #222222) */
  val backgroundBaseLight = Color(0xFFFFFFFF)
  val backgroundBaseDark = Color(0xFF222222)

  /** light-dark(#23211f, #ffffff) */
  val foregroundLight = Color(0xFF23211F)
  val foregroundDark = Color(0xFFFFFFFF)

  /** light-dark(#575552, #bebebe) */
  val foregroundMutedLight = Color(0xFF575552)
  val foregroundMutedDark = Color(0xFFBEBEBE)

  /** light-dark(#2381e0, #3c96f7) */
  val uiLight = Color(0xFF2381E0)
  val uiDark = Color(0xFF3C96F7)

  /** light-dark(#8a472a, #ffd493) */
  val vishraamHeavyLight = Color(0xFF8A472A)
  val vishraamHeavyDark = Color(0xFFFFD493)

  /** light-dark(#13662b, #c4eda8) */
  val vishraamMediumLight = Color(0xFF13662B)
  val vishraamMediumDark = Color(0xFFC4EDA8)

  /** light-dark(#5e438e, #decbff) */
  val vishraamLightLight = Color(0xFF5E438E)
  val vishraamLightDark = Color(0xFFDECBFF)

  const val TONER_OPACITY = 0.08f

  const val WEIGHT_PRIMARY = 550f
  const val WEIGHT_LATIN = 475f
  const val WEIGHT_SECONDARY = 440f

  const val RATIO_DEFAULT = 0.6f

  const val DEFAULT_SIZE = 20f
  const val MIN_SIZE = 14f
  const val MAX_SIZE = 56f

  /**
   * Total line box as a multiple of font size, so it holds when zoomed. Gurmukhi
   * stacks vowel signs above and below the base line; at 1.0 the lagaa matraa
   * collide with the line above.
   */
  const val LINE_HEIGHT_RATIO = 1.2f

  fun clamp(size: Float) = size.coerceIn(MIN_SIZE, MAX_SIZE)
}
