[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾ ਕੋ ਹੋਆ; ਤੋਲਣਹਾਰਾ ॥"
page = 1067
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "No one can ever weigh it."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕੋਈ ਭੀ ਇਸ ਨੂੰ ਕਦੇ ਜੋਖ ਨਹੀਂ ਸਕਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "No one can weigh it."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਕੋ ਤੋਲਨੇਹਾਰਾ ਕੋਈ ਨਹੀਂ ਹੋਇਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਕੋਈ ਭੀ ਜੀਵ (ਹਰਿ-ਨਾਮ ਦਾ) ਮੁੱਲ ਪਾਣ-ਜੋਗਾ ਨਹੀਂ ਹੋ ਸਕਿਆ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕੋ = ਕੋਈ ਭੀ ਮਨੁੱਖ। ਤੋਲਣਹਾਰਾ = ਮੁੱਲ ਪਾਣ ਜੋਗਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Eres tú quien evalúas y le das la estimación a todos mediante la palabra del Shabd del Guru y,"