[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੁਵਰਨ ਆਦਿ ਦਾਨੰ ॥"
page = 137

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The charities like gold etc.,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸੋਨੇ ਦਾ ਦਾਨ ਦੇਣਾ,"