[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮਾਧਉ ਦਾਰੁਨ ਦੁਖੁ; ਸਹਿਓ. ਨ ਜਾਇ ॥"
page = 1194
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "what am I before it? O my Lord, this terrible pain, I can endure not."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਮੇਰੇ ਸੁਆਮੀ! ਇਹ ਭਿਆਨਕ ਪੀੜ ਮੈਂ ਸਹਾਰ ਨਹੀਂ ਸਕਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O Lord, I cannot endure this agonizing pain."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਮਾਧੋ! (ਦਾਰੁਨ) ਕਠਨ ਕਾਮ ਕਾ ਦੁਖ ਸਹਾਰਾ ਨਹੀਂ ਜਾਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਮੇਰੇ ਮਾਧੋ! ਆਪਣੀ ਚੰਚਲ ਮੱਤ ਅੱਗੇ ਮੇਰੀ ਕੋਈ ਪੇਸ਼ ਨਹੀਂ ਜਾਂਦੀ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਦਾਰੁਨ = ਭਿਆਨਕ, ਡਰਾਉਣਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Dios, insoportable es mi dolor y no sé si tendrá algún fin,"