[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਏਕੁ ਸਿਮਰਿ ਏਕੁ ਸਿਮਰਿ; ਏਕੁ ਸਿਮਰਿ ਪਿਆਰੇ ॥"
page = 679
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Remember thou the one Lord. remember the one Lord. remember the one Lord, O my love."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਇਕ ਸਾਹਿਬ ਦਾ ਚਿੰਤਨ ਕਰ, ਇਕ ਸਾਹਿਬ ਦਾ ਚਿੰਤਨ ਕਰ, ਇਕ ਸਾਹਿਬ ਦਾ ਚਿੰਤਨ ਕਰ, ਹੇ ਮੇਰੇ ਪ੍ਰੀਤਮਾ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Meditate in remembrance on the One Lord; meditate in remembrance on the One Lord; meditate in remembrance on the One Lord, O my Beloved."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਪਿਆਰੇ! ਏਕ ਹਰੀ ਕੋ ਹੀ ਮਨ ਤਨ ਬਾਣੀ ਕਰ ਕੇ ਸਿਮਰਨ ਕਰੋ॥☬ਸੋ ਹਰਿ ਕੈਸਾ ਹੈ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪਿਆਰੇ! ਸਦਾ ਹੀ ਪਰਮਾਤਮਾ ਦਾ ਨਾਮ ਸਿਮਰਿਆ ਕਰ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਿਆਰੇ = ਹੇ ਪਿਆਰੇ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Medita recordando al Único Señor, medita recordando al Único Señor, medita recordando al Único Señor. Oh mi amado,"