[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਿਹ ਸਿਮਰਨਿ; ਤੇਰੀ ਗਤਿ ਹੋਇ ॥"
page = 971
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Contemplating whom thou art emancipate;"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਦਾ ਆਰਾਧਨ ਕਰਨ ਦੁਆਰਾ ਤੂੰ ਬੰਦਖਲਾਸ ਹੁੰਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Remembering Him in meditation, you shall obtain salvation."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਸਿਮਰਨ ਤੇ ਤੇਰੀ ਗਤੀ ਹੋਵੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਸਿਮਰਨ ਦੀ ਬਰਕਤਿ ਨਾਲ ਤੇਰੀ ਉੱਚੀ ਆਤਮਕ ਅਵਸਥਾ ਬਣਦੀ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗਤਿ = ਮੁਕਤੀ, ਉੱਚੀ ਆਤਮਕ ਅਵਸਥਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Contemplando al Señor, uno es emancipado;"