[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਸਾ ਮਹਲਾ ੧ ਪੰਚਪਦੇ₆ ॥"
page = 354
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Asa Measure 1st Guru. Panchpade."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਆਸਾ ਪਹਿਲੀ ਪਾਤਸ਼ਾਹੀ ਪੰਚਪਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Aasaa, First Mehl, Panch-Padhay:"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਛੇ ਸਬਦ ਪਾਂਚ ੨ ਪੌੜੀਆਂ ਕੇ ਆਵੇਂਗੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Asa, Mejl Guru Nanak, Primer Canal Divino."