[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਸੀਹ ਬਾਣ ਅਰਚਾਹਿ ਕੈ ਅੰਗਿ ਝਾਰੇ ॥"
page = 705

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He attacked Pavitarta with twenty-five arrows and Arcchana with eighty arrows, whose limbs were chopped by him"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਸੀ ਬਾਣ 'ਅਰਚਾ' ਦੇ ਸ਼ਰੀਰ ਵਿਚ ਝਾੜੇ ਹਨ।"