#!/usr/bin/env node
//
// Generates platform token files from packages/design/tokens.md.
//
//   node packages/design/scripts/generate-tokens.mjs
//
// Plain Node with no dependencies, deliberately: this has to run from apps/build.sh
// on a machine that may have neither bun nor a JS toolchain set up, and a generator
// that cannot run is a generator that gets bypassed.
//
// The apps share no code (ADR-0010 is undecided), so without this the same decision
// gets written twice and drifts. Anything both apps must agree on belongs here.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')

// The source is markdown, not JSON, so a token can sit next to the sentence
// explaining it — see packages/design/tokens.md. Only the tables are read; prose is
// ignored. Parsing is deliberately strict: an unrecognised table shape is a silent
// omission otherwise, and a missing token becomes a compile error three files away.
const md = readFileSync(join(root, 'packages/design/tokens.md'), 'utf8')

/** Rows of a markdown table inside the named `##` section. */
const section = (heading) => {
  const body = md.split(new RegExp(`^## ${heading}$`, 'm'))[1]
  if (!body) throw new Error(`packages/design/tokens.md: no "## ${heading}" section`)
  return body.split(/^## /m)[0]
}

const colorRows = [...section('Colour').matchAll(/^\| (\w+) \| `(#[0-9a-fA-F]{6})` \| `(#[0-9a-fA-F]{6})` \|$/gm)]
if (!colorRows.length) throw new Error('packages/design/tokens.md: no colour rows parsed')
const color = Object.fromEntries(colorRows.map(([, name, light, dark]) => [name, { light, dark }]))

const scalars = (heading) => {
  const rows = [...section(heading).matchAll(/^\| (\w+) \| `([\d.]+)` \|$/gm)]
  if (!rows.length) throw new Error(`packages/design/tokens.md: no rows parsed under "## ${heading}"`)
  return Object.fromEntries(rows.map(([, name, value]) => [name, Number(value)]))
}

const opacity = scalars('Opacity')
const weight = scalars('Weight')
const type = scalars('Type')

for (const key of ['defaultSize', 'lineHeight', 'minSize', 'maxSize']) {
  if (type[key] === undefined) throw new Error(`packages/design/tokens.md: type.${key} missing`)
}
if (opacity.toner === undefined) throw new Error('packages/design/tokens.md: opacity.toner missing')
const lineHeightRatio = +(type.lineHeight / type.defaultSize).toFixed(4)

const rgb = (hex) => {
  const n = parseInt(hex.replace('#', ''), 16)
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255]
}
const swiftComponents = (hex) => {
  const [r, g, b] = rgb(hex).map((c) => (c / 255).toFixed(4))
  return `red: ${r}, green: ${g}, blue: ${b}`
}
const kotlinHex = (hex) => `0xFF${hex.replace('#', '').toUpperCase()}`

const banner = (comment) => `${comment} Generated by packages/design/scripts/generate-tokens.mjs — do not edit.
${comment} Source of truth: packages/design/tokens.md`

// ---------------------------------------------------------------- Swift

const swiftColor = (name, pair) => `  /// light-dark(${pair.light}, ${pair.dark})
  static let ${name} = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(${swiftComponents(pair.dark)}, alpha: 1)
      : UIColor(${swiftComponents(pair.light)}, alpha: 1)
  })`

const swift = `${banner('//')}

import SwiftUI
import UIKit

/// Colour and type shared with the Android app. A UIColor provider is used rather
/// than reading \`@Environment(\\.colorScheme)\` so the value resolves itself —
/// including inside UIKit-backed views that never see the SwiftUI environment.
enum DesignTokens {
${Object.entries(color).map(([k, v]) => swiftColor(k, v)).join('\n\n')}

  static let tonerOpacity: Double = ${opacity.toner}

  static let weightPrimary: Double = ${weight.weightPrimary}
  static let weightLatin: Double = ${weight.weightLatin}
  static let weightSecondary: Double = ${weight.weightSecondary}

  static let ratioDefault: Double = ${type.ratioDefault}

  static let defaultSize: Double = ${type.defaultSize}
  static let minSize: Double = ${type.minSize}
  static let maxSize: Double = ${type.maxSize}

  /// Total line box as a multiple of font size, so it holds when zoomed.
  /// Gurmukhi stacks vowel signs above and below the base line; at 1.0 the lagaa
  /// matraa collide with the line above.
  static let lineHeightRatio: Double = ${lineHeightRatio}

  static func clamp(_ size: Double) -> Double {
    min(maxSize, max(minSize, size))
  }

  /// SwiftUI's \`lineSpacing\` is *extra* space on top of the font's natural line
  /// height, not the total line box, so the target has to be measured against the
  /// real font metrics. Android's \`lineHeight\` is the total directly.
  static func lineSpacing(for size: Double, fontName: String) -> Double {
    let natural = UIFont(name: fontName, size: size)?.lineHeight ?? size * 1.2
    return max(0, size * lineHeightRatio - natural)
  }
}
`

// --------------------------------------------------------------- Kotlin

const kotlinColor = (name, pair) => `  /** light-dark(${pair.light}, ${pair.dark}) */
  val ${name}Light = Color(${kotlinHex(pair.light)})
  val ${name}Dark = Color(${kotlinHex(pair.dark)})`

const kotlin = `${banner('//')}

package com.shabados.android

import androidx.compose.ui.graphics.Color

/** Colour and type shared with the iOS app. */
object DesignTokens {
${Object.entries(color).map(([k, v]) => kotlinColor(k, v)).join('\n\n')}

  const val TONER_OPACITY = ${opacity.toner}f

  const val WEIGHT_PRIMARY = ${weight.weightPrimary}f
  const val WEIGHT_LATIN = ${weight.weightLatin}f
  const val WEIGHT_SECONDARY = ${weight.weightSecondary}f

  const val RATIO_DEFAULT = ${type.ratioDefault}f

  const val DEFAULT_SIZE = ${type.defaultSize}f
  const val MIN_SIZE = ${type.minSize}f
  const val MAX_SIZE = ${type.maxSize}f

  /**
   * Total line box as a multiple of font size, so it holds when zoomed. Gurmukhi
   * stacks vowel signs above and below the base line; at 1.0 the lagaa matraa
   * collide with the line above.
   */
  const val LINE_HEIGHT_RATIO = ${lineHeightRatio}f

  fun clamp(size: Float) = size.coerceIn(MIN_SIZE, MAX_SIZE)
}
`

// ------------------------------------------------- Android XML resources
//
// Compose cannot style the *window* — the surface behind it is set by the framework
// theme in res/values/themes.xml, which needs real colour resources. Without these
// the window stays light in dark mode, showing as a pale flash on launch.

const androidXml = (variant) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packages/design/scripts/generate-tokens.mjs — do not edit. -->
<resources>
${Object.entries(color)
  .map(([name, pair]) => `    <color name="${name.replace(/[A-Z]/g, (c) => '_' + c.toLowerCase())}">${pair[variant]}</color>`)
  .join('\n')}
</resources>
`

const outputs = [
  ['apps/ios/ShabadOS/DesignTokens.swift', swift],
  ['apps/android/app/src/main/java/com/shabados/android/DesignTokens.kt', kotlin],
  ['apps/android/app/src/main/res/values/design_tokens.xml', androidXml('light')],
  ['apps/android/app/src/main/res/values-night/design_tokens.xml', androidXml('dark')],
]

for (const [path, contents] of outputs) {
  const full = join(root, path)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, contents)
  console.log(`wrote ${path}`)
}
