[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਬ੍ਰਹਮਾ ਬਿਸਨੁ ਮਹੇਸੁ ਵੀਚਾਰੀ ॥"
page = 1049
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "I have thought about Brahma, Vishnu and Shiva."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਬ੍ਰਹਮਾ, ਵਿਸ਼ਨੂੰ ਅਤੇ ਸ਼ਿਵਜੀ ਬਾਰੇ ਸੋਚਿਆ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I have considered Brahma, Vishnu and Shiva."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਬ੍ਰਹਮਾਂ, ਬਿਸਨ, ਸਿਵ ਹੋਰ ਭੀ ਜੋ ਬਿਚਾਰਵਾਂਨ ਹੈਂ, ਸੋ ਏਹੀ ਕਹਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਵਿਚਾਰ ਕੇ ਵੇਖ ਲਵੋ-ਬ੍ਰਹਮਾ ਹੋਵੇ, ਵਿਸ਼ਨੂ ਹੋਵੇ, ਸ਼ਿਵ ਹੋਵੇ-"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਹੇਸੁ = ਸ਼ਿਵ। ਵੀਚਾਰੀ = ਵੀਚਾਰਿ, ਵਿਚਾਰ ਕੇ ਵੇਖ ਲੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "He puesto mis pensamientos en Brahma, Vishnu y Shiva,"