[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੁਨੁ ਰਾਜਾ ਪ੍ਰਾਨਨ ਤੇ ਪ︀ਯਾਰੇ ॥"
page = 1117

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਰਾਣਾਂ ਤੋਂ ਪਿਆਰੇ ਰਾਜੇ! ਸੁਣੋ।"