[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਚਾਚਰੀ ਛੰਦ ॥ ਤ੍ਵ ਪ੍ਰਸਾਦਿ ॥"
page = 6
line = 3

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "CHACHARI STANZA BY THY GRACE"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਚਾਚਰੀ ਛੰਦ: ਤੇਰੀ ਕ੍ਰਿਪਾ ਨਾਲ:"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਚਾਚਰੀ ਛੰਦ ॥ ਤ੍ਵਪ੍ਰਸਾਦਿ ॥"