[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਧਾਮ ਚਲੋ ਹਮਰੇ ਪ੍ਰਭੂ, ਕਰਿ ਕੈ ਕ੍ਰਿਪਾ ਅਪਾਰ ॥"
page = 841

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "(They begged) ‘Please be benevolent and come to our domains."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਰਾਣੀ ਨੇ ਕਿਹਾ, ਹੇ ਪ੍ਰਭੂ! (ਮੇਰੇ ਉਤੇ) ਅਪਾਰ ਕ੍ਰਿਪਾ ਕਰ ਕੇ ਮੇਰੇ ਘਰ ਚਲੋ।"