[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਪਸੀ; ਤਪਹਿ ਰਾਤਾ ॥੨॥"
page = 71
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The penitent is absorbed in penance."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕਰੜੀ ਘਾਲ ਘਾਲਣ ਵਾਲਾ ਕਰੜੀ ਘਾਲ ਅੰਦਰ ਲੀਨ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "and the ascetic is absorbed in asceticism. ||2||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "(ਤਪਸ੍ਵੀ) ਤਪ ਮੇਂ ਹੀ ਮਸਤ ਰਹਿਤਾ ਹੈ ਔਰ ਆਪ ਕੋ ਮੁਕਤ ਮਾਨਤਾ ਹੈ॥੨॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤਪ ਕਰਨ ਵਾਲੇ ਸਾਧੂ ਤਪ (ਕਰਨ) ਵਿਚ ਹੀ ਮਸਤ ਰਹਿੰਦੇ ਹਨ ॥੨॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤਪਹਿ = ਤਪਿ ਹੀ, ਤਪ ਵਿਚ ਹੀ। ਰਾਤਾ = ਮਸਤ ॥੨॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El asceta está apegado al ascetismo.(2)"