[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਮਸਤੰ ਅਭੰਗੇ ॥੧੫॥"
page = 2
line = 10

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Salutation to Thee O Immortal Lord! 15"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਅਟੁੱਟ! ਤੈਨੂੰ ਨਮਸਕਾਰ ਹੈ ॥੧੫॥"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨਮਸਤੰ, ਅਭੰਗੇ ॥੧੫॥"