[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਫਿਰੈ ਸੈਨ ਭੱਜੀ ॥੩੫॥"
page = 52

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "There are shouts and in this way the army is running about. 35."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਸੈਨਾ (ਇਧਰ ਉਧਰ) ਭਜੀ ਫਿਰਦੀ ਹੈ ॥੩੫॥"