[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਰੂਪ ਰੰਗ ਅਰੁ ਰੇਖ ਭੇਖ; ਕੋਊ ਕਹਿ ਨ ਸਕਤ ਕਿਹ ॥"
page = 1
line = 4

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He who is without colour or form, and without any distinctive norm."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਜਿਸ ਦੇ ਰੂਪ, ਰੰਗ, ਰੇਖ, ਭੇਖ ਬਾਰੇ ਕੋਈ ਕੁਝ ਨਹੀਂ ਕਹਿ ਸਕਦਾ (ਕਿ ਉਹ) ਕਿਹੋ ਜਿਹਾ ਹੈ।"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਰੂਪ ਰੰਗ ਅਰੁ ਰੇਖ ਭੇਖ; ਕੋਊ ਕਹਿ ਨ ਸਕਤਿ ਕਿਹ ॥"