[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਪੇ ਸ੍ਰਿਸਟਿ ਹੁਕਮਿ ਸਭ ਸਾਜੀ ॥"
page = 1059
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "In His will, the Lord Himself created all the world."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੀ ਰਜ਼ਾ ਅੰਦਰ ਸਾਈਂ ਨੇ ਆਪ ਹੀ ਸਾਰੀ ਦੁਨੀਆ ਰਚੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He Himself fashioned the Universe, through the Hukam of His Command."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੁਕਮੀ ਨੇ ਆਪ ਹੀ ਸ੍ਰਿਸ੍ਟ ਸਭ ਬਣਾਈ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰਮਾਤਮਾ ਨੇ ਆਪ ਹੀ ਇਹ ਸਾਰੀ ਸ੍ਰਿਸ਼ਟੀ ਆਪਣੇ ਹੁਕਮ ਨਾਲ ਪੈਦਾ ਕੀਤੀ ਹੋਈ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਆਪੇ = ਆਪ ਹੀ। ਹੁਕਮਿ = ਹੁਕਮ ਨਾਲ। ਸਭ = ਸਾਰੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Por Su Voluntad el Señor ha creado la Creación y por Sí Mismo,"