[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਹਨ ਕਹਾਵਨ ਕਉ; ਕਈ ਕੇਤੈ ॥"
page = 1302
line = 6

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Several and many are there, who talk and speak about God."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਨੇਕਾਂ ਅਤੇ ਅਣਗਿਣਤ ਹੀ ਵਾਹਿਗੁਰੂ ਦੀਆਂ ਸਿਫਤਾਂ ਕਰਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Many speak and talk about God."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਆਪ ਕੋ ਤਤੁ ਬੇਤਾ ਆਪ ਕਹਤੇ ਹੈਂ ਕਈ ਔਰ ਸਿਖੋਂ ਸੇ ਕਹਾਤੇ ਹੈਂ ਕਿ ਹਮਾਰਾ ਗੁਰੂ ਤਤਵੇਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜ਼ਬਾਨੀ ਆਖਣ ਅਖਵਾਣ ਵਾਲੇ ਤਾਂ ਅਨੇਕਾਂ ਹੀ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਈ = ਅਨੇਕਾਂ ਬੰਦੇ। ਕੇਤੈ = ਕਿਤਨੇ ਹੀ ਬੰਦੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ese humilde Sirviente que logra entender"