[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪਉਣੈ ਪਾਣੀ; ਅਗਨੀ ਕਾ ਸਨਬੰਧ ॥"
page = 1257
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "for it is the mere aggregate of air, water and fire."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕਿਉਂ ਜੋ ਇਹ ਨਿਰੀ ਪੁਰੀ ਹਵਾ, ਪਾਣੀ ਅਤੇ ਅੱਗ ਦਾ ਹੀ ਇਕੱਠ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "It is a fusion of air, water and fire."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਿਨ ਪਵਣ, ਪਾਣੀ, ਅਗਨੀ ਆਦੀ ਤਤੋਂ ਕੇ ਸਨਬੰਧ ਕਰ ਸਰੀਰ ਰਚਿਆ ਹੈ ਤਿਨੋਂ ਮੇਂ ਹੀ ਲੀਨ ਹੋ ਜਾਵੇਗਾ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਹ ਤਾਂ ਹਵਾ ਪਾਣੀ ਅੱਗ ਆਦਿਕ ਤੱਤਾਂ ਦਾ ਮੇਲ ਹੈ (ਜਦੋਂ ਤੱਤ ਖਿੰਡ ਜਾਣਗੇ, ਸਰੀਰ ਢਹਿ ਢੇਰੀ ਹੋ ਜਾਏਗਾ)।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਨਬੰਧ = ਮੇਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pues estos sólo se relacionan con el agua, el fuego y el aire,"