[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਾਮ ਪਰਸ ਤੇ ਝੂਠ ਬਨਾਵਾ ॥"
page = 707

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Made falsehood on the left"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਖਬੇ ਪਾਸੇ ਤੋਂ 'ਝੂਠ' ਨੂੰ ਉਤਪੰਨ ਕੀਤਾ।"