[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਗੁ ਰਾਮਕਲੀ ਮਹਲਾ ੯ ਤਿਪਦੇ ॥"
page = 901
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Rag Ramkali. 9th Guru Tipadas."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਰਾਮਕਲੀ। ਨੌਵੀਂ ਪਾਤਿਸ਼ਾਹੀ ਤਿਪਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Raag Raamkalee, Ninth Mehl, Thi-Padhay:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਰਾਮਕਲੀ ਵਿੱਚ ਗੁਰੂ ਤੇਗਬਹਾਦਰ ਜੀ ਦੀ ਤਿਨ-ਬੰਦਾਂ ਵਾਲੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ramkali, Mejl Guru Teg Bajadur, Noveno Canal Divino, Ti-Padas."