[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਇਕ ਬਿਨ, ਦੂਸਰ ਸੋ ਨ ਚਿਨਾਰ ॥"
page = 712

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Do not recognize anyone except ONE"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਇਕ ਪਰਮਾਤਮਾ ਤੋਂ ਬਿਨਾ (ਕਿਸੇ) ਦੂਜੇ ਨੂੰ ਨਾ ਪਛਾਣੋ।"