[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਲਖੇ ਨ ਜਾਹਿ; ਪਾਰਬ੍ਰਹਮ ਕੇ ਰੰਗ ॥"
page = 275
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The plays of the Supreme One cannot be known."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪਰਮ ਪੁਰਖ ਦੇ ਕਉਤਕ ਜਾਣੇ ਨਹੀਂ ਜਾ ਸਕਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The playful sport of the Supreme Lord God cannot be known."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸ ਪਾਰਬ੍ਰਹਮ ਕੇ ਰੰਗ ਲਖੇ ਨਹੀਂ ਜਾਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਅਕਾਲ ਪੁਰਖ ਦੇ ਖੇਲ ਬਿਆਨ ਨਹੀਂ ਕੀਤੇ ਜਾ ਸਕਦੇ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਲਖੇ ਨ ਜਾਹਿ = ਬਿਆਨ ਨਹੀਂ ਕੀਤੇ ਜਾ ਸਕਦੇ। ਰੰਗ = ਤਮਾਸ਼ੇ, ਖੇਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "ha expandido Su Presencia en olas interminables de creación."