[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਮਸਤੰ ਅਥਾਪੇ ॥"
page = 2
line = 8

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Salutation to Thee O Non-established Lord!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਸਥਾਪਨਾ-ਰਹਿਤ! ਤੈਨੂੰ ਨਮਸਕਾਰ ਹੈ;"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨਮਸਤੰ, ਅਥਾਪੇ ॥"