[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੰਗੀਤ ਛਪੈ ਛੰਦ ॥"
page = 240

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "SANGEET CHHAPAI STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸੰਗੀਤ ਛਪੈ ਛੰਦ"