[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੇਈ ਉਬਰੇ. ਜਗੈ ਵਿਚਿ; ਜੋ ਸਚੈ ਰਖੇ ॥"
page = 318
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "They alone are delivered in the world whom the True Lord preserves."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕੇਵਲ ਓਹੀ ਇਸ ਜਹਾਨ ਵਿੱਚ ਸੁਰਖਰੂ ਹੁੰਦੇ ਹਨ, ਜਿਨ੍ਹਾਂ ਦੀ ਸੱਚਾ ਸੁਆਮੀ ਰਖਿਆ ਕਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "They alone are delivered from the world, who are preserved and protected by the True Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਸਚੇ ਨੇ ਰਖੇ ਹੈਂ, ਸੋ ਜਗਤ ਮੇਂ ਬਚੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਕਾਮਾਦਿਕ ਵਿਕਾਰਾਂ ਤੋਂ) ਜਗਤ ਵਿਚ ਉਹੀ ਮਨੁੱਖ ਬਚੇ ਹਨ ਜਿਨ੍ਹਾਂ ਨੂੰ ਸੱਚੇ ਪ੍ਰਭੂ ਨੇ ਰੱਖਿਆ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Solamente aquéllos a quienes el Guru salva son exaltados en el mundo."