[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਿਹ ਪ੍ਰਸਾਦਿ; ਗ੍ਰਿਹ ਸੰਗਿ ਸੁਖ ਬਸਨਾ ॥"
page = 269
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By whose Kindness, thou abidest in comfort with thy family,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਦੀ ਦਇਆ ਦੁਆਰਾ ਤੂੰ ਆਪਣੇ ਟੱਬਰ ਨਾਲ ਆਰਾਮ ਅੰਦਰ ਰਹਿੰਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "By His Grace, you abide with your family in peace;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਕੀ ਕ੍ਰਿਪਾ ਕਰ ਕੇ ਤੂੰ ਗ੍ਰਿਹ ਵਿਖੇ ਸੁਖ ਸਾਥ ਵਸਨਾ ਕਰਤਾ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ (ਪ੍ਰਭੂ) ਦੀ ਕ੍ਰਿਪਾ ਨਾਲ ਤੂੰ ਘਰ ਮੌਜਾਂ ਨਾਲ ਵੱਸ ਰਿਹਾ ਹੈਂ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੰਗਿ ਸੁਖ = ਸੁਖ ਨਾਲ, ਮੌਜ ਨਾਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Por su gracia habitas con tu familia en paz;"