[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਨ੍ਹਾਣ ਦੀ ਸੰਗਤ ਤੇਰੇ ਲਈ ਇਕ ਰਸਾਇਨ ਇਲਾਜ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਸੁਹਬਤਿ ਸ਼ਾਣ ਕੀਮੀਆ ਬਾਸ਼ਦ ਤੁਰਾ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Everyone's hand is trying to grab the corner of his beneficent robe,"