[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਅਗਮ ਅਗੋਚਰ; ਸਦਾ ਬੇਅੰਤਾ ॥"
page = 184
line = 6

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Lord is ever Inaccessible Incomprehensible and Illimitable Meditate on Him."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪ੍ਰਭੂ ਸਦੀਵ ਹੀ ਪਹੁੰਚ ਤੋਂ ਪਰੇ ਸਾਡੀ ਸੋਚ ਸਮਝ ਤੋਂ ਉਚੇਰਾ ਅਤੇ ਹੱਦਬੰਨਾ-ਰਹਿਤ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He is Inaccessible, Incomprehensible, Eternal and Infinite."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪੁਨਾ ਮਨ ਕੀ ਬਾਣੀ ਕਾ ਅਵਿਸੇ ਹੈ ਨਿਤ ਰੂਪ ਹੈ ਬੇਅੰਤ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੋ ਅਪਹੁੰਚ ਹੈ, ਜਿਸ ਤਕ ਮਨੁੱਖ ਦੇ ਗਿਆਨ-ਇੰਦ੍ਰਿਆਂ ਦੀ ਪਹੁੰਚ ਨਹੀਂ ਹੋ ਸਕਦੀ, ਜਿਸ ਦੇ ਗੁਣਾਂ ਦਾ ਕਦੇ ਅੰਤ ਨਹੀਂ ਪੈ ਸਕਦਾ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਅਗਮ = ਅਪਹੁੰਚ। ਅਗੋਚਰ = {ਅ-ਗੋ-ਚਰ} ਇੰਦ੍ਰਿਆਂ ਦੀ ਪਹੁੰਚ ਤੋਂ ਪਰੇ। ਮੰਤਾ = ਉਪਦੇਸ਼।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Él es Insondable, más Allá del más allá, Infinito."