[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਭ ਗੋਪਨ ਬਾਚ ਆਪਸਿ ਮੈ ॥"
page = 307

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of all the gopas amongst themselves:"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸਾਰੇ ਗਵਾਲ ਬਾਲਕਾਂ ਨੇ ਆਪਸ ਵਿਚ ਕਿਹਾ:"