[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੁਰ ਪੁਰ ਪੋਯੰ ॥੧੭॥"
page = 197

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "They are ornamented with steel armours and are moving towards heaven.17."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਸੁਅਰਗ ਵਿੱਚ ਪਹੁੰਚਦੇ ਜਾਂਦੇ ਸਨ ॥੧੭॥"