[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਸਾਧਸੰਗਤਿ ਸਚੁ ਦੇਸੁ; ਘਰੁ ਪਰਵਾਣਿਆ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Holy congregation is the genuine basis and authentic abode of truth."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਸਾਧ ਸੰਗਤ ਸਚਾ ਉਪਦੇਸ਼ ਹੈ, (ਓਹੀ) ਘਰ ਪ੍ਰਮਾਣੀਕ ਹੈ;"