[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਹਿ ਕਬੀਰ; ਫਿਰਿ. ਜਨਮਿ ਨ ਆਵੈ ॥੩॥੮॥੩੦॥"
page = 483
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Says Kabir, she is not born, again."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕਬੀਰ ਜੀ ਆਖਦੇ ਹਨ, ਉਹ ਮੁੜ ਕੇ ਜਨਮ ਨਹੀਂ ਧਾਰਦੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Says Kabeer, she shall not have to be reincarnated again. ||3||8||30||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸ੍ਰੀ ਕਬੀਰ ਜੀ ਕਹਤੇ ਹੈਂ: ਸੋ ਫੇਰ ਜਨਮ ਮਰਨ ਮੇਂ ਨਹੀਂ ਆਉਤੀ ਹੈ॥੩॥੮॥੩੦॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਕਬੀਰ ਆਖਦਾ ਹੈ-ਉਹ (ਜੀਵ-) ਇਸਤ੍ਰੀ ਫਿਰ ਜਨਮ (ਮਰਨ) ਵਿਚ ਨਹੀਂ ਆਉਂਦੀ ॥੩॥੮॥੩੦॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਹਿ = ਕਹੇ, ਆਖਦਾ ਹੈ ॥੩॥੮॥੩੦॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "ella no será llevada al vientre otra vez. (3‑8‑30)"