[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਭਨਤਿ ਨਾਨਕੁ; ਸੁਣਹੁ ਜਨ ਭਾਈ ॥"
page = 852
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Says Nanak, hearken O men, by brother."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਜੀ ਆਖਦੇ ਹਨ, ਸੁਣੋ ਹੇ ਲੋਕੋ! ਮੇਰੇ ਭਰਾਵ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Prays Nanak, listen, O Siblings of Destiny!"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਭਾਈ ਜਨੋਂ ਸ੍ਰਵਨ ਕਰੋ! ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਨਾਨਕ ਆਖਦਾ ਹੈ-ਹੇ ਭਾਈ ਜਨੋ! ਸੁਣੋ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਭਨਤਿ = ਆਖਦਾ ਹੈ। ਜਨ ਭਾਈ = ਹੇ ਜਨੋ! ਹੇ ਭਾਈ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Reza Nanak, escuchen, oh hermanos del Destino,"