[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਤਿਹ ਤੇ ਕਹੀ ਥੋਰੀਐ ਬੀਨ ਕਥਾ ॥"
page = 200

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਇਸ ਕਰਕੇ ਥੋੜੀ ਚੋਣਵੀ ਕਥਾ ਕਹੀ ਹੈ,"