[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਗੁਫਸ ਤੁਯੰ ॥"
page = 134

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Art in caves."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਹੀ ਗੁਫਾ ਹੈਂ,"