[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਸਨਾ ਬਖਾਨੈ ਨਾਮੁ ॥"
page = 838
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "My tongue utter Thy Name, O Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰੀ ਜੀਭ੍ਹਾ ਤੇਰੇ ਨਾਮ ਦਾ ਉਚਾਰਨ ਕਰਦੀ ਹੈ, ਹੇ ਸਾਈਂ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "My tongue chants the Naam, the Name of the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਤੇ ਹਮਾਰੀ ਰਸਨਾ ਤੇਰੇ ਨਾਮ ਕੋ ਸਦਾ ਉਚਾਰਨ ਕਰੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਆਪਣੀ) ਜੀਭ ਨਾਲ (ਪਰਮਾਤਮਾ ਦਾ) ਨਾਮ ਉਚਾਰਦਾ ਰਹਿੰਦਾ ਹੈ"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਬਖਾਨੈ = ਉਚਾਰਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Mi lengua recita el Naam, el Nombre del Señor, oh Dios"