[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਭ ਮਹਿ; ਪੂਰਿ ਰਹੇ ਪਾਰਬ੍ਰਹਮ ॥"
page = 299
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Supreme One is fully contained amongst all."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪਰਮ ਪੁਰਖ ਸਾਰਿਆਂ ਅੰਦਰ ਪੂਰੀ ਤਰ੍ਹਾਂ ਵਿਆਪਕ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Supreme Lord God is pervading amongst all."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਪਾਰਬ੍ਰਹਮ ਪ੍ਰਭੂ ਸਰਬ ਕੇ ਬੀਚ ਪੂਰਨ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇਹੜਾ ਪ੍ਰਭੂ ਸਾਰੇ ਜਗਤ ਵਿਚ ਹਰ ਥਾਂ ਵਿਆਪਕ ਹੈ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Señor prevalece a través de todos los seres,"