[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਭਗਤ ਸਚੇ ਤੇਰੈ ਦਰਵਾਰੇ ॥"
page = 1056
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The True saints remain standing at Thy door."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੱਚੇ ਸਾਧੂ ਤੈਂਡੇ ਬੂਹੇ ਉੱਤੇ ਖੜੇ ਰਹਿੰਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Your true devotees stand at the Door of Your Court."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੋ ਹੇ ਸਚੇ! ਤੇਰੇ ਦਰਬਾਰ ਮੇਂ ਭਗਤ ਸਚੇ ਹੋਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਰਭੂ! ਤੇਰੇ ਦਰਬਾਰ ਵਿਚ ਤੇਰੇ ਭਗਤ ਸੁਰਖ਼ਰੂ ਰਹਿੰਦੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਚੇ = ਸੁਰਖ਼ਰੂ। ਤੇਰੈ ਦਰਵਾਰੇ = ਤੇਰੇ ਦਰਬਾਰ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Al pasar por Tu Puerta, Tus Devotos se ven Verdaderos,"