[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਉਗਾਧ ਛੰਦ ॥"
page = 221

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "UGAADH STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਗਾਧ ਛੰਦ"