[[content]]
assets = ["AKKB"]
type = "primary"
data = "ਜਿਹਵਾ ਏਕ ਪਾਰ ਨਹਿ ਲਹੀ ॥"

[[content]]
assets = ["SOTK"]
type = "translation"
language = "en"
data = "none which may reach its furthest limit. 525 "