[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਦਾ ਅਲਗੁ; ਰਹੈ ਨਿਰਬਾਣੁ ॥"
page = 1261
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He ever remains aloof and detached."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਹਮੇਸ਼ਾਂ ਨਿਆਰਾ ਅਤੇ ਉਪਰਾਮ ਰਹਿੰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He remains forever unattached in the state of Nirvaanaa."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸਦਾ ਸਰਬ ਸੇ ਅਲਗ ਹੋਇ ਕਰ ਨਿਰਬਾਣ ਰੂਪ ਹੋ ਰਹੇ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਹ ਸਦਾ ਨਿਰਲੇਪ ਰਹਿੰਦਾ ਹੈ, ਮਾਇਆ ਦੇ ਮੋਹ ਤੋਂ ਬਚਿਆ ਰਹਿੰਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਅਲਗੁ = ਵੱਖਰਾ। ਨਿਰਬਾਨੁ = ਵਾਸਨਾ-ਰਹਿਤ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "permaneciendo desapegado en el Estado de Nirvana."