[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਉਮੈ ਆਵੈ ਜਾਈ ॥"
page = 1003
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "in self conceit the man comes and goes."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਵੈ ਹੰਗਤਾ ਅੰਦਰ ਆਦਮੀ ਆਉਂਦਾ ਤੇ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "In egotism, they come and go."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੰਤਾ ਮਮਤਾ ਮੇਂ ਹੀ ਜਨਮ ਮਰਨ ਹੋਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹਉਮੈ ਦੇ ਕਾਰਨ ਜੀਵ ਭਟਕਦਾ ਫਿਰਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਆਵੈ ਜਾਈ = ਆਉਂਦਾ ਹੈ ਜਾਂਦਾ ਹੈ, ਭਟਕਦਾ ਫਿਰਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y en el egoísmo va y viene,"