[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਰੂਪੰ ਕਰਾਲਾ ॥੫੨੩॥"
page = 603

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "His dreadful form was radiating brightness like fire.523."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਜਾਂ) ਭਿਆਨਕ (ਪਰ) ਸੁੰਦਰ ਰੂਪ ਵਾਲਾ ਹੈ ॥੫੨੩॥"