[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਮਿ ਰਤੋ; ਚਾਹਉ ਤੁਝ ਓਰੁ ॥"
page = 1187
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Imbued with Thy Name, O Lord, I ever desire to be Thy wards."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਨਾਮ ਨਾਲ ਰੰਗਿਆ ਹੋਇਆ, ਹੇ ਸੁਆਮੀ! ਮੈਂ ਸਦਾ ਹੀ ਤੇਰੇ ਪਾਸ ਹੋਣਾ ਚਾਹੁੰਦਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Imbued with Your Name, I long to be Yours."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਹਰੀ! ਤੇਰੇ ਨਾਮ ਮੇਂ ਰਤਾ ਹੂਆ ਤੇਰੀ ਤਰਫ ਹੀ ਦੇਖ ਰਹਾ ਹਾਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਨਾਮ-ਰੰਗ ਵਿਚ ਰੰਗਿਆ ਰਹਾਂ ਤੇ ਤੇਰਾ ਹੀ ਪੱਲਾ ਫੜੀ ਰੱਖਾਂ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨਾਮਿ = ਨਾਮ ਵਿਚ। ਓਰੁ = ਪਾਸਾ, ਆਸਰਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Estoy imbuido en Tu Nombre y mi atención se enfoca sólo en Ti,"