[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਮ ਬਿਨਾ; ਕਿਉ ਜੀਵਾ ਮਾਇ ॥"
page = 226
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Without the Name, how can I live O my mother?"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਨਾਮ ਦੇ ਬਾਝੋਂ ਮੈਂ ਕਿਸ ਤਰ੍ਹਾਂ ਜਿਉ ਸਕਦਾ ਹਾਂ ਹੈ ਮਾਤਾ?"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Without the Naam, how can I live, O mother?"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ (ਮਾਇ) ਮਾਯਾ ਪਤੀ! ਨਾਮ ਸੇ ਬਿਨਾ ਕੈਸੇ ਜੀਵੋਂ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਮੇਰੀ ਮਾਂ! ਪਰਮਾਤਮਾ ਦੇ ਨਾਮ ਤੋਂ ਬਿਨਾ ਮੈਂ (ਆਤਮਕ ਜੀਵਨ) ਜਿਊ ਨਹੀਂ ਸਕਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜੀਵਾ = ਜੀਵਾਂ, ਮੈਂ ਜੀਉ ਸਕਾਂ। ਮਾਇ = ਹੇ ਮਾਂ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "¿Cómo podría vivir sin el Nombre, oh mi madre?"