[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਸਾ ਮਹਲਾ ੩ ਛੰਤ ਘਰੁ ੩ ॥"
page = 440
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Asa 3rd Guru. Rhythm."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਸਾ ਤੀਜੀ ਪਾਤਸ਼ਾਹੀ। ਛੰਦ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Aasaa, Third Mehl, Chhant, Third House:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਆਸਾ, ਘਰ ੩ ਵਿੱਚ ਗੁਰੂ ਅਮਰਦਾਸ ਜੀ ਦੀ ਬਾਣੀ 'ਛੰਤ'।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Mejl Guru Amar Das, Tercer Canal Divino, Chhant."