[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੇਰੇ ਲਾਲਨ ਕੀ ਸੋਭਾ ॥"
page = 1322
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Wondrous is the magnificence of my Beloved."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਦਭੁਤ ਹੈ ਪ੍ਰਭਤਾ ਮੇਰੇ ਪ੍ਰੀਤਮ ਦੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O, the Wondrous Glory of my Beloved!"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ (ਲਾਲਨ) ਪਿਆਰੇ ਕੀ ਜੋ ਸੋਭਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ ਸੋਹਣੇ ਪ੍ਰਭੂ ਦੀ ਸੋਭਾ-ਵਡਿਆਈ-"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਲਾਲਨ ਕੀ = ਸੋਹਣੇ ਲਾਲ ਦੀ, ਪਿਆਰੇ ਦੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "¡Oh, qué maravillosa es la Gloria de mi Bienamado!"