[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੋਲਹ ਅਸਟਪਦੀਆ ਗੁਆਰੇਰੀ ਗਉੜੀ ਕੀਆ ॥"
page = 228
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Sixteen Ashtpadian of Gauri Guareri."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੋਲਾਂ ਅਸ਼ਟਪਦੀਆਂ ਗੁਆਰੇਰੀ ਗਊੜੀ ਦੀਆਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Sixteen Ashtpadheeyaa Of Gwaarayree Gauree||"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dieciséis Ashtapadis de Gauri Guareri"