[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਓਹੁ ਅਬਿਨਾਸੀ; ਬਿਨਸਤ ਨਾਹੀ ॥"
page = 736
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He, the Lord is imperishable and perishes not."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਸਾਹਿਬ ਨਾਸ-ਰਹਿਤ ਹੈ ਅਤੇ ਨਾਸ ਨਹੀਂ ਹੁੰਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He is imperishable; He will never pass away."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਯਦ੍ਯਪਿ ਪਹਿਲੇ ਵੀ ਓਹ ਅਬਿਨਾਸੀ ਹੈ ਔਰ ਅਬ ਭੀ ਨਾਸਵਾਨ ਨਹੀਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਉਹ ਪਰਮਾਤਮਾ ਨਾਸ-ਰਹਿਤ ਹੈ, ਉਸ ਕਦੇ ਨਾਸ ਨਹੀਂ ਹੁੰਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਅਬਿਨਾਸੀ = ਨਾਸ-ਰਹਿਤ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Señor es Eterno; Él continúa;"