[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਰਾਜ ਪੁਤ੍ਰ ਤਾ ਕੇ ਕੋ ਭਯੋ ॥੨॥"
page = 975

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "After sometimes the Raja died and his sons took over the kingdom.(2)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਉਸ ਦਾ ਪੁੱਤਰ ਰਾਜਾ ਹੋਇਆ ॥੨॥"