[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਕੇ ਨਾਮ ਕੇ; ਜਨ ਕਾਂਖੀ ॥"
page = 1227
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "God's slaves are desirous of the God's Name."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰੱਬ ਦੇ ਗੋਲੇ ਰਬ ਦੇ ਨਾਮ ਦੇ ਚਾਹਵਾਨ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Lord's humble servants yearn for the Lord's Name."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਹਰੀ! ਜੋ ਤੇਰੇ ਜਨ ਹੈਂ, ਸੋ ਤੇਰੇ ਨਾਮ ਕੇ (ਕਾਂਖੀ) ਚਾਹਵਾਨ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰਮਾਤਮਾ ਦੇ ਸੇਵਕ ਪਰਮਾਤਮਾ ਦੇ ਨਾਮ ਦੇ ਚਾਹਵਾਨ ਰਹਿੰਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜਨ = ਸੰਤ ਜਨ। ਕਾਂਖੀ = ਚਾਹਵਾਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Los Sirvientes de Dios añoran sólo el Nombre del Señor, sí, con pensamiento,"