[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬ︀ਯੋਮ ਬਾਨੀ ਬਾਚ ॥"
page = 643

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of the heavenly voice :"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਆਕਾਸ਼ ਬਾਣੀ ਨੇ ਕਿਹਾ:"