[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਹਸਾ ਮੂਲਿ ਨ ਚੁਕੈ ਵਿਕਾਰਾ ॥"
page = 1062
line = 6

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "His doubt and sin are dispelled not ever."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਸ ਦਾ ਸੰਦੇਹ ਅਤੇ ਪਾਪ ਕਦੇ ਭੀ ਦੂਰ ਨਹੀਂ ਹੁੰਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "His skepticism and corruption are never dispelled."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "(ਸਹਸਾ) ਫਿਕਰ ਔ ਬਿਕਾਰ ਕਦੇ ਨਹੀਂ ਚੂਕਤੇ ਅਰਥਾਤ ਦੂਰ ਨਹੀਂ ਹੋਤੇ ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਦਾ ਇਹ ਵਿਅਰਥ ਸਹਮ ਕਦੇ ਭੀ ਨਹੀਂ ਮੁੱਕਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਹਸਾ = (ਮਾਇਆ ਬਾਰੇ) ਸਹਮ। ਮੂਲਿ = ਬਿਲਕੁਲ। ਚੁਕੈ = ਮੁੱਕਦਾ। ਵਿਕਾਰਾ = ਬੇ-ਕਾਰ, ਵਿਅਰਥ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y su duda nunca termina por disiparse, ni su maldad por irse."