[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੀਅ ਜੰਤ; ਸਭਿ ਤੇਰਾ ਖੇਲੁ ॥"
page = 11
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "All the sentient-beings are Thine play things"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਮੂਹ ਪ੍ਰਾਣਧਾਰੀ ਤੇਰੇ ਖਿਡਾਉਣੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "All living beings are Your playthings."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਵਡੇ ਛੋਟੇ ਜਿਤਨੇ ਜੀਵ ਹੈਂ, ਸਭ ਤੇਰਾ ਹੀ ਖੇਲੁ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਹ ਸਾਰੇ ਜੀਆ ਜੰਤ ਤੇਰੀ (ਰਚੀ ਹੋਈ) ਖੇਡ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਭਿ = ਸਾਰੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Todos los seres son Tus Juguetes."