[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਭੁ ਅਪੁਨਾ; ਹੋਇਆ ਕਿਰਪਾਲ ॥੧॥"
page = 389
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "My Lord have become merciful."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰਾ ਸੁਆਮੀ ਮਿਹਰਬਾਨ ਹੋ ਗਿਆ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "God has become merciful to me. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕ੍ਯੋਂਕਿ ਪ੍ਰਭੂ ਅਪਨਾ ਮੁਝ ਪਰ ਕ੍ਰਿਪਾਲ ਹੂਆ ਹੈ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਉੱਤੇ ਪਿਆਰਾ ਪ੍ਰਭੂ ਦਇਆਵਾਨ ਹੋ ਜਾਂਦਾ ਹੈ  ॥੧॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਿਰਪਾਲ = ਦਇਆਵਾਨ ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pues mi Maestro me ha mostrado su Compasión. (1)"