[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰਮੁਖਿ ਹੋਵੈ. ਸੁ ਕਰੇ ਵੀਚਾਰੁ ॥"
page = 1422
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Whosoever turns Guru-ward. he reflects on the Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਕੋਈ ਗੁਰੂ-ਅਨੁਸਾਰੀ ਹੋ ਵੰਜਦਾ ਹੈ, ਉਹ ਸਾਈਂ ਦਾ ਸਿਮਰਨ ਕਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Whoever becomes Gurmukh contemplates the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਪੁਰਸ਼ ਗੁਰਮੁਖ ਹੋਵੇ ਸੋ ਸ੍ਵੈ ਸਰੂਪ ਕਾ ਵੀਚਾਰ ਕਰਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਹੜਾ ਮਨੁੱਖ ਗੁਰੂ ਦੀ ਸਰਨ ਪਿਆ ਰਹਿੰਦਾ ਹੈ, ਉਹ (ਪਰਮਾਤਮਾ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਨੂੰ) ਆਪਣੇ ਮਨ ਵਿਚ ਵਸਾਈ ਰੱਖਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੁ = ਉਹ ਮਨੁੱਖ। ਕਰੇ ਵੀਚਾਰੁ = (ਪਰਮਾਤਮਾ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਨੂੰ) ਮਨ ਵਿਚ ਵਸਾਈ ਰੱਖਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Quien se vuelve Gurmukj medita en el Señor,"