[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਿਰਖ ਦੀਨ ਪਰ ਹੋਤ ਦਿਆਰਾ ॥"
page = 156

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Seeing Thy mercifulness towards the lowly"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਤੈਨੂੰ) ਦੀਨਾਂ ਉਤੇ ਦਿਆਲ ਹੁੰਦਾ ਵੇਖਕੇ"