[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਹੁ ਪੰਡਿਤ; ਸੂਚਾ ਕਵਨੁ ਠਾਉ ॥"
page = 1195
line = 6

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O Pandit, tell me which place is contaminated not,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਪੰਡਿਤ! ਤੂੰ ਮੈਨੂੰ ਦੱਸ, ਕਿਹੜੀ ਥਾਂ ਪਲੀਤ ਨਹੀਂ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Tell me, O Pandit, O religious scholar, which place is uncontaminated?"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਪੰਡਤ ਜੀ! ਮੇਰੇ ਕੋ ਬਤਾਵੋ ਸੂਚਾ ਕਵਨ ਅਸਥਾਨੁ ਹੈ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪੰਡਿਤ! ਦੱਸ, ਉਹ ਕਿਹੜਾ ਥਾਂ ਹੈ ਜੋ ਸੁੱਚਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪੰਡਿਤ = ਹੇ ਪੰਡਿਤ! ਕਵਨੁ ਠਾਉ = ਕਿਹੜਾ ਥਾਂ?"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Pandit, dime de algún lugar que no esté contaminado"