[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਬਾਝੁ ਗੁਰੂ; ਹੈ ਅੰਧ ਅੰਧਾਰਾ ॥"
page = 125
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Without the Guru there is inky darkness."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੁਰਾਂ ਦੇ ਬਿਨਾਂ ਅਨ੍ਹੇਰ ਘੁਪ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Without the Guru, there is only pitch-black darkness."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਗੁਰੋਂ ਸੇ ਬਿਨਾ ਜੋ ਨਿਗੁਰੇ ਹੈਂ ਤਿੰਨ ਅੰਧੋਂ ਕੋ ਸਦਾ ਹੀ ਅਗਿਆਨ ਰੂਪੀ ਅੰਧੇਰਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਦੀ ਸਰਨ ਤੋਂ ਬਿਨਾ (ਮਾਇਆ ਦੇ ਮੋਹ ਦਾ) ਘੁੱਪ ਹਨੇਰਾ ਛਾਇਆ ਰਹਿੰਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਅੰਧ ਅੰਧਾਰਾ = ਮਾਇਆ ਦੇ ਮੋਹ ਦਾ ਘੁੱਪ ਹਨੇਰਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sin el Guru, hay una oscuridad profunda;"