[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰੀਤਿ ਕਰਹੁ ਸਦ ਏਕ ਸਿਉ; ਇਆ ਸਾਚਾ ਅਸਨੇਹੁ ॥"
page = 257
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Ever embrace affection for the One Lord. This is the true love."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹਮੇਸ਼ਾਂ ਇਕ ਸੁਆਮੀ ਨਾਲ ਪਿਰਹੜੀ ਪਾ! ਏਹੀ ਸੱਚਾ ਪ੍ਰੇਮ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Embrace love for the One Lord forever - this is true love!"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸਦੀਵ ਏਕ ਪਰਮੇਸ੍ਵਰ ਕੇ ਸਾਥ ਪ੍ਰੀਤੀ ਕਰੋ ਯਹੀ ਸਚਾ (ਅਸਨੇਹੁ) ਪ੍ਰੇਮ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸਦਾ ਸਿਰਫ਼ ਪਰਮਾਤਮਾ ਨਾਲ (ਦਿਲੀ) ਪ੍ਰੀਤਿ ਬਣਾ। ਇਹੀ ਪਿਆਰ ਸਦਾ ਕਾਇਮ ਰਹਿਣ ਵਾਲਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਅਸਨੇਹੁ = ਨੇਹੁ, ਪਿਆਰ {स्नेह ਦੇ ਦੋ ਪੰਜਾਬੀ ਰੂਪ: ਨੇਹੁ, ਅਸਨੇਹੁ। ਵੇਖੋ 'ਗੁਰਬਾਣੀ ਵਿਆਕਰਣ'}।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pues sólo eso es el Amor Verdadero."