[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਮੁ ਹਮਾਰੈ; ਤ੍ਰਿਪਤਿ ਸੁਭੋਗ ॥"
page = 1145
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "God's Name for me is the sublime diet, which satiates me."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰੱਬ ਦਾ ਨਾਮ ਮੇਰੇ ਲਈ ਸਰੇਸ਼ਟ ਭੋਜਨ ਹੈ, ਜਿਸ ਨਾਲ ਮੈਂ ਰੱਜ ਜਾਂਦਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Naam is the sublime food which satisfies me."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਨਾਮ ਹੀ ਹਮਾਰੇ ਮਨ ਮੇਂ ਸ੍ਰੇਸ਼ਟ ਭੋਗੋਂ ਕੀ ਤ੍ਰਿਪਤੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਦੁਨੀਆ ਦੇ ਸੁਆਦਲੇ ਪਦਾਰਥਾਂ ਨੂੰ ਖਾ ਖਾ ਕੇ ਰੱਜਣਾ-(ਇਹ ਸਾਰਾ ਸੁਆਦ) ਮੇਰੇ ਵਾਸਤੇ ਹਰਿ-ਨਾਮ ਦਾ ਸਿਮਰਨ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤ੍ਰਿਪਤਿ = ਰੱਜ। ਸੁਭੋਗ = ਸੁਆਦਲੇ ਭੋਗਾਂ ਦੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "el sagrado día, pues es lo único que sacia mi ser."