[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਪੂਰਨ ਸਤਿਗੁਰੂ ਰੱਬ ਦਾ ਹੀ ਰੂਪ ਹੁੰਦਾ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਸੂਰਤਿ ਹੱਕ ਮੁਰਸ਼ਦਿ ਕਾਮਿਲ ਬਵਦ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "A perfect Guru is, in fact, the image of the Omnipresent,"