[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਟ ਅਸਟਪਦੀਆ ਮਹਲਾ ੪ ॥"
page = 980
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Nat Ashatpadies. 4th Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਨਟ ਅਸਟਪਦੀਆਂ। ਚੌਥੀ ਪਾਤਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Nat Ashtpadheeyaa, Fourth Mehl:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਨਟ-ਨਾਰਾਇਨ ਵਿੱਚ ਗੁਰੂ ਰਾਮਦਾਸ ਜੀ ਦੀ ਅੱਠ-ਬੰਦਾਂ ਵਾਲੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Nat, Ashtapadis, Mejl Guru Ram Das, Cuarto Canal Divino."