[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਅਲੇਖਸ ॥"
page = 132

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Lord is Accountless."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਲੇਖੇ ਤੋਂ ਬਾਹਰ ਹੈ,"