[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਵਛ ਸਿੰਘ ਬਾਚ ॥"
page = 425

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of Svachh Singh:"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸਵਛ ਸਿੰਘ ਨੇ ਕਿਹਾ:"