[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬ ਸਰਦਾਰੀਏ ਕਰਦ ਪੇਸ਼ੀਨਹ ਫ਼ੌਜ ॥"
page = 1421

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Leading the frontal detachments,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ (ਲੜਕੀ) ਨੂੰ ਫ਼ੌਜ ਦਾ ਸਰਦਾਰ ਬਣਾ ਦਿੱਤਾ"