[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਸਰਬੱਤ੍ਰ ਭੇਸੈ ॥"
page = 6
line = 19

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Thou art in all the garbs!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਭੇਸਾਂ ਵਿਚ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਕਿ, ਸਰਬਤ੍ਰ ਭੇਸੈ ॥"