[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਮਸਤੰ ਨ੍ਰਿਧੂਤੇ ॥"
page = 2
line = 7

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Salutation to Thee O Motionless Lord!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਨਾ ਹਿਲਾਏ ਜਾ ਸਕਣ ਵਾਲੇ (ਅਚਲ ਸਰੂਪ)! ਤੈਨੂੰ ਨਮਸਕਾਰ ਹੈ;"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨਮਸਤੰ, ਨ੍ਰਿਧੂਤੇ ॥"