[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਕਾਮ ॥"
page = 10
line = 12

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Desireless Lord !"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕਾਮਨਾ-ਰਹਿਤ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਅਕਾਮ ॥"