[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਾਧ ਕੈ ਸੰਗਿ; ਨਰਕ ਪਰਹਰੈ ॥"
page = 272
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By associating with the saints the hell is avoided."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੰਤਾਂ ਦੀ ਸੰਗਤ ਕਰਨ ਦੁਆਰਾ ਦੋਜ਼ਖ਼ ਤੋਂ ਬਚ ਜਾਈਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "In the Company of the Holy, hell is far away."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੰਤੋਂ ਕੇ ਸੰਗ ਸੇ ਨਰਕੋਂ ਕਾ ਦੁਖ ਦੂਰ ਕਰ ਦੇਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਤੇ ਇਸ ਤਰ੍ਹਾਂ) ਨਰਕਾਂ ਤੋਂ ਬਚ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਰਹਰੈ = ਪਰੇ ਹਟਾ ਲੈਂਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y la mente conquista un Estado de permanente Quietud,"