[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਨ ਗਾਇ ਸੁਨਿ ਲਿਖਿ ਦੇਇ ॥"
page = 838
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He who sings, hears and writes the Lord's praise,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਪ੍ਰਭੂ ਦੀ ਕੀਰਤੀ ਗਾਉਂਦਾ, ਸੁਣਦਾ ਅਤੇ ਲਿਖਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "One who sings the Glorious Praises of the Lord, and hears them, and writes them,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਵਾਹਿਗੁਰੂ ਕੇ ਗੁਣੋਂ ਕੋ ਗਾਵੈ ਅਥਵਾ ਸ੍ਰਵਨ ਕਰੇ, ਵਾ ਕਿਸੀ ਕਉ ਲਿਖ ਕਰ ਦੇਵੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਹੜਾ ਮਨੁੱਖ (ਪਰਮਾਤਮਾ ਦੇ) ਗੁਣ ਗਾ ਕੇ, ਸੁਣ ਕੇ, ਲਿਖ ਕੇ (ਇਹ ਦਾਤ ਹੋਰਨਾਂ ਨੂੰ ਭੀ) ਦੇਂਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗਾਇ = ਗਾ ਕੇ। ਸੁਨਿ = ਸੁਣ ਕੇ। ਲਿਖਿ = ਲਿਖ ਕੇ। ਦੇਇ = ਦੇਂਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Aquél que canta, escucha o escribe"