[[content]]
assets = ["DGDG", "DDTK"]
type = "primary"
data = "ਉਦਾਰੇ ॥"
page = 6
line = 4

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Most Genereous Lord!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਦਾਰ-ਚਿਤ ਅਤੇ"

