[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਭੋਲਿਆ; ਹਉਮੈ ਸੁਰਤਿ ਵਿਸਾਰਿ ॥"
page = 1168
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O ignorant man, forget thou thy haughty intellect."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਬੇਸਮਝ ਬੰਦੇ! ਤੂੰ ਆਪਣੀ ਆਕੜ-ਖਾਂ ਅਕਲ ਨੂੰ ਭੁੱਲ ਜਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O ignorant one, forget your egotistical intellect."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਭੋਲੇ ਜੀਵ! ਹੰਤਾ, ਮਮਤਾ ਕੀ ਗ੍ਯਾਤ ਕੋ ਬਿਸਾਰ ਦੇਹੁ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਕਮਲੇ ਮਨ! ਮੈਂ ਮੈਂ ਕਰਨ ਵਾਲੀ ਬ੍ਰਿਤੀ ਭੁਲਾ ਦੇ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਭੋਲਿਆ = ਹੇ ਕਮਲੇ (ਮਨ)! ਸੁਰਤਿ = ਬ੍ਰਿਤੀ। ਵਿਸਾਰਿ = ਭੁਲਾ ਦੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh ser ignorante, abandona tu sentido del yo soy."