[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਬਾਝੁ ਗੁਰੂ, ਡੁਬਾ ਜਗੁ ਸਾਰਾ ॥੨੯॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Without Guru the world is getting drowned."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਥੋਂ ਬਿਨਾਂ ਸਾਰਾ ਜਗਤ ਡੁੱਬ ਰਿਹਾ ਹੈ। “"