[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਉਤਭੁਜ ਸਰੂਪ ਅਬਿਗਤ ਅਭੰਗ ॥"
page = 138

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The Germinating Entity, Unmanifested and Invincible"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਨਾਸ਼ ਤੋਂ ਬਿਨਾ ਹੈ ਗਤਿ ਤੋਂ ਰਹਿਤ"