[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਹ ਸੰਗਿ ਗਾਮਨੀ ॥੧॥"
page = 901
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "go not with mortal."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪ੍ਰਾਣੀ ਦੇ ਨਾਲ ਨਹੀਂ ਜਾਂਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "but these will not go along with you. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪਰੰਤੂ ਇਨ ਪਦਾਰਥੋਂ ਕਾ ਪਰਲੋਕ ਮੇਂ ਸਾਥ ਜਾਨਾ ਨਹੀਂ ਹੋਤਾ ਹੈ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਪਰ ਇਹਨਾਂ ਵਿਚੋਂ ਕੋਈ ਚੀਜ਼ ਇਸ ਦੇ) ਨਾਲ ਨਹੀਂ ਜਾਂਦੀ ॥੧॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੰਗਿ = ਨਾਲ। ਗਾਮਨੀ = ਜਾਂਦਾ ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pero nada te acompañará al final.  (1)"