[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਤਬ ਲੌ ਆਵਤ ਪਟੂਆ ਭਯੋ ॥"
page = 860

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "She loved him intensively and, in due course, had commenced to have sex with him."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਦੋਂ ਤਕ ਪਟੂਆ ਆ ਗਿਆ,"