[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਤੋਟਕ ॥"
page = 523

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "TOTAK STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੋਟਕ:"