[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤੁਝ ਰਾਖਨਹਾਰੋ; ਮੋਹਿ ਬਤਾਇ ॥"
page = 1194
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "and said. \"show me thou, where thy Protector is?\""

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਮੈਨੂੰ ਵਿਖਾਲ! ਤੇਰੀ ਰੱਖਿਆ ਕਰਨ ਵਾਲਾ ਕਿੱਥੇ ਹੈ?"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "\"Show me your protector now!\""

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਕੋ ਜੋ ਰਾਖਨਹਾਰਾ ਹੈ ਅਬ ਮੇਰੇ ਕੋ ਬਤਾਇ ਦੇਹੁ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮੈਨੂੰ ਉਹ ਦੱਸ ਜੋ ਤੈਨੂੰ ਬਚਾਉਣ ਵਾਲਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੋਹਿ = ਮੈਨੂੰ। ਬਤਾਇ = ਦੱਸ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "veamos ahora en donde está tu Protector"