[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਭੁਜੰਗ ਛੰਦ ॥"
page = 942

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Bhujang Chhand"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਭੁਜੰਗ ਛੰਦ:"