[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਜ਼ੁਲਮ ਦੀ ਬੁਨਿਆਦ ਪੁੱਟ ਦਿੱਤੀ ਗਈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਬਿਨਾਇ ਸਿਤਮ ਰਾ ਬਰ-ਅੰਦਾਖ਼ਤਾ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "The foundations of tyrannt were uprooted,"