[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਰ ਨਾਇਕ ਹੈਂ ॥"
page = 9
line = 19

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Lord! Thou art the Master of men!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਮਨੁੱਖਾਂ ਦਾ ਨਾਇਕ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨਰ, ਨਾਇਕ ਹੈਂ ॥"