[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਕਾ ਨਾਮੁ; ਮੰਨਿ ਵਸਾਏ ॥"
page = 362
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "he gathers God's Name within his mind."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਵਾਹਿਗੁਰੂ ਦੇ ਨਾਮ ਨੂੰ ਆਪਣੇ ਚਿੱਤ ਵਿੱਚ ਟਿਕਾ ਲੈਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Name of the Lord abides within his mind."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹਰਿ ਕਾ ਨਾਮ ਮਨ ਮੇਂ ਬਸਾਉਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਕਿਉਂਕਿ) ਉਹ ਪਰਮਾਤਮਾ ਦੇ ਨਾਮ ਨੂੰ (ਸਦਾ ਆਪਣੇ) ਮਨ ਵਿਚ ਵਸਾਈ ਰੱਖਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੰਨਿ = ਮਨਿ, ਮਨ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y atesora el Naam, el Nombre del Señor en su mente."