[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਤਰਫੰਤ ਭਟੰ ਗਰਜੰ ਗਜੰ ॥"
page = 167

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The warriors are writhing and the elephants are roaring in such a way,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸੂਰਮੇ ਤੜਪਦੇ ਸਨ, ਹਾਥੀ ਗਜਦੇ ਸਨ"