[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਿਨਿ ਉਪਾਏ ਜੀਅ; ਤਿਨਿ ਹਰਿ ਰਾਖਿਆ ॥"
page = 594
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Lord who fashioned the creatures, that Lord protects them too."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਪ੍ਰਭੂ ਨੇ ਜੀਵ-ਜੰਤੂ ਪੈਦਾ ਕੀਤੇ ਹਨ, ਉਹੀ ਪ੍ਰਭੂ ਉਨ੍ਹਾਂ ਦੀ ਰੱਖਿਆ ਕਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Lord, who created the creatures, also protects them."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਹਰਿ ਨੇ ਜੀਵ ਉਤਪੰਨ ਕੀਏ ਹੈਂ, ਤਿਸੀ ਹਰਿ ਨੇ ਜੀਵੋਂ ਕੀ ਰਖ੍ਯਾ ਕਰੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਹਰੀ ਨੇ ਜੀਵ ਪੈਦਾ ਕੀਤੇ ਹਨ, ਉਸੇ ਨੇ ਉਹਨਾਂ ਦੀ ਰੱਖਿਆ ਕੀਤੀ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜਿਨਿ = ਜਿਸ ਨੇ। ਤਿਨਿ = ਉਸੇ ਨੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Aquél que crea la vida, también la protege;"