[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੰਗੀਤ ਬਹੜਾ ਛੰਦ ॥"
page = 258

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "SANGEET BAHRA STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸੰਗੀਤ ਬਹੜਾ ਛੰਦ"