[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਉਹੁ ਗੁਰੁ ਗੋਬਿੰਦ ਹੋਇ ਪ੍ਰਗਟਿਓ; ਦਸਵਾਂ ਅਵਤਾਰਾ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Guru Gobind Singh manifested as the tenth incarnation."