[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਰਿ ਕਰਤਾ; ਉਤਰਸਿ ਪਾਰੰ ॥"
page = 972
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Man of action crosses the world-ocean."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਮਲੀ ਜੀਵਨ ਵਾਲਾ ਬੰਦਾ ਸੰਸਾਰ ਸਮੁੰਦਰ ਤਰ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Chanting to the Creator, one crosses over."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕਰਤਾ ਹੋ ਕਰ ਜੋਗੁ ਕਿਰਿਆ ਕਾ ਪਾਰ ਉਤਰਿਆ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤਦੋਂ ਪ੍ਰਭੂ ਦਾ ਸਿਮਰਨ ਕਰ ਕੇ ਉਹ ਪਾਰ ਲੰਘ ਗਿਆ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਰਿ ਕਰਤਾ = 'ਕਰਤਾ ਕਰਤਾ' ਕਰ ਕੇ, 'ਪ੍ਰਭੂ ਪ੍ਰਭੂ' ਆਖ ਕੇ, ਪ੍ਰਭੂ ਦਾ ਸਿਮਰਨ ਕਰ ਕੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y, cantando el Nombre del Señor Creador, va a través."