[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਾਂਏਂ; ਆਨ ਆਨ ਰੁਚੀਐ ॥"
page = 1229
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "why thou love another, another?"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਹੋਰਸ, ਹੋਰਸ ਨੂੰ ਕਿਉਂ ਪਿਆਰ ਕਰਦੀ ਹੈ?"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Others - why are you involved with others?"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਔਰ ਪਦਾਰਥੋਂ ਮੇਂ ਕਾਹੇ ਕੋ ਰੁਚੀ (ਆਨ) ਲਿਆਵਤੀ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਉਸ ਨੂੰ ਭੁਲਾ ਕੇ) ਹੋਰ ਹੋਰ ਪਦਾਰਥਾਂ ਵਿਚ ਪਿਆਰ ਨਹੀਂ ਪਾਣਾ ਚਾਹੀਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਾਂਏਂ = ਕਿਉਂ? ਆਨ ਆਨ = ਹੋਰ ਹੋਰ (ਪਦਾਰਥਾਂ ਵਿਚ)। ਰੁਚੀਐ = ਪ੍ਰੀਤ ਬਣਾਈ ਹੋਈ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "¿por qué vives entonces apegado al otro?"