[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪੂਰੇ ਗੁਰ ਕੀ; ਦੇਖੁ ਵਡਾਈ ॥"
page = 614
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Behold thou the greatness of the perfect Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਪੂਰਨ ਗੁਰੂ ਦੀ ਬਜ਼ੁਰਗੀ ਵੇਖ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Behold the glorious greatness of the Perfect Guru."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪੂਰੇ ਗੁਰੋਂ ਕੀ ਤੂੰ (ਵਡਿਆਈ) ਮਹਿਮਾਂ ਤੋ ਦੇਖ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਪੂਰੇ ਗੁਰੂ ਦੀ ਆਤਮਕ ਉੱਚਤਾ ਬੜੀ ਅਸਚਰਜ ਹੈ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ve, la Gloria del Guru Perfecto"