[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰ ਗੋਰਖ ਕੀ; ਤੈ ਬੂਝ. ਨ ਪਾਈ ॥"
page = 886
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Thou understandest not Gorakh, thy Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਆਪਣੇ ਗੁਰੂ ਗੋਰਖ ਨੂੰ ਨਹੀਂ ਸਮਝਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "You do not understand Gorakh, your guru."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਵਡਾ ਜੋ ਪਰਮੇਸ੍ਵਰ ਹੈ ਪ੍ਰਿਥੀ ਕੀ ਰਛਿਆ ਕੇ ਕਰਨੇ ਵਾਲਾ, ਤਿਸ ਕੀ ਤੈਨੇ ਸਮਝ ਨਹੀਂ ਪਾਈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਜੋਗੀ! (ਇਸ ਤਰ੍ਹਾਂ) ਉਸ ਸਭ ਤੋਂ ਵੱਡੇ ਗੋਰਖ (ਜਗਤ-ਰੱਖਿਅਕ ਪ੍ਰਭੂ) ਦੀ ਤੈਨੂੰ ਸੋਝੀ ਨਹੀਂ ਪਈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੋਰਖ = ਗੋਪਾਲ {ਗੋ = ਧਰਤੀ। ਰਖ = ਰੱਖਿਆ ਕਰਨ ਵਾਲਾ}। ਤੈ = ਤੂੰ, ਤੈਂ। ਬੂਝ = ਸੋਝੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "No conoces a Gorak, el Guru,"