[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਭ ਹੀ ਜਗ ਭਰਮੇ ਭਵਰਾ︁ਯੰ ॥"
page = 156

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "They became kings of the world and got deluded"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਤੁਸੀਂ) ਸਾਰਾ ਜਗਤ ਭਰਮਾਂ ਵਿਚ ਭੁਲਾਇਆ ਹੋਇਆ ਹੈ,"