[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਭ ਕਉ ਸਿਮਰਹਿ; ਸੇ ਪਰਉਪਕਾਰੀ ॥"
page = 263
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "They, who contemplate over the Master are philanthropical."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਮਾਲਕ ਦਾ ਆਰਾਧਨ ਕਰਦੇ ਹਨ, ਉਹ ਉਦਾਰਚਿੱਤ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Those who remember God generously help others."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਪ੍ਰਭੂ ਕੋ ਸਿਮਰਤੇ ਹੈਂ ਸੋਈ ਪਰਉਪਕਾਰੀ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੋ ਮਨੁੱਖ ਪ੍ਰਭੂ ਨੂੰ ਸਿਮਰਦੇ ਹਨ, ਉਹ ਦੂਜਿਆਂ ਨਾਲ ਭਲਾਈ ਕਰਨ ਵਾਲੇ ਬਣ ਜਾਂਦੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਉਪਕਾਰ = ਭਲਾਈ, ਨੇਕੀ। ਉਪਕਾਰੀ = ਭਲਾਈ ਕਰਨ ਵਾਲਾ। ਪਰਉਪਕਾਰੀ = ਦੂਜਿਆਂ ਨਾਲ ਭਲਾਈ ਕਰਨ ਵਾਲੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Los Santos del Señor son siempre un apoyo para los demás."