[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰੇ ਮਨ ਸੇਵਿ; ਤੂ ਪਰਹਿ ਪਾਰ ॥੪॥"
page = 1192
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Serve Thou the Lord, O my soul, that thou too may cross over."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਸੁਆਮੀ ਦੀ ਸੇਵਾ ਕਰ, ਹੇ ਮੇਰੀ ਜਿੰਦੜੀਏ! ਤਾਂ ਜੋ ਤੇਰਾ ਵੀ ਪਾਰ ਉਤਾਰਾ ਹੋ ਜਾਵੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O my mind, serve Him, and you shall be carried across to the other side. ||4||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਰੇ ਮਨਾ! ਤੂੰ ਭੀ ਤਿਸ ਕੋ ਸੇਵਨਾ ਕਰ, ਜੋ ਸੰਸਾਰ ਸਮੁੰਦ੍ਰ ਸੇ ਪਾਰ ਪੜ ਜਾਵੈ॥੪॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ (ਮੇਰੇ) ਮਨ! ਤੂੰ ਭੀ ਪਰਮਾਤਮਾ ਦੀ ਸਰਨ ਪਉ, (ਸੰਸਾਰ-ਸਮੁੰਦਰ ਤੋਂ) ਪਾਰ ਲੰਘ ਜਾਹਿਂਗਾ ॥੪॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਰਹਿ ਪਾਰ = ਤੂੰ (ਸੰਸਾਰ-ਸਮੁੰਦਰ ਤੋਂ) ਪਾਰ ਲੰਘ ਜਾਹਿਂਗਾ ॥੪॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Habita entonces en Él, oh mi mente para que también seas llevada hasta el otro lado. (4)"