[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੂਜਰੀ ਮਹਲਾ ੧ ॥"
page = 504
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Gujri 1st Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੂਜਰੀ ਪਹਿਲੀ ਪਾਤਿਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Goojaree, First Mehl:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Guyeri, Mejl Guru Nanak, Primer Canal Divino."