[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰ ਪਰਸਾਦੀ; ਸੋ. ਹਰਿ ਹਰਿ ਪਾਈ ਜੀਉ ॥"
page = 217
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "that Lord God I have obtained."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੁਰਾਂ ਦੀ ਦਇਆ ਰਾਹੀਂ ਮੈਂ ਉਸ ਵਾਹਿਗੁਰੂ ਸੁਆਮੀ ਨੂੰ ਪ੍ਰਾਪਤ ਕਰ ਲਿਆ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "By Guru's Grace, I have found the Lord, Har, Har."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪਰੰਤੂ ਜੋ ਤੂੰ ਦੁਖੋਂ ਕੇ ਹਰਨੇ ਵਾਲਾ ਔਰ ਹਰੇਕ ਰੂਪ ਧਾਰਨੇ ਵਾਲਾ ਹੈਂ, ਸੋ ਗੁਰੋਂ ਕੀ ਕਿਰਪਾ ਸੇ ਪਾਈਤਾ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਹ ਹਰਿ-ਪ੍ਰਭੂ ਗੁਰੂ ਦੀ ਕਿਰਪਾ ਨਾਲ ਹੀ ਮਿਲ ਸਕਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਰਸਾਦੀ = ਪਰਸਾਦਿ, ਕਿਰਪਾ ਨਾਲ। ਪਾਈ = ਪਾਈਂ, ਮੈਂ ਪਾਂਦਾ ਹਾਂ, ਮੈਂ ਪ੍ਰਾਪਤ ਕਰਦਾ ਹਾਂ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "por la Gracia del Guru Lo encuentro a Él."