[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਮ ਰਾਮ ਰਾਮ; ਸਦਾ ਸਹਾਇ ॥"
page = 865
line = 4

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Lord Master's Name is ever a helper of mine."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੁਆਮੀ ਮਾਲਕ ਦਾ ਨਾਮ ਸਦੀਵ ਹੀ ਮੇਰਾ ਸਹਾਇਤ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Lord, Raam, Raam, Raam, is always our help and support."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਰਾਮ ਰਾਮ ਮਨ ਤਨ ਬਾਣੀ ਕਰ ਕੇ ਸਦਾ ਸਹਾਈ ਜਾਨ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਜੇਹੜਾ ਪਰਮਾਤਮਾ ਸਦਾ ਹੀ ਸਹਾਇਤਾ ਕਰਨ ਵਾਲਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਹਾਇ = ਸਹਾਇਤਾ ਕਰਨ ਵਾਲਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dios es siempre nuestro Soporte,"