[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਬਿਸਮਨ ਬਿਸਮ; ਰਹੇ ਬਿਸਮਾਦ ॥"
page = 291
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "I am astonished at the wonderous mystery of the Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਸੁਆਮੀ ਦੀ ਅਸਚਰਜ ਅਦਭੁਤਤਾ ਉਤੇ ਹੈਰਾਨ ਹੋ ਰਿਹਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "We are wonder-struck at the wondrous wonder of the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਹਰੀ! ਤੁਝ ਤਿਸ ਅਸਚਰਜ ਤੋਂ ਅਸਚਰਜ ਸਰੂਪ ਕੌ ਜਾਨਨੇ ਹਾਰੇ ਭੀ ਅਸਚਰਜ ਰੂਪ ਹੋ ਰਹੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੀਵ ਤੇਰੀ ਗਤਿ ਭਾਲਦੇ ਹੈਰਾਨ ਤੇ ਅਚਰਜ ਹੋ ਰਹੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਬਿਸਮਨ ਬਿਸਮ = ਅਚਰਜ ਤੋਂ ਅਚਰਜ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "En ese entonces, el Señor Maravilloso permanecía absorbido en Su Propio Asombro;"