[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮਮਾ; ਜਾਹੂ ਮਰਮੁ ਪਛਾਨਾ ॥"
page = 259
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "M: He who knows God's secret,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮ-ਜੋ ਵਾਹਿਗੁਰੂ ਦੇ ਭੇਦ ਨੂੰ ਸਮਝਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "MAMMA: Those who understand God's mystery are satisfied,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮਮੇਂ ਅਖਰ ਦ੍ਵਾਰਾ ਕਹਤੇ ਹੈਂ: ਜਿਸ ਪੁਰਸ ਨੇ ਵਾਹਗੁਰੂ ਕੇ ਭੇਦ ਕੋ ਪਛਾਨਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਹ ਮਨੁੱਖ ਸਾਧ ਸੰਗਤਿ ਵਿਚ ਮਿਲ ਕੇ (ਇਸ ਬਾਰੇ) ਪੂਰਾ ਯਕੀਨ ਬਣਾ ਲੈਂਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜਾਹੂ = ਜਿਸ ਨੇ। ਮਰਮੁ = ਭੇਦ, (ਕਿ ਪ੍ਰਭੂ ਮੇਰੇ ਸਦਾ ਅੰਗ-ਸੰਗ ਹੈ)।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "MAMMA: Para aquél que ha conocido el Misterio de la Vida,"