[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੇ ਜਨ ਲਾਗੇ; ਗੁਰ ਕੀ ਪਾਈ ॥੨॥"
page = 194
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "fall at the feet of the Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਇਨਸਾਨ ਗੁਰਾਂ ਦੇ ਪੈਰੀ ਪੈਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "fall at the Guru's Feet. ||2||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੋ ਦਾਸ ਗੁਰੋਂ ਕੀ ਚਰਨੀ ਲਾਗੇ ਹੈਂ॥੨॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਹ ਮਨੁੱਖ ਗੁਰੂ ਦੀ ਚਰਨੀਂ ਆ ਲੱਗਦੇ ਹਨ (ਗੁਰੂ ਦੀ ਸਰਨ ਪੈਂਦੇ ਹਨ) ॥੨॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਾਈ = ਪਾਈਂ, ਪੈਰੀਂ ॥੨॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "caen a los Pies del Guru.(2)"