[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਕਿਉਣਕਿ ਇਹ ਰਸਤਾ ਤਾਣ ਰੱਬ ਦੇ ਸੂਰਮੇ ਭਗਤਾਣ ਦਾ ਹੈ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਕਿ ਈਣ ਰਾਹ ਤਅੱਲਕਿ ਮੰਜ਼ਲਿ ਮਰਦਾਨਸਤ ॥੩॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "And, not thinking about Him would get us stuck in every other worldly attraction. (275)"