[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਅਜਿਹਾ ਧਨ ਸੰਸਾਰੀ ਖਜ਼ਾਨਿਆਂ, ਮਾਲ ਅਤੇ ਚਾਂਦੀ, ਤੋਂ ਕਿਵੇਂ ਮਿਲ ਸਕਦਾ ਹੈ#"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਕੈ ਬਦਸਤ ਆਇਦ ਜ਼ਿ ਗੰਜੋ ਮਾਲੋ ਸੀਮ ॥੨੦੫॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "All the holy angels obey the command of Guru Gobind Singh,"