[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰਮੁਖਿ; ਹਰਿ ਫਲੁ ਪਾਵਹੁ ॥"
page = 767
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "and through the Guru obtain the Lord's fruit."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਗੁਰਾਂ ਦੇ ਰਾਹੀਂ ਪ੍ਰਭੂ ਦੇ ਫਲ ਨੂੰ ਪਰਾਪਤ ਕਰ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "As Gurmukh, obtain the Lord's fruitful rewards."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਗੁਰੋਂ ਦੁਆਰੇ ਹਰੀ ਕੀ ਪ੍ਰਾਪਤੀ ਰੂਪ ਫਲ ਪਾਵੋਗੇ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਦੀ ਸਰਨ ਪੈ ਕੇ (ਸਿਫ਼ਤਿ-ਸਾਲਾਹ ਦਾ ਗੀਤ ਗਾਇਆਂ) ਪਰਮਾਤਮਾ ਦੇ ਦਰ ਤੋਂ (ਇਸ ਦਾ) ਫਲ ਪ੍ਰਾਪਤ ਕਰੋਗੇ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਰਮੁਖਿ = ਗੁਰੂ ਦੀ ਸਰਨ ਪੈ ਕੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "como Gurmukj obtén la recompensa del Fruto del Señor."