[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਜਾਨਿਯੋ ਮੋਹਿ ਪੀਰ ਪਟਕਾਯੋ ॥"
page = 1012

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The imprudent did not discern and thought that the Peer had toppled him over."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਸ ਨੇ ਸਮਝਿਆ ਕਿ) ਮੈਨੂੰ ਪੀਰ ਨੇ ਪਟਕਾਇਆ ਹੈ।"