[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਉ ਮਨੁ ਮਾਨੈ; ਜਾ ਤੇ. ਹਉਮੈ ਜਈ ਹੈ ॥੨॥"
page = 325
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "the mind is appeased, when pride is stilled."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਦ ਹੰਕਾਰ ਨਵਿਰਤ ਹੋ ਜਾਂਦਾ ਹੈ, ਕੇਵਲ ਤਦ ਹੀ ਮਨ ਦੀ ਨਿਸ਼ਾ ਹੁੰਦੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The mind is only appeased, when egotism is conquered. ||2||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤੁਉ ਮਨੁ ਮਨਤਾ ਹੈ ਜੌ ਮਨ ਸੇ ਹਉਂ ਜਾਤੀ ਰਹਤੀ ਹੈ॥੨॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮਨ ਨੂੰ ਤਦੋਂ ਹੀ ਧੀਰਜ ਆ ਸਕਦੀ ਹੈ ਜੇ ਅਹੰਕਾਰ ਦੂਰ ਹੋ ਜਾਏ ॥੨॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤਉ = ਤਦੋਂ ਹੀ। ਮਾਨੈ = ਮੰਨਦਾ ਹੈ, ਪਤੀਜਦਾ ਹੈ। ਜਾ ਤੇ = ਜਦੋਂ। ਜਈ ਹੈ = ਦੂਰ ਹੋ ਜਾਏ ॥੨॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "porque la mente se calma sólo cuando se libera del ego.(2)"