[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕੁਕਰਮ ਕਾਰੀ ॥"
page = 222

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "“O the basket of sins! evil-doer,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਕੁਕਰਮ ਕਰਨ ਵਾਲੀ!"