[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੇ ਕੋ ਲਾਏ; ਭਾਉ ਪਿਆਰਾ ॥"
page = 361
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "only if man embraces it with love and affection."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੇਕਰ ਆਦਮੀ ਇਸ ਨੂੰ ਪ੍ਰੇਮ ਤੇ ਪ੍ਰੀਤ ਕਰੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "if it is embraced with love and affection."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਕੋਈ ਪ੍ਯਾਰਾ ਪੁਰਸੁ ਗੁਰੋਂ ਕੇ ਦਰਸਨ ਮੇਂ (ਭਾਉ) ਪ੍ਰੇਮ ਕਰਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਪਰ ਤਾਂ) ਜੇ ਕੋਈ ਮਨੁੱਖ (ਗੁਰੂ ਦੇ ਸ਼ਾਸਤ੍ਰ ਵਿਚ) ਪ੍ਰੇਮ-ਪਿਆਰ ਜੋੜੇ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕੋ = ਕੋਈ ਮਨੁੱਖ। ਭਾਉ = ਪ੍ਰੇਮ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "si sólo uno Lo adorara con Amor Infinito."