[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਦਰਬਿ ਸਿਆਣਪ; ਨਾ ਓਇ ਰਹਤੇ ॥"
page = 182
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Through wealth and cleverness they are not restrained."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਦੌਲਤ ਤੇ ਚਤੁਰਾਈ ਰਾਹੀਂ ਉਹ ਨਹੀਂ ਰੁਕਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "they cannot be restrained by wealth or cleverness."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਧਨ ਔਰ ਚਤੁਰਾਈ ਕਰ ਕੇ ਭੀ ਵਹੁ ਰੁਕੇ ਨਹੀਂ ਰਹਤੇ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਹ ਪੰਜੇ ਡਾਕੂ ਨਾਹ ਧਨ ਨਾਲ ਵਰਜੇ ਜਾ ਸਕਦੇ ਹਨ, ਨਾਹ ਚਤੁਰਾਈ ਨਾਲ ਵਰਜੇ ਜਾ ਸਕਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਦਰਬਿ = ਧਨ ਨਾਲ। ਓਇ = {ਲਫ਼ਜ਼ 'ਓਹ' ਤੋਂ ਬਹੁ-ਵਚਨ}।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Los bandidos no son sobornados por el dinero, ni engañados por la astucia."