[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਖਵਾਰੇ ਕਾ ਹੋਇ ਬਿਨਾਸ ॥"
page = 871
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "When this care-taker dies,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਦ ਇਹ ਰੱਖਿਆ ਕਰਨ ਵਾਲਾ ਮਰ ਜਾਂਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "When this protector dies,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਉਸ ਰਾਖੇ ਕਾ ਭੀ ਬਿਨਾਸ ਹੋਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਇਸ ਮਾਇਆ ਦਾ) ਰਾਖਾ ਮਰ ਜਾਂਦਾ ਹੈ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y cuando el que la atiende también muere,"