[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰ ਊਪਰਿ; ਸਦਾ ਕੁਰਬਾਨੁ ॥੨॥"
page = 864
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Unto the Guru, I am ever a sacrifice."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੁਰਾਂ ਦੇ ਉਤੋਂ ਮੈਂ ਸਦੀਵ ਹੀ ਸਦਕੇ ਜਾਂਦਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I am forever a sacrifice to the Guru. ||2||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਸੀ ਤੇ ਗੁਰੋਂ ਕੇ ਊਪਰ ਸੇ ਹਮ ਸਦਾ ਕੁਰਬਾਨ ਜਾਤੇ ਹੈਂ॥੨॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਮੇਰੇ ਮਨ! ਗੁਰੂ ਤੋਂ ਸਦਾ ਸਦਕੇ ਹੋ ॥੨॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "ofrezco siempre mi ser en sacrificio al Guru. (2)"