[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਤਿ ਬਚਨ; ਵਰਤਹਿ ਹਰਿ ਦੁਆਰੇ ॥"
page = 869
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "These words prove to be true in the Lord's court."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਇਹ ਸ਼ਬਦ ਹਰੀ ਦੇ ਦਰਬਾਰ ਅੰਦਰ ਸੱਚੇ ਉਤਰਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "these words shall be true in the Court of the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤੁਸੀਂ ਸਚ ਬਚਨ ਸੁਣੋਂ, ਜੋ ਹਰੀ ਕੇ ਦੁਆਰੇ ਮੇਂ ਵਰਤਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਮੈਂ ਤੈਨੂੰ ਉਹ) ਅਟੱਲ ਨਿਯਮ (ਦੱਸਦਾ ਹਾਂ ਜੋ) ਪਰਮਾਤਮਾ ਦੇ ਦਰ ਤੇ (ਸਦਾ) ਵਾਪਰਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਤਿ = {सत्य} ਅਟੱਲ, ਸਦਾ ਕਾਇਮ ਰਹਿਣ ਵਾਲਾ। ਵਰਤਹਿ = ਵਰਤਦੇ ਹਨ, ਵਾਪਰਦੇ ਹਨ। ਦੁਆਰੇ = ਦੁਆਰਿ, ਦਰ ਤੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "que, en la Corte del Señor, la Palabra del Shabd Verdadera es lo único que sirve"