[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਧਨਾਸਰੀ ਮਹਲਾ ੩ ਘਰੁ ੨ ਚਉਪਦੇ ॥"
page = 663
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Dhanasri 3rd Guru. Chaupadas."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਧਨਾਸਰੀ ਤੀਜੀ ਪਾਤਿਸ਼ਾਹੀ। ਚਉਪਜੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Dhanaasaree, Third Mehl, Second House, Chau-Padhay:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਧਨਾਸਰੀ, ਘਰ ੨ ਵਿੱਚ ਗੁਰੂ ਅਮਰਦਾਸ ਜੀ ਦੀ ਚਾਰ-ਬੰਦਾਂ ਵਾਲੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dhanasri, Mejl Guru Amar Das, Tercer Canal Divino, Chau-Padas."