[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਿਸਨਪਦ ॥ ਪਰਜ ॥ ਤ੍ਵਪ੍ਰਸਾਦਿ ਕਥਤਾ ॥"
page = 681

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "VISHNUPADA SAYING (A MUSICAL MODE) PARAZ"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਬਿਸਨਪਦ: ਪਰਜ: ਤੇਰੀ ਕ੍ਰਿਪਾ ਨਾਲ ਕਹਿੰਦਾ ਹਾਂ:"