[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੋਹ ਭਰਮਿ; ਬਹੁ ਜੋਨਿ ਭਵਾਇਆ ॥"
page = 388
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Worldly attachment and doubt, make man wander through many births."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੰਸਾਰੀ ਲਗਨ ਅਤੇ ਸੰਦੇਹ ਆਦਮੀ ਨੂੰ ਘਣੇਰੀਆਂ ਜੂਨੀਆਂ ਅੰਦਰ ਭਟਕਾਉਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "In emotional attachment and doubt, the mortals wander through countless incarnations."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਅਕਾਲ ਪੁਰਖ ਨੇ ਭਗਤ ਹੀਨ ਪੁਰਖੋਂ ਕੋ ਮੋਹ ਔਰ ਭਰਮ ਕੇ ਹੋਨੇ ਕਰ ਬਹੁਤ ਜੋਨੀਓਂ ਮੇਂ ਭ੍ਰਮਾਇਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ! ਮਾਇਆ ਦੇ) ਮੋਹ ਦੀ ਭਟਕਣਾ ਵਿਚ ਪੈ ਕੇ ਮਨੁੱਖ ਅਨੇਕਾਂ ਜੂਨਾਂ ਵਿਚ ਭਵਾਏ ਜਾਂਦੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਭਰਮਿ = ਭਟਕਣਾ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Apego y duda hacen que los hombres vaguen a través de millones de nacimientos,"