[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੁਤੁ; ਅਪਰਾਧ ਕਰਤ ਹੈ ਜੇਤੇ ॥"
page = 478
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "As many as faults the son commits,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿੰਨੇ ਕਸੂਰ ਪੁੱਤਰ ਕਰਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "As many mistakes as the son commits,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪੁਤ੍ਰ ਜਿਤਨੇ ਔਗੁਨ ਕਰਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪੁੱਤਰ ਭਾਵੇਂ ਕਿਤਨੀਆਂ ਹੀ ਗ਼ਲਤੀਆਂ ਕਰੇ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੁਤੁ = ਪੁੱਤਰ। ਅਪਰਾਧ = ਭੁੱਲਾਂ, ਗ਼ਲਤੀਆਂ। ਜੇਤੇ = ਜਿਤਨੇ ਭੀ, ਭਾਵੇਂ ਕਿਤਨੇ ਹੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El hijo comete error tras error,"