[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੰਨਿਆਸੀ ਮਾਤੇ ਅਹੰਮੇਵ ॥"
page = 1193
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The secitarians are inebriated in the mysteries of self-conceit."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਇਕਾਂਤੀ ਸਵੈ-ਹੰਗਤਾ ਅੰਦਰ ਨਸ਼ਈ ਹੋਏ ਹੋਏ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Sannyaasees are intoxicated in egotism."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੰਨਿਆਸੀ ਭੀ (ਅਹੰਮੇਵ) ਹੰਕਾਰ ਮੇਂ ਮਾਤੇ ਹੂਏ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸੰਨਿਆਸੀ (ਸੰਨਿਆਸ ਦੇ) ਅਹੰਕਾਰ ਵਿਚ ਡੁੱਬੇ ਹੋਏ ਹਨ;"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਅਹੰਮੇਵ = ਅਹੰਕਾਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "los Sanyasas de forma egocéntrica se han involucrado en ellos mismos,"