[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਗੁਰਮੁਖਿ ਕਿਰਤਿ ਕਮਾਵਣੀ; ਨਮਸਕਾਰੁ ਡੰਡਉਤਿ ਸਿਞਾਪੈ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Earning livelihood with his hands by a Sikh is equal to the obeisance and prostration (of Hindus)."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਗੁਰਮੁਖ (ਹੱਥਾਂ ਨਾਲ) ਕਿਰਤ ਕਰਦੇ ਹਨ ਅਰ ਸਿਰ ਕਰ ਕੇ ਨਮਸਕਾਰ ਤੇ ਡੰਡੌਤਾਂ ਕਰਦੇ ਹਨ।"