[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਨਕ ਜਾਪੀ ਜਪੁ ਜਾਪੁ ॥"
page = 896
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Nanak, the worshipper, ever utters the Name of Him,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਪਾਸ਼ਕ ਨਾਨਕ ਸਦਾ ਉਸ ਦੇ ਨਾਮ ਦਾ ਉਚਾਰਨ ਕਰਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Nanak chants the Chant of the Lord,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਿਤੇ ਹੈਂ: ਤਿਸ ਕੇ ਜਪ ਕੋ ਜਾਪ ਕਰਿਕੇ ਤੂੰ ਜਾਪੀ ਅਰਥਾਤ ਜਾਨਨੇਹਾਰਾ ਹੋ; ਵਾ (ਜਾਪੀ) ਜਪਨੇ ਜੋਗੁ ਜੋ ਹੈ ਤਿਸ ਕੇ ਜਪ ਕੋ ਜਪ; ਵਾ (ਜਾਪੀ) ਜਾਪਕ ਹੋਇਕੈ ਜਾਪਿ ਕੋ ਜਾਪੁ॥☬ਸੌ ਕੌਣ ਹੈ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਨਾਨਕ ਸਦਾ ਹੀ ਉਸ ਪ੍ਰਭੂ ਦਾ ਨਾਮ ਦਾ ਜਾਪ ਜਪਦਾ ਰਹੇ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜਾਪੀ = ਜਾਪੀਂ, ਮੈਂ ਜਪਦਾ ਰਹਾਂ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Tu Gloria, en verdad,"