[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪਾਰਬ੍ਰਹਮ ਕੀ; ਜਿਸੁ ਮਨਿ ਭੂਖ ॥"
page = 281
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He in whose mind is the hunger of the Supreme Lord,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਦੇ ਚਿੱਤ ਅੰਦਰ ਪਰਮ ਪ੍ਰਭੂ ਦੀ ਭੁਖ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "One whose mind hungers for the Supreme Lord God,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਕੇ ਮਨ ਮੇਂ ਪਾਰਬ੍ਰਹਮ ਕੀ ਭੂਖ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਮਨੁੱਖ ਦੇ ਮਨ ਵਿਚ ਪ੍ਰਭੂ (ਦੇ ਮਿਲਣ) ਦੀ ਤਾਂਘ ਹੈ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Viviendo la mente en Añoranza del Supremo Estado,"