[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਾਜਨ ਸੰਤ; ਕਰਹੁ ਇਹੁ ਕਾਮੁ ॥"
page = 290
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O friendly saints do this work."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਮਿਤ੍ਰ ਸਾਧੂਓ! ਇਹ ਕੰਮ ਕਰੋ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O friends, O Saints, make this your work."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਸੰਤ ਸ੍ਵਜਨੋਂ! ਤੁਮ ਇਹੀ ਕਾਮ ਕਰੋ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਸੱਜਣ ਜਨੋ! ਹੇ ਸੰਤ ਜਨੋ! ਇਹ ਕੰਮ ਕਰੋ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Santo amigo, destina tu existencia a meditar en el Nombre de Dios."