[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਮਕਲੀ ਮਹਲਾ ੫ ਅਸਟਪਦੀ ॥"
page = 915
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Ramkali 5th Guru. Ashatpadi."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਮਕਲੀ ਪੰਜਵੀਂ ਪਾਤਿਸ਼ਾਹੀ। ਅਸ਼ਟਪਦੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Raamkalee, Fifth Mehl, Ashtapadee:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਰਾਮਕਲੀ ਵਿੱਚ ਗੁਰੂ ਅਰਜਨਦੇਵ ਜੀ ਦੀ ਅੱਠ-ਬੰਦਾਂ ਵਾਲੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ramkali, Mejl Guru Aryan, Quinto Canal Divino, Ashtapadis."