[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੁਖ ਸਾਂਦਿ. ਘਰਿ ਆਇਆ ॥"
page = 629
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Safe and sound, I have come back to my home."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਜ਼ੀ ਬਾਜ਼ੀ ਮੈਂ ਆਪਣੇ ਗ੍ਰਿਹ ਆਇਆ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Safe and sound, I have returned home."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੁਖ ਅਰ (ਸਾਂਦਿ) ਸਾਂਤੀ ਸੇ ਹਮਾਰਾ ਘਰ ਮੇਂ ਆਵਣਾ ਹੂਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਸੰਤ ਜਨੋ!) ਉਹ ਮਨੁੱਖ ਪੂਰੀ ਆਤਮਕ ਅਰੋਗਤਾ ਨਾਲ ਆਪਣੇ ਹਿਰਦੇ-ਘਰ ਵਿਚ (ਸਦਾ ਲਈ) ਟਿਕ ਗਿਆ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੁਖ ਸਾਂਦਿ = ਸੁਖ-ਸਾਂਦ ਨਾਲ, ਖ਼ੈਰੀਅਤ ਨਾਲ, ਆਤਮਕ ਅਰੋਗਤਾ ਨਾਲ। ਘਰਿ = ਹਿਰਦੇ-ਘਰ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "He regresado a mi Hogar a salvo y en Paz."