[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਆਨਿ ਗਾਵ ਤੇ ਬਚਨ ਕਹੈਂਗੇ ॥"
page = 840

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "‘They would, no doubt, indulge in cacophony."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਹ ਲੋਕ) ਆ ਕੇ ਪਿੰਡ ਵਿਚ ਗੱਲਾਂ ਕਰਨਗੇ,"