[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਭਰਨ ਸਕਲ ਅੰਗ ਮੈ ਧਾਰਿਯੋ ॥"
page = 1117

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਸ ਨੇ) ਸਾਰੇ ਸ਼ਰੀਰ ਉਤੇ ਸੁੰਦਰ ਗਹਿਣੇ ਸਜਾ ਲਏ।"