[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਮਾਤਾ ਬਾਚ ॥"
page = 227

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of the Mother :"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਮਾਤਾ (ਕੁਸ਼ਲਿਆ) ਕਹਿੰਦੀ ਹੈ-"