[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੁੰਦਰ ਸੁਬੇਸ ॥੪੩॥"
page = 630

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "“O princess! Look towards these elegantly dressed warrior-kings of the countery.”43."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਇਸ ਦਾ ਵੇਸ ਬਹੁਤ ਸੁੰਦਰ ਹੈ ॥੪੩॥"