[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਹ ਰਹਿਮਤਾਂ ਦੀ ਬਹੁਤਾਤ ਅਤੇ ਨਿਆਮਤਾਂ ਦਾ ਅਤਿਅੰਤ ਹੈ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਤਵਾਫ਼ਰ ਤਰਾਹਮ ਤਕਾਸਰ ਨਅਮ ॥੧੩੫॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "He is the bounty of benevolence and ultimate of granting boons. (135)"