[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਹਮੇਸੁਲ ਅਭੇਖ ਹੈਂ ॥੧੫੭॥"
page = 8
line = 19

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Thou art ever garbles! 157"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਸਦਾ ਭੇਖਾਂ ਤੋਂ ਰਹਿਤ ਹੈਂ ॥੧੫੭॥"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਹਮੇਸੁਲ, ਅਭੇਖ ਹੈਂ ॥੧੫੭॥"