[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਤਿਗੁਰ ਮੇਰੇ ਕੀ ਵਡਿਆਈ ॥"
page = 1142
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The glory of my True Guru,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ ਸੱਚੇ ਗੁਰਾਂ ਦੀ ਪ੍ਰਭਤਾ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The glorious greatness of my True Guru"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ ਸਤਿਗੁਰੋਂ ਕੀ ਵਡਿਆਈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਦੀ ਇਹ ਉੱਚੀ ਸੋਭਾ-"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਵਡਿਆਈ = ਸੋਭਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Gloria sea para mi Guru Verdadero,"