[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਵਿਦਾਸ ਧਿਆਏ; ਪ੍ਰਭ ਅਨੂਪ ॥"
page = 1192
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Ravidass meditated on the beauteous Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਵਿਦਾਸ ਨੇ ਸੁੰਦਰ ਸੁਆਮੀ ਦਾ ਸਿਮਰਨ ਕੀਤਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Ravi Daas meditated on God, the Incomparably Beautiful."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪੁਨਹ ਰਵਿਦਾਸ ਜੀ, ਹੇ ਪ੍ਰਭੂ! ਤੇਰੇ ਅਨੂਪਮ ਚਰਨ ਧ੍ਯਾਵਤੇ ਭਏ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਵਿਦਾਸ ਨੇ ਭੀ ਸੋਹਣੇ ਪ੍ਰਭੂ ਦਾ ਸਿਮਰਨ ਕੀਤਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਅਨੂਪ = ਉਪਮਾ-ਰਹਿਤ, ਸੋਹਣਾ, ਸੁੰਦਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ravidas Te contempló, oh Dios, de Belleza Incomparable,"