[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਮਸਤੰ ਨਿਰਾਸਰੇ ॥੧੬॥"
page = 2
line = 11

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Salutation to Thee O Propless Lord! 16"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਬਿਨਾ ਆਸਰੇ ਵਾਲੇ! ਤੈਨੂੰ ਨਮਸਕਾਰ ਹੈ ॥੧੬॥"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨਮਸਤੰ, ਨਿਰਾਸਰੇ ॥੧੬॥"