[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਚਲ ਸਿੰਘ ਬਾਚ ॥"
page = 415

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of Achal Singh:"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਚਲ ਸਿੰਘ ਨੇ ਕਿਹਾ:"