[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਭਗਤ ਜਨਾ ਕਾ ਪ੍ਰੀਤਮੁ ਪਿਆਰਾ ॥"
page = 1072
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Loved Lord is dear unto His devotees."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪਿਆਰਾ ਪ੍ਰਭੂ ਆਪਣੇ ਪਗਤਾਂ ਦਾ ਲਾਡਲਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Dear Lord is the Beloved of His humble devotees."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਐਸਾ ਜੋ ਪ੍ਰੀਤਮ ਹੈ, ਸੋ ਭਗਤ ਜਨ ਕਾ ਪਿਆਰਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸਾਡਾ ਮਾਲਕ-ਪ੍ਰਭੂ ਆਪਣੇ ਭਗਤਾਂ ਦਾ ਪਿਆਰਾ ਹੈ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Señor es el Bienamado de Sus Devotos."