[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਭ ਪੂਰਨ ਗੁਨਤਾਸ ॥"
page = 1306
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O my perfect Lord, the Treasure of virtues."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਨੇਕੀਆਂ ਦੇ ਖਜਾਨੇ ਮੇਰੇ ਸੰਪੂਰਨ ਮਾਲਕ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "God is the Perfect Treasure of Virtue."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਗੁਣਤਾਸ ਪੂਰਨ ਪ੍ਰਭੂ! ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪੂਰਨ ਪ੍ਰਭੂ! ਹੇ ਗੁਣਾਂ ਦੇ ਖ਼ਜ਼ਾਨੇ!"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਨ ਤਾਸ = ਹੇ ਗੁਣਾਂ ਦੇ ਖ਼ਜ਼ਾਨੇ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dios es el Perfecto Tesoro de Virtud."