[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਗੋਯਾ ਦੇ ਸ਼ਿਅਰ ਹਿੰਦੁਸਤਾਨ ਵਿਚ ਅਜੇਹੇ ਮੇਵੇ ਹਨ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਸ਼ੇਅਰਿ ਗੋਯਾ ਬੇਸ਼ ਅਜ਼ ਸ਼ੀਰੋ ਸ਼ਕਰ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "O wind! Do not blow away my dust from the door of my Beloved,"