[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੂੰ ਅਚਾਨਕ ਮੈਂ ਆਪਣੇ ਘਰ ਅੰਦਰ ਹੀ ਦੇਖ ਲਿਆ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਯਾਫ਼ਤਮ ਨਾਗਾਹ ਦਰ ਕਾਸ਼ਾਨਾਇ ॥੪੧੩॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Suddenly, I discovered Him inside my own home (body). (413)"