[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਬੀਰੁ ॥ ਮਾਰੂ ॥"
page = 1106
line = 6

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Kabir Maru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕਬੀਰ ਮਾਰੂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Kabeer, Maaroo:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Rag Maru, Kabir."