[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਦੂਜੈ ਪਾਥਰ; ਧਰੀਐ ਪਾਉ ॥"
page = 525
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Another stone is trodden under the feet."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਦੂਸਰਾ ਪਾਹਨ ਪੈਰਾਂ ਦੇ ਨਾਲ ਲਤਾੜਿਆ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "while another stone is walked upon."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਔ ਦੂਸਰੇ ਪਥਰ ਪਰ ਪੈਰ ਧਰਤੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤੇ ਦੂਜੇ ਪੱਥਰਾਂ ਉੱਤੇ ਪੈਰ ਧਰਿਆ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਾਉ = ਪੈਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "mientras a otra piedra la pisoteamos;"