[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਉ; ਸਤਿਗੁਰ ਵਿਟਹੁ ਘੁਮਾਇਆ ॥"
page = 72
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "I am a sacrifice unto the True Guru,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਸਚੇ ਗੁਰਾਂ ਉਤੋਂ ਘੋਲੀ ਜਾਂਦਾ ਹਾਂ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I am a sacrifice to the True Guru;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਸਤਿਗੁਰੂ ਕੇ (ਵਿਟਹੁ) ਊਪਰ ਸੇ (ਘੁਮਾਇਆ) ਬਲਿਹਾਰ ਜਾਤਾ ਹੂੰ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮੈਂ (ਤਾਂ) ਗੁਰੂ ਤੋਂ ਕੁਰਬਾਨ ਹਾਂ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਵਿਟਹੁ = ਤੋਂ। ਹਉ = ਮੈਂ। ਘੁਮਾਇਆ = ਕੁਰਬਾਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ofrezco mi vida al Guru Verdadero,"