[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਾਦੁ ਆਇਆ. ਤਿਨ ਹਰਿ ਜਨਾਂ; ਚਖਿ ਸਾਧੀ ਡਿਠਾ ॥"
page = 321
line = 6

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Those God's men and saints who taste it, realise the relish thereof."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਰੱਬ ਦੇ ਬੰਦੇ ਅਤੇ ਸੰਤ, ਜੋ ਇਸ ਨੂੰ ਛਕਦੇ ਹਨ, ਉਸ ਦੇ ਸੁਆਦ ਨੂੰ ਅਨੁਭਵ ਕਰਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Those humble servants of the Lord who taste it, come to savor its flavor."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪਰੰਤੂ ਜਿਨ ਹਰੀ ਜਨੋਂ ਕੋ ਸ੍ਵਾਦ ਆਇਆ ਹੈ ਤਿਨੋਂ ਨੇ ਸੰਤੋਂ ਦ੍ਵਾਰਾ ਚਖ ਕਰ ਦੇਖਿਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਪਰ) ਇਹ ਸੁਆਦ ਉਨ੍ਹਾਂ ਸਾਧੂਆਂ ਨੂੰ ਹਰਿ-ਜਨਾਂ ਨੂੰ ਆਉਂਦਾ ਹੈ ਜਿਨ੍ਹਾਂ (ਇਹ ਨਾਮ-ਰਸ) ਚੱਖ ਕੇ ਵੇਖਿਆ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਾਦੁ = ਸੁਆਦ। ਸਾਧੀ = ਸਾਧੀ, ਸਾਧ ਜਨਾਂ ਨੇ। ਚਖਿ ਡਿਠਾ = ਚੱਖ ਵੇਖਿਆ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Los Santos lo prueban y encuentran que es muy sabroso."