[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੁੰਭ ਮਾਰ ਕੈ ਚੰਡਿਕਾ; ਉਠੀ ਸੁ ਸੰਖ ਬਜਾਇ ॥"
page = 100

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "After killing Sumbh, Chnadika rose to blow her conch.,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸ਼ੁੰਭ ਨੂੰ ਮਾਰ ਕੇ ਚੰਡੀ ਉਠੀ ਅਤੇ ਸੰਖ ਵਜਾਇਆ।"