[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਮ ਭਗਤਿ ਬਿਨੁ; ਨਿਹਫਲ ਸੇਵਾ ॥੨॥"
page = 1158
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Without the Lord's devotion, fruitless is other service."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਾਈਂ ਦੇ ਅਨੁਰਾਗ ਦੇ ਬਾਝੋਂ ਨਿਸਫਲ ਹੈ, ਹੋਰ ਟਹਿਲ ਸੇਵਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Without devotional worship of the Lord, service is useless. ||2||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "(ਰਾਮ) ਹੇ ਰਮਣ ਰੂਪ ਪਰਮੇਸ੍ਵਰ! ਤੇਰੀ ਭਗਤੀ ਸੇ ਬਿਨਾਂ ਔਰ ਸੇਵਾ ਨਿਸਫਲ ਹੈ॥੨॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਮੈਂ ਜਾਣਦਾ ਹਾਂ ਕਿ) ਪ੍ਰਭੂ ਦੀ ਬੰਦਗੀ ਤੋਂ ਬਿਨਾ ਹੋਰ ਕਿਸੇ ਦੀ ਪੂਜਾ ਵਿਅਰਥ ਹੈ ॥੨॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pues sin Devoción, uno no sirve a Dios. (2)"