[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੋ ਸਤਿਗੁਰੁ; ਜਿਸੁ ਰਿਦੈ ਹਰਿ ਨਾਉ ॥"
page = 287
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He is the True Guru within whose mind is God's Name."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹੀ ਸੱਚਾ ਗੁਰੂ ਹੈ, ਜਿਸ ਦੇ ਮਨ ਅੰਦਰ ਵਾਹਿਗੁਰੂ ਦਾ ਨਾਮ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The True Guru's Heart is filled with the Name of the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੋਈ ਸਤਿਗੁਰੂ ਹੈ ਜਿਸ ਕੇ ਰਿਦੇ ਮੇਂ ਹਰੀ ਕਾ ਨਾਮ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸਤਿਗੁਰੂ (ਭੀ) ਉਹ ਹੈ ਜਿਸ ਦੇ ਹਿਰਦੇ ਵਿਚ ਪ੍ਰਭੂ ਦਾ ਨਾਮ ਵੱਸਦਾ ਹੈ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Verdadero Guru es aquél que conserva el corazón colmado de Amor al Nombre;"