[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਿੰਕੁਰੀ ਅਨੂਪ ਵਾਜੈ ॥"
page = 886
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Lord's lyre plays handsomely,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਾਹਿਬ ਦੀ ਵੀਣਾ ਸੁਹਣੀ ਤਰ੍ਹਾਂ ਵੱਜਦੀ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The celestial harp plays the incomparable melody,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਜੋਗੀ! ਜੋ ਬਾਹਰ ਸੁੰਦਰ ਕਿੰਗਰੀ ਵਜ ਰਹੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਵੇਖ, ਅੱਗੇ ਹੀ) ਸੁੰਦਰ ਕਿੰਗ ਬੜੀ ਸੋਹਣੀ ਵੱਜ ਰਹੀ ਹੈ"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਿੰਕੁਰੀ = ਕਿੰਗਰੀ, ਸੋਹਣੇ ਕਿੰਗ। ਅਨੂਪ = ਉਪਮਾ-ਰਹਿਤ, ਬੇ-ਮਿਸਾਲ, ਬਹੁਤ ਸੋਹਣੀ। ਵਾਜੈ = (ਅੱਗੇ ਹੀ) ਵੱਜ ਰਹੀ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Arpa Celestial toca la Incomparable Melodía,"