[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਹੋਰਸੁ ਕਿਸੈ ਨ ਜਾਣਈ, ਚਿਤਿ ਬੇਪਰਵਾਹੀ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "And if being enough powerful to care for nobody is still engrossed in dilemma,"

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਹੋਰ ਕਿਸੇ ਨੂੰ ਨਾ ਜਾਣੇ ਅਰ ਚਿੱਤ ਵਿਖੇ ਬੇਪਰਵਾਹੀ ਰੱਖੇ (ਐਸਾ ਮਨੌਂ ਅਲਗਰਜ਼ ਭੀ ਹੋਵੇ)।"