[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਮ ਨਾਮ ਬਿਨੁ. ਸਭੈ ਬਿਗੂਤੇ; ਦੇਖਹੁ ਨਿਰਖਿ ਸਰੀਰਾ ॥"
page = 654
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Without the Lord's Name, all are ruined, see and ascertain this, O man."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੁਆਮੀ ਦੇ ਨਾਮ ਬਗੈਰ ਸਾਰੇ ਤਬਾਹ ਹੋ ਗਏ ਹਨ। ਇਸ ਨੂੰ ਵੇਖ ਕੇ ਨਿਰਣਯ ਕਰ ਲੈ, ਹੇ ਬੰਦੇ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Without the Lord's Name, all come to ruin; behold, and know this, O body."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਤੇ ਹੇ ਭਾਈ! ਰਾਮ ਨਾਮ ਸੇ ਬਿਨਾ ਸਭੀ (ਬਿਗੂਤੇ) ਖਰਾਬ ਹੂਏ ਹੈਂ, ਅਪਨੇ ਸਰੀਰੋਂ ਮੇਂ ਨਿਰਨਾ ਕਰ ਕੇ ਦੇਖ ਲੇਵੋ ਵਾ ਸਰੀਰਾਂ (ਨਿਰਖਿ) ਮੁਲ ਲਖ ਲੇਵੋ, ਭਾਵ ਤੁਛ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਆਪੋ-ਆਪਣੇ ਅੰਦਰ ਝਾਤ ਮਾਰ ਕੇ ਵੇਖ ਲਵੋ, ਪਰਮਾਤਮਾ ਦੇ ਨਾਮ ਦਾ ਸਿਮਰਨ ਕਰਨ ਤੋਂ ਬਿਨਾ ਸਭ ਜੀਵ ਖ਼ੁਆਰ ਹੋ ਰਹੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਬਿਗੂਤੇ = ਖ਼ੁਆਰ ਹੋਏ। ਨਿਰਖ = {Skt. निरीक्ष्य} ਗਹੁ ਨਾਲ ਤੱਕ ਕੇ, ਨਿਰਨਾ ਕਰ ਕੇ। ਸਰੀਰਾ = ਸਰੀਰ ਵਿਚ, ਆਪਣੇ ਅੰਦਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sin el Nombre del Señor todos están perdidos;"