[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕੋਟਿ ਪੂਜਾਰੀ ਕਰਤੇ ਪੂਜਾ ॥"
page = 1156
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Millions of worshippers worship the Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕ੍ਰੋੜਾਂ ਹੀ ਉਪਾਸ਼ਕ ਪ੍ਰਭੂ ਦੀ ਉਪਾਸ਼ਨਾ ਕਰਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Millions of worshippers worship Him."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕ੍ਰੋੜ ਹੀ ਪੁਜਾਰੀ ਹੋ ਕੇ ਤੇਰੀ ਪੂਜਾ ਕਰ ਰਹੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਕ੍ਰੋੜਾਂ ਪੁਜਾਰੀ ਉਸ ਦੀ ਪੂਜਾ ਕਰ ਰਹੇ ਹਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "a Quien millones de Devotos alaban con todo su ser,"