[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਜੋ ਅਗਮ ਨਿਗਮ ਕੀ; ਲਖੈ ਸੁਮਾਰਾ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "He narrates about the inaccessible body-corporate."