[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਾ ਕੀ ਸੇਵ; ਨ ਬਿਰਥੀ ਜਾਸੀ ॥"
page = 626
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "and His service goes not in vain."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਉਸ ਦੀ ਟਹਿਲ ਨਿਸਫਲ ਨਹੀਂ ਜਾਂਦੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Service to Him shall never go unrewarded."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "(ਤਾ) ਤਿਸ ਤੇਰੀ ਸੇਵਾ (ਕੀ) ਕਰੀ ਹੂਈ ਬਿਅਰਥ ਨਹੀਂ ਜਾਤੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਦੀ ਕੀਤੀ ਹੋਈ ਸੇਵਾ-ਭਗਤੀ ਖ਼ਾਲੀ ਨਹੀਂ ਜਾਂਦੀ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤਾ ਕੀ = ਉਸ (ਪ੍ਰਭੂ) ਦੀ। ਸੇਵ = ਸੇਵਾ-ਭਗਤੀ। ਬਿਰਥੀ = ਵਿਅਰਥ, ਖ਼ਾਲੀ। ਜਾਸੀ = ਜਾਏਗੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Su Servicio nunca se desperdicia."