[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਜੀ ਮੇਰੀ ਸਾਰ ਕਰੇ; ਹਮ ਹਰਿ ਕੇ ਬਾਲਕ ॥"
page = 1101
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Reverend God takes care of me and I am the child of God."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪੂਜਯ ਵਾਹਿਗੁਰੂ ਮੇਰੀ ਸੰਭਾਲ ਕਰਦਾ ਹੈ ਅਤੇ ਮੈਂ ਵਾਹਿਗੁਰੂ ਦਾ ਬੱਚਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Dear Lord takes care of me; I am the child of the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹਰਿ ਜੀ ਮੇਰੀ ਸੰਭਾਲ ਕਰਤਾ ਹੈ, ਕਿਉਂਕਿ ਹਮ ਹਰਿ ਕੇ ਬਾਲਕ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪ੍ਰਭੂ ਮੇਰੀ ਸੰਭਾਲ ਕਰਦਾ ਹੈ, ਅਸੀਂ ਪ੍ਰਭੂ ਦੇ ਬੱਚੇ ਹਾਂ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਾਰ = ਸੰਭਾਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pues soy el hijo de Dios. Nunca me abandona y me alimenta todo el tiempo,"