[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਕਾ ਨਾਮੁ; ਜਪਹੁ ਜੀਅ ਸਦਾ ॥"
page = 266
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "heartily utter the Name of God."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹਮੇਸ਼ਾਂ ਦਿਲੋਂ ਵਾਹਿਗੁਰੂ ਦਾ ਨਾਮ ਉਚਾਰਨਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "is to chant the Name of the Lord in the heart, forever."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਤੇ ਹਰੀ ਕਾ ਨਾਮ ਹੀ ਜੀਅ ਮੇਂ ਸਦਾ ਜਪਣਾ ਕਰੋ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਮਨ! ਸਦਾ ਪ੍ਰਭੂ ਦਾ ਨਾਮ ਜਪ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜੀਅ = ਹੇ ਜੀ! ਹੇ ਮਨ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "la permanente Contemplación del Señor."