[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਹਥੀਂ ਕਿਰਤਿ ਕਮਾਂਵਦਾ; ਪਗਿ ਚਲੈ ਸੁਜਾਣਾ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "He works with hands and He, the Omniscient One, walks on feet."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਹਥਾਂ (ਅੰਦਰ ਹੋਕੇ) ਕਿਰਤ ਕਰਦਾ ਤੇ ਸਿਆਣਾ ਪੈਰਾਂ ਨਾਲ ਤੁਰਦਾ ਹੈ।"