[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਭੂ ਦਇਆ ਤੇ; ਮੰਗਲੁ ਗਾਵਉ ॥"
page = 101
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Through the Lord's grace, I sing songs of joy."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੁਆਮੀ ਦੀ ਮਿਹਰ ਰਾਹੀਂ ਮੈਂ ਖੁਸ਼ੀ ਦੇ ਗੀਤ ਗਾਇਨ ਕਰਦਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "By God's Kindness, I sing the songs of joy."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਰਭੂ! ਤੁਮਾਰੀ ਦਯਾ ਤੇ ਮੰਗਲ ਰੂਪ ਜਸ ਗਾਇਨ ਕਰਤਾ ਹੂੰ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰਮਾਤਮਾ ਦੀ ਹੀ ਕਿਰਪਾ ਨਾਲ ਮੈਂ ਪਰਮਾਤਮਾ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਦਾ ਗੀਤ ਗਾਂਦਾ ਹਾਂ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੰਗਲੁ = ਸਿਫ਼ਤਿ-ਸਾਲਾਹ ਦਾ ਗੀਤ। ਗਾਵਉ = ਗਾਵਉਂ, ਮੈਂ ਗਾਂਦਾ ਹਾਂ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Por la Misericordia del Señor, entona los estribillos de Éxtasis."