[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਦੁਤਿਯ ਨ ਪੁਰਖਹਿ ਭੇਦ ਜਤਾਯੋ ॥"
page = 1213

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕਿਸੇ ਹੋਰ ਬੰਦੇ ਨੂੰ ਇਸ ਬਾਰੇ ਨਾ ਦਸਿਆ।"