[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਰੂਆਲ ਛੰਦ ॥"
page = 697

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "ROOAAL STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਰੂਆਲ ਛੰਦ:"