[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਹੁਰਿ ਤਵਨ ਸੌ ਕੇਲ ਕਮਾਯੋ ॥"
page = 1001

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "At night Rani called him over and enjoyed lovemaking with him."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਨਾਲ ਫਿਰ ਕਾਮ-ਕ੍ਰੀੜਾ ਕੀਤੀ।"