[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਏਕੁ ਤੁਈ. ਏਕੁ ਤੁਈ ॥੭॥"
page = 144
line = 6

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Thou alone art, O Lord! Thou alone art."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕੇਵਲ ਤੂੰ ਹੀ ਹੈਂ ਹੇ ਸੁਆਮੀ! ਕੇਵਲ ਤੂੰ ਹੀ ਹੈਂ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "You alone, O Lord, You alone. ||7||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤੀਨੋਂ ਕਾਲ ਮੇਂ ਏਕ ਤੂ ਹੀ ਹੈਂ॥੭॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਪ੍ਰਭੂ! ਜੀਵਾਂ ਨੂੰ ਸੱਤਿਆ ਦੇਣ ਤੇ ਖੋਹ ਲੈਣ ਵਾਲਾ) ਇਕ ਤੂੰ ਹੀ ਹੈਂ ਇਕ ਤੂੰ ਹੀ ਹੈਂ ॥੭॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "porque sólo Él Es, sí, sólo Él.  (7)"