[[content]]
assets = ["DGDG", "DDTK"]
type = "primary"
data = "ਸਦੈਵੰ ਪ੍ਰਕਾਸੇ ॥"
page = 8
line = 7

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Salutation to Thee O Ever-Illumined Lord!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਸਦਾ ਪ੍ਰਕਾਸ਼ਿਤ ਰਹਿਣ ਵਾਲੇ!"

