[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮਾਈ; ਮੇਰੇ ਮਨ ਕੀ ਪਿਆਸ ॥"
page = 716
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "My mother, my mind thirsts for the Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰੀ ਮਾਤਾ, ਮੇਰੇ ਚਿੱਤ ਅੰਦਰ ਪ੍ਰਭੂ ਦੀ ਤ੍ਰੇਹ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O my mother, my mind is so thirsty."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ (ਮਾਈ) ਮਾਯਾ ਪਤੀ! ਮੇਰੇ ਮਨ ਮੇਂ ਤੌ ਏਕ ਤੇਰੇ ਦਰਸਨ ਕੀ ਪਿਆਸ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਮਾਂ! ਮੇਰੇ ਮਨ ਦੀ ਇਹ (ਪ੍ਰਭੂ ਦਰਸਨ ਦੀ) ਪਿਆਸ (ਸਦਾ ਟਿਕੀ ਰਹਿੰਦੀ ਹੈ)"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਾਈ = ਹੇ ਮਾਂ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Madre, tengo sed de Tu Amor;"