[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਅਪਨਾ ਕਹਿਆ; ਆਪਿ. ਨ ਕਮਾਵੈ ॥੧॥"
page = 887
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Thou Thyself practisest not what thou preachest."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਉਪਦੇਸ਼ ਤੂੰ ਦਿੰਦਾ ਹੈਂ, ਤੂੰ ਖੁਦ ਉਸ ਉਤੇ ਅਮਲ ਨਹੀਂ ਕਰਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "but you do not practice what you preach. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਅਪਨਾ ਕਹਿਆ ਹੂਆ ਉਪਦੇਸ ਆਪ ਨਹੀਂ ਕਮਾਵਤਾ ਹੈਂ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰ ਆਪਣਾ ਇਹ ਦੱਸਿਆ ਹੋਇਆ ਉਪਦੇਸ਼ ਆਪ ਨਹੀਂ ਕਮਾਂਦਾ (ਉਸ ਨੂੰ ਪੰਡਿਤ ਨਹੀਂ ਆਖਿਆ ਜਾ ਸਕਦਾ) ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pero él mismo no practica lo que enseña.(1)"