[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਰਿ ਕਿਰਪਾ; ਗੁਰਿ ਦੀਨੋ ਦਾਨੁ ॥"
page = 1149
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Guru has mercifully blessed Nanak with the gift,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮਿਹਰ ਧਾਰ ਕੇ ਗੁਰਾਂ ਨੇ ਨਾਨਕ ਨੂੰ ਦਾਤ ਪਰਦਾਨ ਕੀਤੀ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Guru, in His Mercy, has granted this Gift."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਗੁਰੋਂ ਨੇ ਕ੍ਰਿਪਾ ਕਰ ਕੇ ਹਮ ਕੋ ਦਾਨ ਦੀਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮਿਹਰ ਕਰ ਕੇ ਗੁਰੂ ਨੇ ਜਿਸ ਮਨੁੱਖ ਨੂੰ (ਨਾਮ ਦੀ) ਦਾਤ ਬਖ਼ਸ਼ੀ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਰਿ = ਗੁਰੂ ਨੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dice Nanak, cuando en Su Misericordia el Guru lo bendice a uno,"