[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਰੁਕਮਿਨੀ ਬਾਚ ॥"
page = 513

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of Rukmani:"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਰੁਕਮਨੀ ਨੇ ਕਿਹਾ:"