[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਉ ਜਾਨੈ; ਮੈ ਕਥਨੀ ਕਰਤਾ ॥"
page = 255
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "When he considers himself to be a preacher,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਦ ਉਹ ਆਪਣੇ ਆਪ ਨੂੰ ਪ੍ਰਚਾਰਕ ਖਿਆਲ ਕਰਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "When he believes himself to be a preacher,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੇਕਰ ਪੁਰਸ ਇਹ ਜਾਨ ਲੇਵੇ ਕਿ ਮੈਂ (ਕਥਨੀ) ਕਥਾ ਕਰਤਾ ਹੂੰ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਦੋਂ ਮਨੁੱਖ ਇਹ ਸਮਝ ਲੈਂਦਾ ਹੈ ਕਿ ਮੈਂ ਚੰਗੇ ਧਾਰਮਿਕ ਵਖਿਆਨ ਕਰ ਲੈਂਦਾ ਹਾਂ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El que piensa que habla muy bien,"