[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਠਾਕੁਰ ਚਰਣ ਸੁਹਾਵੇ ॥"
page = 407
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Beautiful are the feet of the Lord,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੁੰਦਰ ਹਨ ਸੁਆਮੀ ਦੇ ਪੈਰ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Feet of my Lord and Master are so Beautiful!"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਠਾਕੁਰ! ਤੇਰੇ ਚਰਣ (ਸੁਹਾਵੇ) ਸੋਭਨੀਕ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮਾਲਕ-ਪ੍ਰਭੂ ਦੇ ਚਰਨ ਸੋਹਣੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੁਹਾਵੇ = ਸੁਖ ਦੇਣ ਵਾਲੇ, ਸੋਹਣੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Benditos son los Pies del Maestro;"