[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੰਤਹੁ; ਰਾਮੁ ਜਪਤ ਸੁਖੁ ਪਾਇਆ ॥"
page = 629
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O saints, remembering the Lord, I have attained peace."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਸਾਧੂਓ! ਸਾਹਿਬ ਨੂੰ ਸਿਮਰ ਕੇ, ਮੈਂ ਸੁੱਖ ਪ੍ਰਾਪਤ ਕੀਤਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O Saints, meditating on the Lord, we obtain peace."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਸੰਤ ਜਨੋਂ! ਹਮਨੇ ਰਾਮ ਜਪ ਕਰ ਸੁਖ ਕੋ ਪਾਇਆ ਹੈ॥☬ਕੈਸੇ ਪਾਇਆ ਹੈ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਸੰਤ ਜਨੋ! ਪਰਮਾਤਮਾ ਦਾ ਨਾਮ ਜਪ ਕੇ ਉਹ ਮਨੁੱਖ ਆਤਮਕ ਸੁਖ ਮਾਣਦੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੰਤਹੁ = ਹੇ ਸੰਤ ਜਨੋ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Santos, contemplando al Señor, logré el Éxtasis;"