[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਕਾ ਨਾਮੁ; ਜਨ ਕਉ ਧਾਰੈ ॥"
page = 189
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "God's Name lends prop to His serf,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰੱਬ ਦਾ ਨਾਮ ਉਸ ਦੇ ਨਫ਼ਰ ਨੂੰ ਆਸਰਾ ਦਿੰਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Name of the Lord is the support of His humble servants."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹਰੀ ਕਾ ਜੋ ਨਾਮ ਹੈ ਤਿਸ ਨੇ ਜਨਕਾਦਿਕ ਉਧਾਰੇ ਹੈਂ; ਵਾ ਹਰੀ ਕੇ ਨਾਮ ਕਰ ਜਨਕ ਨੈ ਨਰਕ ਸੇ ਜੀਵੋਂ ਕਾ ਉਧਾਰ ਕੀਆ ਹੈ; ਵਾ ਹਰੀ ਕਾ ਨਾਮ ਹੀ ਜਨੋਂ ਕਾ ਆਸਰਾ ਰੂਪ ਹੈ"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰਮਾਤਮਾ ਦਾ ਨਾਮ (ਪਰਮਾਤਮਾ ਦੇ) ਸੇਵਕ ਨੂੰ ਸਹਾਰਾ ਦੇਂਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜਨ ਕਉ = ਸੇਵਕ ਨੂੰ। ਧਾਰੈ = ਧਾਰਦਾ ਹੈ, ਧਰਵਾਸ ਦੇਂਦਾ ਹੈ, ਸਹਾਰਾ ਦੇਂਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Nombre del Señor es el Soporte del Devoto,"