[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਦੂਜਾ ਭਾਉ ਕੁਦਾਉ ਹਰਾਵੈ ॥੧੯॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Having sense of duality is not a good conduct, and one always is defeated."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਦੂਜਾ ਭਾਉ ਖੋਟਾ ਭਾਉ ਹੈ (ਇਸ ਨਾਲ) ਹਾਰ ਹੀ ਆਉਂਦੀ ਹੈ।"