[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਜੇਕਰ ਤੂੰ ਆਪਣੀ ਹਿਰਸ ਹਵਸ ਤੋਣ ਭੱਜਨ ਦੀ ਇੱਛਾ ਰਖਦਾ ਹੈਣ #"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਅਜ਼ ਖ਼ੁਦ ਹਵਸ ਮੈਲਿ ਰਮੀਦਨ ਦਾਰੀ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "The Almighty God has also said,"