[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਦਾ ਸਿਧ ਦਾ ਬੁਧ ਦਾ ਬ੍ਰਿਧ ਕਰਤਾ ॥"
page = 4
line = 4

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Thou art the Giver of riches and wisdom and Promoter."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਸਦਾ ਸਿੱਧੀ ਦੇਣ ਵਾਲੇ, ਬੁੱਧੀ ਦੇਣ ਵਾਲੇ ਅਤੇ ਵਾਧਾ ਕਰਨ ਵਾਲੇ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਸਦਾ ਸਿੱਧਦਾ ਬੁੱਧਦਾ; ਬ੍ਰਿੱਧ ਕਰਤਾ ॥"