[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਏਕ ਨਾਮ ਲੇ; ਮਨਹਿ ਪਰੋਊ ॥"
page = 253
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "who takes the One Name in his heart."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਇਕ ਨਾਮ ਨੂੰ ਲੈ ਕੇ, ਆਪਣੇ ਦਿਲ ਅੰਦਰ ਪਰੋ ਲੈਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Does not have to take birth again."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਏਕ ਪਰਮੇਸ੍ਵਰ ਕੇ ਨਾਮ ਕੋ ਲੈਕਰ ਮਨ ਮੇਂ ਪਰੋਇ ਰਖਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇਹੜਾ ਬੰਦਾ ਇਕ ਪ੍ਰਭੂ ਦਾ ਨਾਮ ਲੈ ਕੇ ਆਪਣੇ ਮਨ ਵਿਚ ਪ੍ਰੋ ਲੈਂਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਨਹਿ = ਮਨ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "no vuelve a regresar a ningún vientre."