[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਹਿਓ ਪ੍ਰਭੂ ਸੁ ਮੈ ਕਰੋਂ ॥੩੬॥"
page = 58

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "I do not pay attention to anyone else, all my actions are at the bidding of the Lord.36."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਜੋ ਪ੍ਰਭੂ ਨੇ ਕਿਹਾ ਹੈ, ਉਹੀ ਕਰਾਂਗਾ ॥੩੬॥"