[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਚੌਪਈ ॥"
page = 288

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "CHAUPAI"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੂੰ ਕਿਸੇ ਤਰ੍ਹਾਂ ਦਾ ਕੋਈ ਤੋਟਾ ਨਹੀਂ ॥੮੪੨॥"