[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਮੰਤ੍ਰੀ ਬਾਚ ॥"
page = 688

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Speech of the minister"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਮੰਤਰੀ ਨੇ ਕਿਹਾ -"