[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਸਤਿਗੁਰ ਬਿਨਾ, ਨ ਸੋਝੀ ਪਾਈ ॥੯॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Without true Guru this understanding cannot be attained."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਸੂਝ ਸਤਿਗੁਰੂ ਬਿਨਾ ਕਿਸੇ ਨੇ ਨਹੀਂ ਪਾਈ।"