[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਤਿਗੁਰੁ ਸਿਖ ਕੀ; ਕਰੈ ਪ੍ਰਤਿਪਾਲ ॥"
page = 286
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The True Guru cherishes his disciple."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੱਚੇ ਗੁਰੂ ਜੀ ਆਪਣੇ ਮੁਰੀਦ ਦੀ ਪਾਲਣਾ ਪੋਸਣਾ ਕਰਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The True Guru cherishes His Sikh."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸਤਿਗੁਰ ਸਿਖ ਕੀ ਪ੍ਰਤਿਪਾਲਨਾ ਕਰਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸਤਿਗੁਰੂ ਸਿੱਖ ਦੀ ਰੱਖਿਆ ਕਰਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪ੍ਰਤਿਪਾਲ = ਰੱਖਿਆ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Verdadero Guru sostiene al Discípulo, siempre se muestra Bondadoso con él."