[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਾਮ ਤੁਪਕ ਕੇ ਹੋਤ ਹੈ; ਲੀਜੋ ਸਮਝ ਪ੍ਰਬੀਨ ॥੧੧੧੭॥"
page = 789

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Saying the word “Vaahini” and adding the word “Shatru” at the end, O wise men! the names of Tupak are formed.1117."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਇਸ ਨੂੰ) ਸਭ ਪ੍ਰਬੀਨੋ, ਤੁਪਕ ਦਾ ਨਾਮ ਸਮਝ ਲਵੋ ॥੧੧੧੭॥"