[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਿਸੁ ਜਨ ਕੀ; ਤੂ ਸੇਵਾ ਲਾਗੁ ॥"
page = 286
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Attach thyself to the service of that slave."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੁਆਮੀ ਦੇ ਉਸ ਗੋਲੇ ਦੀ ਟਹਿਲ ਅੰਦਰ ਆਪਣੇ ਆਪ ਨੂੰ ਜੋੜ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "and enjoin yourself to the service of those servants."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸ ਜਨ ਕੀ ਸੇਵਾ ਮੇਂ ਤੂੰ ਲਾਗ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤੇ ਉਸ ਸੇਵਕ ਦੀ ਸੇਵਾ ਵਿਚ ਜੁੱਟ ਪਉ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y conviértete en Devoto al servicio de aquéllos que a Él sirven."