[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ # ਕੀ ਤੈਨੂੰ ਪਤਾ ਹੈ ਕਿ ਰੱਬ ਦੀ ਯਾਦ ਕੀ ਹੁੰਦੀ ਹੈ#"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਐ ਬਰਾਦਰ ਯਾਦਿ ਹੱਕ ਦਾਨੀ ਕਿ ਚੀਸਤ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Great is the true Guru who has, blind minds like mine,"