[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਵਜੇ ਢੋਲ ਨਗਾਰੇ, ਦਲਾਂ ਮੁਕਾਬਲਾ ॥"
page = 122

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The drums and trumpets have sounded and the armies have attacked each other."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਢੋਲ ਅਤੇ ਨਗਾਰੇ ਵਜੇ ਅਤੇ ਦਲਾਂ ਦਾ ਮੁਕਾਬਲਾ ਸ਼ੁਰੂ ਹੋ ਗਿਆ।"