[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਹੇ ਅਕਾਲ ਪੁਰਖ # ਇਸ ਬੰਦੇ (ਸੇਵਕ) ਦਾ ਸਹਾਈ ਹੋ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਯਾ ਇਲਾਹੀ ਯਾਵਰੀ ਕੁਨ ਬੰਦਾ ਰਾ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "O Waaheguru! Kindly help this person, yours truly,"