[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਜ਼ਾਹਰ ਜ਼ਹੂਰ ਹੈਂ ॥"
page = 8
line = 11

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Thou art visible illumination!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਹੇ ਪ੍ਰਭੂ!) ਤੂੰ ਪ੍ਰਗਟ ਰੂਪ ਵਿਚ ਪ੍ਰਕਾਸ਼ਮਾਨ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਕਿ, ਜਾਹਰ ਜਹੂਰ ਹੈਂ ॥"