[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪਰੇਤਹੁ ਕੀਤੋਨੁ ਦੇਵਤਾ; ਤਿਨਿ ਕਰਣੈਹਾਰੇ ॥"
page = 323
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He the Creator has transformed the ghost into an angel."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਸ ਸਿਰਜਣਹਾਰ ਨੇ ਭੂਤ ਨੂੰ ਫਰਿਸ਼ਤਾ ਬਣਾ ਦਿਤਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The ghost has been transformed into an angel by the Creator Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸ ਕਰਨੇ ਹਾਰ ਵਾਹਗੁਰੂ ਨੇ ਪ੍ਰੇਤ ਸੇ ਦੇਵਤਾ ਕੀਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਸਿਰਜਣਹਾਰ ਨੇ (ਨਾਮ ਦੀ ਦਾਤਿ ਦੇ ਕੇ ਜੀਵ ਨੂੰ) ਪ੍ਰੇਤ ਤੋਂ ਦੇਵਤਾ ਬਣਾ ਦਿੱਤਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਰਤੇਹੁ = ਪਰੇਤ ਤੋਂ, ਭੂਤ ਤੋਂ। ਕੀਤੋਨੁ = ਉਸ ਨੇ ਬਣਾ ਦਿੱਤਾ। ਤਿਨਿ = ਉਸ ਨੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dios, el Creador, nos ha transformado de fantasmas en ángeles,"