[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਤਾ ਕੋ ਹਨੋ ਆਜ ਯੌ ਭਾਖੀ ॥੧੨॥"
page = 1182

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੂੰ ਅਜ ਹੀ ਮਾਰ ਦਿਓ, ਇਸ ਤਰ੍ਹਾਂ ਕਹਿਣ ਲਗੀ ॥੧੨॥"