[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਰਬ ਮੰਗਲਾ ਕੋ ਸਿਰ ਨਯਾਵੈ ॥੫॥"
page = 917

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "They would recite Sundry songs to appease goddess, Mangal.(5)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਸਰਬ ਮੰਗਲਾ (ਦੇਵੀ) ਨੂੰ ਸਿਰ ਨਿਵਾਉਂਦੇ ਸਨ ॥੫॥"