[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੋ ਇਸੁ ਮਾਰੇ; ਸੋ ਪਤਿਵੰਤਾ ॥"
page = 238
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He, who kills it, becomes worthy of honour."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਹੜਾ ਇਸ ਨੂੰ ਨਸ਼ਟ ਕਰ ਦਿੰਦਾ ਹੈ, ਉਹ ਇੱਜਤ ਵਾਲਾ ਹੋ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "One who kills this is honorable."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਔਰ ਜੋ ਇਸ ਕੋ ਮਾਰੇ ਸੋਈ ਪਤ ਵਾਲਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇਹੜਾ ਮਨੁੱਖ ਇਸ (ਮੇਰ-ਤੇਰ ਨੂੰ) ਮੁਕਾ ਲੈਂਦਾ ਹੈ, ਉਹ ਇੱਜ਼ਤ ਵਾਲਾ ਹੋ ਜਾਂਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਤਿ = ਇੱਜ਼ਤ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y honorable."