[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕੀਨੇ ਕਰਮ ਅਨੇਕ; ਗਵਾਰ ਬਿਕਾਰ ਘਨ ॥"
page = 1363
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The unwise one commits several misdeeds and good many sins."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਬੇਅਕਲ ਬੰਦਾ ਅਨੇਕਾਂ ਕੁਕਰਮ ਅਤੇ ਘਦੇਰੇ ਪਾਪ ਕਮਾਉਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The fool commits countless foolish actions and so many sinful mistakes."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਸ ਜੀਵ ਗਵਾਰ ਨੇ ਜਿਸ ਸਰੀਰ ਕੇ ਵਾਸਤੇ ਅਧਿਕ ਵਿਕਾਰ ਰੂਪ ਅਨੇਕ ਕਰਮ ਕੀਏ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮੂਰਖ ਮਨੁੱਖ ਅਨੇਕਾਂ ਹੀ ਕੁਕਰਮ ਕਰਦਾ ਰਹਿੰਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗਵਾਰ = ਮੂਰਖ। ਘਨ = ਬਹੁਤ। ਕਰਮ ਬਿਕਾਰ = ਵਿਕਾਰਾਂ ਦੇ ਕੰਮ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El tonto comete tantos errores malvados y faltas,"