[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰ ਪੂਰੇ ਤੇ; ਪਾਇਆ ਜਾਈ ॥"
page = 1176
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "who is obtained through the Perfect Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਪੂਰਨ ਗੁਰਾਂ ਦੇ ਰਾਹੀਂ ਪਰਾਪਤ ਹੁੰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Through the Perfect Guru, it is obtained."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਵਹੁ ਰਾਮ ਨਾਮ ਪੂਰੇ ਗੁਰੋਂ ਸੇ ਪਾਯਾ ਜਾਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਹ ਨਾਮ ਪੂਰੇ ਗੁਰੂ ਪਾਸੋਂ ਹੀ ਮਿਲਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤੇ = ਤੋਂ, ਦੀ ਰਾਹੀਂ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pero es a través del Guru Perfecto que uno lo obtiene."