[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਬਿਖਿਆ ਕਾ; ਸਭੁ ਧੰਧੁ ਪਸਾਰੁ ॥"
page = 1145
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "All the strifes are but the extension of mammon."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਾਰੇ ਬਖੇੜੇ, ਨਿਰੇ ਪੁਰੇ ਮਾਇਆ ਦਾ ਹੀ ਖਿਲਾਰਾ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "All of his conflicts are extensions of his corruption."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੰਪੂਰਨ ਧੰਧਾ ਬਿਸ੍ਯੋਂ ਕਾ ਪਸਾਰਾ ਹੂਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਜਗਤ ਵਿਚ) ਮਾਇਆ ਦਾ ਹੀ ਸਾਰਾ ਧੰਧਾ ਹੈ, ਮਾਇਆ ਦਾ ਹੀ ਸਾਰਾ ਖਿਲਾਰਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਬਿਖਿਆ = ਮਾਇਆ। ਧੰਧੁ = ਖਲਜਗਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Todo el problema viene por estar involucrado con Maya, la ilusión,"