[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਹੁ ਨਾਨਕ; ਭਲਾ ਮੇਰਾ ਕਰਮ ॥"
page = 191
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Says Nanak, auspicious is my fortune,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਜੀ ਆਖਦੇ ਹਨ ਮੁਬਾਰਕ ਹੈ ਮੇਰੀ ਕਿਸਮਤ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Says Nanak, auspicious is my karma,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਮੇਰਾ ਓਹ ਕਰਮੁ ਭਲਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਨਾਨਕ ਆਖਦਾ ਹੈ- ਮੇਰੇ ਵੱਡੇ ਭਾਗ (ਜਾਗ ਪੈਂਦੇ ਹਨ)"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਰਮ = ਭਾਗ, ਕਿਸਮਤਿ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Dice Nanak, Bendito, oh Bendito es mi Destino,"