[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਸੱਚ ਕੀ ਹੈ# ਉਸ ਪਾਕ ਪਰਵਰਦਗਾਰ ਦੀ ਯਾਦ ਹੀ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਕਹ ਚਿਹ ਬਾਸ਼ਦ ਯਾਦਿ ਆਣ ਯਜ਼ਦਾਨਿ ਪਾਕ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Akaalpurakh abides in every limb of our bodies,"