[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਅਸਟਪਦੀ ॥"
page = 274
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Ashtpadi."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਸ਼ਟਪਦੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Ashtapadee:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ashtapadi IX"