[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਯਕੇ ਪਿਸਰ ਓ ਬੂਦ ਹੁਸਨੁਲ ਜਮਾਲ ॥"
page = 1424

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He had a son who excelled in handsomeness,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਦਾ ਇਕ ਬਹੁਤ ਸੁੰਦਰ ਪੁੱਤਰ ਸੀ"