[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਉਤਰਿ ਜਾਇ; ਤੇਰੇ ਮਨ ਕੀ ਪਿਆਸ ॥"
page = 179
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Thy mind 's thirst shall be quenched."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਮਨੂਏ ਦੀ ਤਿਹ ਬੁਝ ਜਾਵੇਗੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The thirst of your mind shall be quenched,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਮਨ ਕੀ ਤ੍ਰਿਸਨਾ ਲਹਿ ਜਾਵੇਗੀ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਨਾਮ ਦੀ ਬਰਕਤਿ ਨਾਲ) ਤੇਰੇ ਮਨ ਦੀ (ਮਾਇਆ ਦੀ) ਤ੍ਰਿਸ਼ਨਾ ਲਹਿ ਜਾਏਗੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "La sed del hombre es saciada,"