// Generated by brand/scripts/generate-icons.mjs — do not edit.
// Source of truth: brand/icons.md

import UIKit

/// Icon names shared with the Android app, keyed by what they *mean* rather than by
/// what they look like. Use `Image(systemName: AppIcons.zoom)`.
///
/// Availability is checked at generation time against IPHONEOS_DEPLOYMENT_TARGET,
/// so a symbol newer than the target cannot reach a build without a declared
/// fallback. `resolve` handles the remaining case: a device running an OS older
/// than the symbol, where `UIImage(systemName:)` returns nil and SwiftUI draws
/// nothing at all rather than complaining.
enum AppIcons {
  private static func resolve(_ preferred: String, fallback: String) -> String {
    UIImage(systemName: preferred) != nil ? preferred : fallback
  }

  /// Open the Journeys sidebar. Specified by the author.
  /// SF Symbols, iOS 17.0+.
  static let journeys = "point.bottomleft.forward.to.point.topright.scurvepath"

  /// Journeys sidebar is open; tapping returns to the viewer. Same shape, filled.
  /// SF Symbols, iOS 17.0+.
  static let journeysActive = "point.bottomleft.forward.to.point.topright.scurvepath.fill"

  /// Open the Controls sidebar.
  /// Lucide `sliders-horizontal` — an asset, not an SF Symbol.
  static let controls = "sliders-horizontal"

  /// Controls sidebar is open. PROPOSED, as above.
  /// Lucide `sliders-horizontal` — an asset, not an SF Symbol.
  static let controlsActive = "sliders-horizontal"

  /// Font size of the reading area. Specified by the author.
  /// SF Symbols, iOS 13.0+.
  static let zoom = "plus.magnifyingglass"

  /// Secondary text size relative to the Gurmukhi line. Specified by the author.
  /// SF Symbols, iOS 13.0+.
  static let ratio = "textformat.size"

  /// Font weight. Specified by the author.
  /// SF Symbols, iOS 14.0+.
  static let weight = "lineweight"

  /// Reading column width. Wide surfaces only. PROPOSED — not specified.
  /// SF Symbols, iOS 13.0+.
  static let width = "arrow.left.and.right"

  /// Rendering mode: classic / saral / reader / presenter. Specified by the author.
  /// SF Symbols, iOS 13.0+.
  static let mode = "eyeglasses"

  /// Centre the text. Specified by the author.
  /// SF Symbols, iOS 13.0+.
  static let centered = "text.aligncenter"

  /// Larivaar — remove spaces from the Gurmukhi line. Specified by the author.
  /// SF Symbols, iOS 16.0+.
  static let continuous = "space"

  /// Colour vishraam words. Specified by the author.
  /// SF Symbols, iOS 13.0+.
  static let pauses = "pause.fill"

  /// Transliteration schemes, computed by packages/gurmukhi. Specified by the author.
  /// SF Symbols, iOS 15.0+.
  static let pronunciations = "person.wave.2"

  /// Translation languages. Specified by the author.
  /// SF Symbols, iOS 17.4+.
  static let translations = "translate"

  /// Light / dark / auto. Specified by the author.
  /// SF Symbols, iOS 14.0+.
  static let appearance = "sleep"

  /// Filter in All recents: All / Pinned / Recent / Inactive. PROPOSED.
  /// SF Symbols, iOS 15.0+.
  static let filter = "line.3.horizontal.decrease"

  /// Trailing chevron on the All recents row. PROPOSED.
  /// SF Symbols, iOS 14.0+.
  static let disclosure = "chevron.forward"

  /// The Collections row, pinned below Recents. PROPOSED — destination undefined.
  /// SF Symbols, iOS 14.0+.
  static let collections = "books.vertical"

  /// About Shabad OS — links, social, feedback. PROPOSED.
  /// SF Symbols, iOS 13.0+.
  static let about = "info.circle"

  /// Search. PROPOSED — the shell has no specified entry point yet.
  /// SF Symbols, iOS 13.0+.
  static let search = "magnifyingglass"

  /// Pin a journey. PROPOSED.
  /// SF Symbols, iOS 13.0+.
  static let pin = "pin"

  /// Pinned state. PROPOSED.
  /// SF Symbols, iOS 13.0+.
  static let pinned = "pin.fill"

  /// Rename a journey. PROPOSED.
  /// SF Symbols, iOS 13.0+.
  static let rename = "pencil"

  /// Move an entry to a journey's Removed section. Not a delete. PROPOSED.
  /// SF Symbols, iOS 13.0+.
  static let remove = "minus.circle"

  /// Restore a removed entry to its original position. PROPOSED.
  /// SF Symbols, iOS 14.0+.
  static let undo = "arrow.uturn.backward"

  /// Share a journey — a bookmark position, or a Defined journey. PROPOSED.
  /// SF Symbols, iOS 13.0+.
  static let share = "square.and.arrow.up"

  /// Next entry in a journey. PROPOSED.
  /// SF Symbols, iOS 14.0+.
  static let next = "chevron.forward"

  /// Previous entry in a journey. PROPOSED.
  /// SF Symbols, iOS 14.0+.
  static let previous = "chevron.backward"

  /// Consecutive days with a complete Defined instance. PROPOSED.
  /// SF Symbols, iOS 13.0+.
  static let streak = "flame"

  /// Advanced settings, one level beyond the Controls sidebar. PROPOSED.
  /// SF Symbols, iOS 14.0+.
  static let settings = "gearshape"

  /// Return from Settings to the Controls sidebar. PROPOSED.
  /// SF Symbols, iOS 14.0+.
  static let back = "chevron.backward"

  /// Close a tab. Removes it from the journey permanently; the timeline keeps it. PROPOSED.
  /// SF Symbols, iOS 13.0+.
  static let close = "xmark"

  /// A tracked collection or bookmark. PROPOSED.
  /// SF Symbols, iOS 15.0+.
  static let tracked = "chart.line.uptrend.xyaxis"
}
