import Foundation
import Gurmukhi

/// A line of gurbani. `id` is the corpus line id and is stable across corpus
/// versions — see docs/requirements/data-model.md. Nothing here addresses a line
/// by its position.
struct Line: Decodable, Identifiable {
  let id: String

  /// The corpus text, vishraam markers included. Kept because the markers are the
  /// *input* to pause colouring, which needs their positions — stripping is not the
  /// only thing they are for.
  let source: String

  /// What is displayed. Vishraam markers (`.` `,` `;`) are editorial notation marking
  /// where a reciter pauses; they are not part of the scripture and are **stripped
  /// whether or not pause colouring is on**
  /// (docs/requirements/display-controls.md). 1,023 of the 1,935 bundled lines carry
  /// at least one, so this is not an edge case — without it the reader shows
  /// `ਨਿਰਵੈਰੁ;` on screen.
  ///
  /// Done once at decode rather than per render, and via `packages/gurmukhi` rather
  /// than a local `replacingOccurrences` so iOS and Android cannot disagree about
  /// what a marker is.
  let gurmukhi: String

  private enum CodingKeys: String, CodingKey {
    case id
    case gurmukhi
  }

  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    id = try container.decode(String.self, forKey: .id)
    source = try container.decode(String.self, forKey: .gurmukhi)
    gurmukhi = remove(input: source, features: vishraams())
  }
}

struct Bani: Decodable, Identifiable {
  let id: String
  let name: [String: String]
  /// Sections are the bani's own grouping, not the source's structure.
  let sections: [[Line]]

  var latin: String { name["Latn"] ?? id }
  var gurmukhi: String { name["Guru"] ?? "" }
}

/// A bani flattened into one addressable sequence.
///
/// The reader needs stable, unique ids per row so the scroll position can be
/// anchored to a specific line while the type size changes. Nested `ForEach`es keyed
/// on array offsets cannot provide that — the ids repeat across sections.
struct ReaderItem: Identifiable {
  enum Kind {
    case line(String)
    case divider
  }

  let id: String
  let kind: Kind
}

extension Bani {
  var items: [ReaderItem] {
    sections.enumerated().flatMap { sectionIndex, section -> [ReaderItem] in
      let lines = section.enumerated().map { lineIndex, line in
        ReaderItem(id: "\(sectionIndex).\(lineIndex)", kind: .line(line.gurmukhi))
      }
      let isLast = sectionIndex == sections.count - 1
      return isLast ? lines : lines + [ReaderItem(id: "d\(sectionIndex)", kind: .divider)]
    }
  }
}

enum Corpus {
  /// Generated by `bun run database:export-bundled` in `database/`.
  /// Never hand-edited: scripture edits go through the database component.
  static let banis: [Bani] = {
    guard let url = Bundle.main.url(forResource: "banis", withExtension: "json"),
      let data = try? Data(contentsOf: url)
    else {
      // A missing bundled corpus is a build configuration error, not a runtime
      // condition to degrade through — fail where it is visible.
      fatalError("banis.json missing from bundle. Run `bun run database:export-bundled`.")
    }
    struct Payload: Decodable { let banis: [Bani] }
    return try! JSONDecoder().decode(Payload.self, from: data).banis
  }()
}
