// Generated by brand/scripts/generate-tokens.mjs — do not edit.
// Source of truth: brand/tokens.json

import SwiftUI
import UIKit

/// Colour and type shared with the Android app. A UIColor provider is used rather
/// than reading `@Environment(\.colorScheme)` so the value resolves itself —
/// including inside UIKit-backed views that never see the SwiftUI environment.
enum DesignTokens {
  /// light-dark(#f4f1ee, #000000)
  static let background = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.0000, green: 0.0000, blue: 0.0000, alpha: 1)
      : UIColor(red: 0.9569, green: 0.9451, blue: 0.9333, alpha: 1)
  })

  /// light-dark(#ffffff, #222222)
  static let backgroundBase = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.1333, green: 0.1333, blue: 0.1333, alpha: 1)
      : UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)
  })

  /// light-dark(#23211f, #ffffff)
  static let foreground = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)
      : UIColor(red: 0.1373, green: 0.1294, blue: 0.1216, alpha: 1)
  })

  /// light-dark(#575552, #bebebe)
  static let foregroundMuted = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.7451, green: 0.7451, blue: 0.7451, alpha: 1)
      : UIColor(red: 0.3412, green: 0.3333, blue: 0.3216, alpha: 1)
  })

  /// light-dark(#2381e0, #3c96f7)
  static let ui = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.2353, green: 0.5882, blue: 0.9686, alpha: 1)
      : UIColor(red: 0.1373, green: 0.5059, blue: 0.8784, alpha: 1)
  })

  static let tonerOpacity: Double = 0.08

  static let defaultSize: Double = 20
  static let minSize: Double = 14
  static let maxSize: Double = 56

  /// Total line box as a multiple of font size, so it holds when zoomed.
  /// Gurmukhi stacks vowel signs above and below the base line; at 1.0 the lagaa
  /// matraa collide with the line above.
  static let lineHeightRatio: Double = 1.2

  static func clamp(_ size: Double) -> Double {
    min(maxSize, max(minSize, size))
  }

  /// SwiftUI's `lineSpacing` is *extra* space on top of the font's natural line
  /// height, not the total line box, so the target has to be measured against the
  /// real font metrics. Android's `lineHeight` is the total directly.
  static func lineSpacing(for size: Double, fontName: String) -> Double {
    let natural = UIFont(name: fontName, size: size)?.lineHeight ?? size * 1.2
    return max(0, size * lineHeightRatio - natural)
  }
}
