// Generated by packages/design/scripts/generate-tokens.mjs — do not edit.
// Source of truth: packages/design/tokens.md

import SwiftUI
import UIKit

/// Colour and type shared with the Android app. A UIColor provider is used rather
/// than reading `@Environment(\.colorScheme)` so the value resolves itself —
/// including inside UIKit-backed views that never see the SwiftUI environment.
enum DesignTokens {
  /// light-dark(#f4f1ee, #000000)
  static let background = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.0000, green: 0.0000, blue: 0.0000, alpha: 1)
      : UIColor(red: 0.9569, green: 0.9451, blue: 0.9333, alpha: 1)
  })

  /// light-dark(#ffffff, #222222)
  static let backgroundBase = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.1333, green: 0.1333, blue: 0.1333, alpha: 1)
      : UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)
  })

  /// light-dark(#23211f, #ffffff)
  static let foreground = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)
      : UIColor(red: 0.1373, green: 0.1294, blue: 0.1216, alpha: 1)
  })

  /// light-dark(#575552, #bebebe)
  static let foregroundMuted = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.7451, green: 0.7451, blue: 0.7451, alpha: 1)
      : UIColor(red: 0.3412, green: 0.3333, blue: 0.3216, alpha: 1)
  })

  /// light-dark(#2381e0, #3c96f7)
  static let ui = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.2353, green: 0.5882, blue: 0.9686, alpha: 1)
      : UIColor(red: 0.1373, green: 0.5059, blue: 0.8784, alpha: 1)
  })

  /// light-dark(#8a472a, #ffd493)
  static let vishraamHeavy = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 1.0000, green: 0.8314, blue: 0.5765, alpha: 1)
      : UIColor(red: 0.5412, green: 0.2784, blue: 0.1647, alpha: 1)
  })

  /// light-dark(#13662b, #c4eda8)
  static let vishraamMedium = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.7686, green: 0.9294, blue: 0.6588, alpha: 1)
      : UIColor(red: 0.0745, green: 0.4000, blue: 0.1686, alpha: 1)
  })

  /// light-dark(#5e438e, #decbff)
  static let vishraamLight = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(red: 0.8706, green: 0.7961, blue: 1.0000, alpha: 1)
      : UIColor(red: 0.3686, green: 0.2627, blue: 0.5569, alpha: 1)
  })

  static let tonerOpacity: Double = 0.04

  static let weightPrimary: Double = 550
  static let weightLatin: Double = 475
  static let weightSecondary: Double = 440

  static let ratioDefault: Double = 0.6

  static let defaultSize: Double = 20
  static let minSize: Double = 14
  static let maxSize: Double = 56

  /// Total line box as a multiple of font size, so it holds when zoomed.
  /// Gurmukhi stacks vowel signs above and below the base line; at 1.0 the lagaa
  /// matraa collide with the line above.
  static let lineHeightRatio: Double = 1.2

  static func clamp(_ size: Double) -> Double {
    min(maxSize, max(minSize, size))
  }

  /// SwiftUI's `lineSpacing` is *extra* space on top of the font's natural line
  /// height, not the total line box, so the target has to be measured against the
  /// real font metrics. Android's `lineHeight` is the total directly.
  static func lineSpacing(for size: Double, fontName: String) -> Double {
    let natural = UIFont(name: fontName, size: size)?.lineHeight ?? size * 1.2
    return max(0, size * lineHeightRatio - natural)
  }
}
