[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਨਰਮੀ ਦਾ ਭਾਵ ਨਿਮਰਤਾ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਮਾਅਨੀਏ ਨਰਮੀ ਗ਼ਰੀਬੀ ਆਮਦਾ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "This body of yours is radiant because of the splendor of Akaalpurakh,"