[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿਸੂ ਨ ਕਾਨ ਰਾਖਿ ਹੋਂ ॥"
page = 58

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "I say only that which the Lord hath said, I do not yield to anyone else."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕਿਸੇ ਦੀ ਵੀ ਪਰਵਾਹ ਨਹੀਂ ਰਖਾਂਗਾ।"