[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਸ ਦਾ ਧਰਮ ਹਰ ਧਰਮ ਨਾਲੋਂ ਵਧੇਰੇ ਵਡਭਾਗੀ ਅਤੇ ਨੇਕ ਹੈ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਜ਼ਿ ਹਰ ਕੇਸ਼ ਫ਼ਰਖ਼ੰਦਾ-ਤਰ ਕੇਸ਼ਿ ਊ ॥੩੫॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "And, His belief and faith are much more fortunate and sublime than every other religion. (35)"