[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਮ ਸੁਪਨੈ ਕੈ; ਇਹੁ ਜਗੁ ਜਾਨੁ ॥"
page = 1187
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Know thou that this world is like a dream."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਜਾਣ ਲੈ ਕਿ ਇਹ ਸੰਸਾਰ ਸੁਫਨੇ ਵਰਗਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "You must realize that this world is nothing more than a dream."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਸ ਸੰਸਾਰ ਕੋ ਸੁਪਨੇ ਕੇ ਸਮਾਨ ਮਿਥ੍ਯਾ ਜਾਨ ਲੇ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਸ ਜਗਤ ਨੂੰ ਸੁਪਨੇ (ਵਿਚ ਵੇਖੇ ਪਦਾਰਥਾਂ) ਦੇ ਬਰਾਬਰ ਸਮਝ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਮ = ਬਰਾਬਰ। ਜਾਨੁ = ਸਮਝ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Considera que este mundo no es más que un sueño,"