[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਾੜਾ ਅੰਦੇਸਾ. ਕਿਉ ਕੀਜੈ; ਜਾ. ਨਾਹੀ ਅਧਰਮਿ ਮਾਰਦਾ ॥"
page = 90
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Why should we feel burning and anxiety when the Lord punishes not without justification?"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਸੀਂ ਕਿਉਂ ਸਾੜਾ ਤੇ ਫਿਕਰ ਮਹਿਸੂਸ ਕਰੀਏ ਜਦ ਸੁਆਮੀ ਕੋਈ ਅਨਿਆਈ ਦੰਡ ਨਹੀਂ ਦਿੰਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Why should we feel any burning anxiety, since the Lord does not punish without just cause?"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਬ ਅਧਰਮ ਕਰ ਕੇ ਨਹੀਂ ਮਾਰਦਾ ਹੈ ਤਬ (ਕਾੜਾ) ਝੋਰਾ (ਅੰਦੇਸਾ) ਸੰਸਾ ਕਿਉਂ ਕਰੀਏ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇ (ਇਹ ਭਰੋਸਾ ਹੋਵੇ ਕਿ) ਪ੍ਰਭੂ ਅਨਿਆਉਂ ਨਾਲ ਨਹੀਂ ਮਾਰਦਾ, ਤਾਂ ਕੋਈ ਫ਼ਿਕਰ ਡਰ ਨਹੀਂ ਰਹਿੰਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਾੜਾ = ਝੋਰਾ, ਫ਼ਿਕਰ। ਅੰਦੇਸਾ = ਡਰ। ਅਧਰਮਿ = ਅਨਿਆਉਂ ਨਾਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "¿Por qué tener miedo o duda cuando Él nunca es injusto?"