[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਤਿਗੁਰ ਵਿਚਿ; ਵਡੀ ਵਡਿਆਈ ॥"
page = 361
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Great is the greatness of the True Guru,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਵਿਸ਼ਾਲ ਹੈ ਵਿਸ਼ਾਲਤਾ ਸੱਚੇ ਗੁਰਾਂ ਦੀ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Great is the greatness of the True Guru;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਏਹ ਵੱਡੀ ਵਡਿਆਈ ਸਤਿਗੁਰੋਂ ਮੇਂ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ!) ਸਤਿਗੁਰੂ ਵਿਚ ਇਹ ਵੱਡਾ ਭਾਰਾ ਗੁਣ ਹੈ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Verdadero Guru es un Tesoro de Gloria;"