[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤ੍ਰਿਲੋਚਨ; ਗੁਰ ਮਿਲਿ ਭਈ ਸਿਧਿ ॥"
page = 1192
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Meeting with the Guru, Tirlochan attained perfection."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗੁਰਾਂ ਨਾਲ ਮਿਲ ਕੇ ਤ੍ਰਿਲੋਚਨ ਨੂੰ ਪੂਰਨਤਾ ਪਰਾਪਤ ਹੋ ਗਈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Meeting with the Guru, Trilochan attained the perfection of the Siddhas."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤ੍ਰਿਲੋਚਨ ਜੀ ਕੋ ਭੀ ਗੁਰੂ ਮਿਲਨੇ ਸੇ ਸਿਧੀ ਹੋਤੀ ਭਈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਨੂੰ ਮਿਲ ਕੇ ਤ੍ਰਿਲੋਚਨ ਨੂੰ ਭੀ ਆਤਮਕ ਜੀਵਨ ਵਿਚ ਸਫਲਤਾ ਪ੍ਰਾਪਤ ਹੋਈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਰ ਮਿਲਿ = ਗੁਰੂ ਨੂੰ ਮਿਲ ਕੇ। ਸਿਧਿ = (ਆਤਮਕ ਜੀਵਨ ਵਿਚ) ਸਫਲਤਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y Trilochan también encontró la Plenitud,"