[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਏਕਾ ਟੇਕ; ਰਖਹੁ ਮਨ ਮਾਹਿ ॥"
page = 293
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Put the prop of One Lord within thy mind."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਇਕ ਪ੍ਰਭੂ ਦਾ ਆਸਰਾ ਆਪਣੇ ਚਿੱਤ ਅੰਦਰ ਰੱਖ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Keep the Support of the One in your mind."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਬ ਤਿਸ ਏਕ ਕੀ ਹੀ ਟੇਕ ਮਨ ਮੇਂ ਰਾਖੋਗੇ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮਨ ਵਿਚ ਇਕ ਅਕਾਲ ਪੁਰਖ ਦਾ ਆਸਰਾ ਰੱਖੋ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y cesará para siempre tu deambular sin rumbo. Mantenlo a El siempre en tu mente,"