[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਨਕ; ਨਾਮ ਵਿਟਹੁ ਕੁਰਬਾਣੁ ॥"
page = 349
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Unto the Lord's Name, O Nanak, I am a sacrifice."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਾਈਂ ਦੇ ਨਾਮ ਉਤੋਂ ਨਾਨਕ ਘੋਲੀ ਵੰਞਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Nanak is a sacrifice to the Naam, the Name of the Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹਮ ਤੋ ਤਿਸ ਕੇ ਨਾਮ ਕੇ ਊਪਰੋਂ ਬਲਿਹਾਰੁ ਜਾਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਨਾਨਕ! ਪਰਮਾਤਮਾ ਦੇ ਨਾਮ ਤੋਂ ਸਦਕੇ ਹੋ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨਾਨਕ = ਹੇ ਨਾਨਕ! ਵਿਟਹੁ = ਤੋਂ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Nanak ofrece su ser en sacrificio al Naam, el Naam, el Nombre del Señor."