[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੋ ਦੀਸੈ; ਤੁਝ ਮਾਹਿ ਸਮਾਨਾ ॥"
page = 1021
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Whatsoever is seen shall merge in Thee in the end."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਹਿੜਾ ਕੁੱਛ ਭੀ ਦਿਸਦਾ ਹੈ, ਅੰਤ ਨੂੰ ਤੇਰੇ ਵਿੱਚ ਲੀਨ ਹੋ ਜਾਵੇਗਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Whatever is seen, shall merge into You."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਦੇਖੀਤਾ ਹੈ ਸਭ ਤੇਰੇ ਮੇਂ ਸਮਾਇਆ ਹੂਆ ਹੈ ਅਰਥਾਤ ਤੇਰਾ ਰੂਪ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਜਗਤ ਵਿਚ) ਜੋ ਕੁਝ ਦਿੱਸ ਰਿਹਾ ਹੈ ਉਹ ਸਭ ਤੇਰੇ ਵਿਚ ਹੀ ਲੀਨ ਹੋ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Todo lo que parece, se inmerge en Ti al final."