[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਜੈ ॥"
page = 10
line = 10

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Unconquerable Lord !"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਹੇ ਪ੍ਰਭੂ! ਤੂੰ) ਅਜਿਤ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਅਜੈ ॥"