[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਧ੍ਰਿਤ ਕੇ ਧ੍ਰਣ ਹੈਂ ॥"
page = 9
line = 13

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Lord! Thou art the support of the Earth!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਹੇ ਪ੍ਰਭੂ!) ਤੂੰ ਧਰਤੀ ਨੂੰ ਧਾਰਨ ਕਰਨ ਵਾਲਾ (ਸਹਾਰਾ) ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਧ੍ਰਿਤ ਕੇ, ਧਰਨ ਹੈਂ ॥"