[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਲਖੀ ਮ੍ਰੀਚ ਨੈਣੰ ॥"
page = 208

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Marich saw his army running away,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਮਾਰੀਚ ਨੇ (ਆਪਣੀ) ਅੱਖੀਂ ਵੇਖ ਲਿਆ।"