[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮਨਿ ਅਪਨੈ ਹੈ; ਸਭ ਤੇ ਨੀਚਾ ॥"
page = 272
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Within his mind, he is the most humble of all."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੇ ਚਿੱਤ ਅੰਦਰ ਉਹ ਸਾਰਿਆਂ ਨਾਲੋਂ ਨੀਵਾਂ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Within his own mind, he is the most humble of all."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕਿਉਂਕਿ ਵਹੁ ਅਪਨੇ ਮਨ ਸੇ ਸਰਬ ਸੇ ਨੀਵਾਂ ਹੋਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਪਰ) ਆਪਣੇ ਮਨ ਵਿਚ (ਆਪਣੇ ਆਪ ਨੂੰ) ਸਭ ਤੋਂ ਨੀਵਾਂ (ਜਾਣਦਾ ਹੈ)।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y sin embargo es humilde en Espíritu."