[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗਉੜੀ ਪੰਚਪਦਾ₃ ॥"
page = 333
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Gauri Panchpade."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਗਉੜੀ ਪੰਚਪਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Gauree, Panch-Padhay:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Gauri, Panch-Padas"