[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਵਹਿ ਜਾਹਿ; ਭ੍ਰਮਿ ਮਰਹਿ ਅਭਾਗੇ ॥"
page = 1069
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "those unfortunate ones come, go and die of wandering."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਨਿਕਰਮਣ ਆਉਂਦੇ, ਜਾਂਦੇ ਅਤੇ ਭਟਕਦੇ ਮਰ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "come and go, and wander in reincarnation; these unfortunate ones die."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੋ ਅਭਾਗੇ ਭਰਮ ਕਰ ਕੇ ਆਵਤੇ ਜਾਤੇ ਹੈਂ ਔਰ ਬਾਰੰਬਾਰ ਜਨਮਤੇ ਮਰਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਹ ਮੰਦ-ਭਾਗੀ ਮਨੁੱਖ ਭਟਕਣਾ ਵਿਚ ਪੈ ਕੇ ਆਤਮਕ ਮੌਤ ਸਹੇੜਦੇ ਹਨ, ਉਹ ਜਨਮ ਮਰਨ ਦੇ ਗੇੜ ਵਿਚ ਪਏ ਰਹਿੰਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਭ੍ਰਮਿ = ਭਟਕ ਭਟਕ ਕੇ। ਅਭਾਗੇ = ਮੰਦ-ਭਾਗੀ ਬੰਦੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "ese tonto desafortunado muere de tanto vagar, pero aun él podría ser emancipado,"