[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਭ ਬਸੇ. ਹਰਿ ਹਰਿ ਚੀਤ ॥੪॥"
page = 837
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "God, the Lord Master, abides in my mind."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਵਾਹਿਗੁਰੂ ਸੁਆਮੀ ਮਾਲਕ ਮੇਰੇ ਚਿੱਤ ਅੰਦਰ ਵਸਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Lord God, Har, Har, dwells within my consciousness. ||4||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਕੇ ਚਿਤ ਮੇਂ ਹਰ ਪ੍ਰਕਾਰ ਸੇ ਹਰਿ ਪ੍ਰਭੂ ਆਇ ਬਸੇ ਹੈਂ॥੪॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇ ਹਰਿ-ਪ੍ਰਭੂ ਜੀ ਹਿਰਦੇ ਵਿਚ ਵੱਸੇ ਰਹਿਣ ॥੪॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਚੀਤ = ਚਿੱਤ ਵਿਚ ॥੪॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y enaltezco a mi Señor en mi Conciencia.  (4)"