[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਕਲ ਸ੍ਰਾਧ ਕੋ ਸਾਜ ਬਨਾਯੋ ॥"
page = 859

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He conveyed her his intention negatively, not to observe the day, but she insisted must to adhere (to the ritual).(5)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਸ ਨੇ) ਸ਼ਰਾਧ ਦੀ ਸਾਰੀ ਤਿਆਰੀ ਕਰ ਲਈ।"