[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਗ੍ਰਿਹ ਕੀ ਭੂਲਿ ਸਕਲ ਸੁਧਿ ਗਈ ॥"
page = 1135

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਘਰ ਦੀ ਸਾਰੀ ਸੁੱਧ ਬੁੱਧ ਭੁਲ ਗਈ।"