[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤੇਰੀ ਗਤਿ ਅਵਿਗਤਿ; ਨਹੀ ਜਾਣੀਐ ॥"
page = 1168
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O Eternal Lord, Thy state can not be known."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਅਮਰ ਪ੍ਰਭੂ, ਤੇਰੀ ਅਵਸਥਾ ਜਾਣੀ ਨਹੀਂ ਜਾ ਸਕਦੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Your State cannot be known, O Eternal, Unchanging Lord God."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਅਵਗਤ! ਤੇਰੀ ਗਤੀ ਨਹੀਂ ਜਾਣੀ ਜਾਤੀ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਕਿਹੋ ਜਿਹਾ ਹੈਂ- ਇਹ ਗੱਲ ਸਮਝੀ ਨਹੀਂ ਜਾ ਸਕਦੀ, ਜਾਣੀ ਨਹੀਂ ਜਾ ਸਕਦੀ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗਤਿ = ਹਾਲਤ। ਤੇਰੀ ਗਤਿ = ਤੂੰ ਕਿਹੋ ਜਿਹਾ ਹੈਂ, ਇਹ ਗੱਲ। ਅਵਿਗਤਿ = ਜਾਣਨ ਤੋਂ ਪਰੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Eres el Estado Mental que nadie puede ni empezar a describir,"