[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਰੱਬ ਦੀ ਹਕੀਕਤ ਦੀ ਅਤਿ ਸੋਹਣੀ ਸੂਰਤ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਮਾਅਨੀਏ ਹੱਕ ਸੂਰਤੇ ਦਾਰਦ ਨਿਕੂ-ਸਤ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "And, Guru Gobind Singh is the seeker of God and is likeable and desirable of the people. (113)"