[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਗਲ ਕੀ ਚਿੰਤਾ; ਜਿਸੁ ਮਨ ਮਾਹਿ ॥"
page = 282
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Within whose mind is the anxiety of all,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਦੇ ਚਿੱਤ ਵਿੱਚ ਸਾਰਿਆਂ ਦਾ ਫਿਕਰ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The cares of all are on His Mind;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸਰਬ ਜੀਵਾਂ ਕੇ ਭਰਨ ਪੋਖਨ ਕੀ ਚਿੰਤਾ ਜਿਸ ਕੇ ਮਨ ਮੇਂ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਪ੍ਰਭੂ ਨੂੰ ਆਪਣੇ ਮਨ ਵਿਚ ਸਾਰਿਆਂ (ਦੀ ਰੋਜ਼ੀ) ਦਾ ਫ਼ਿਕਰ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਚਿੰਤਾ-ਫ਼ਿਕਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Todos encuentran lugar en Su Corazón"