[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਮਤ ਰਾਮ; ਪੂਰਨ ਸ੍ਰਬ ਠਾਂਇ ॥੯॥"
page = 1236
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Omnipresent Lord is filling all the places."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਰਬ-ਵਿਆਪਕ ਸੁਆਮੀ ਸਾਰੀਆਂ ਥਾਵਾਂ ਨੂੰ ਭਰ ਰਿਹਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Lord is perfectly pervading all places. ||9||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਰਮਣ ਰੂਪ ਰਾਮ ਸਰਬ ਅਸਥਾਨੋਂ ਮੇਂ ਪੂਰਨ ਹੋ ਰਹਾ ਹੈ॥੯॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਹ ਸਭ ਥਾਵਾਂ ਵਿਚ ਵਿਆਪਕ ਹੈ ਸਭ ਥਾਵਾਂ ਵਿਚ ਮੌਜੂਦ ਹੈ ॥੯॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਰਮਤ = ਵਿਆਪਕ। ਸ੍ਰਬ ਠਾਂਇ = ਸਭ ਥਾਵਾਂ ਵਿਚ ॥੯॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "nuestro Dios llena todos los lugares y prevalece en todos los seres. (9)"