[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਲਖ ਚਉਰਾਸੀਹ; ਜੋਨਿ ਫਿਰਹਿ ॥"
page = 211
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Through eighty four lacs of existences the mortals wander."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਚੁਰਾਸੀ ਲੱਖ ਜੂਨੀਆਂ ਅੰਦਰ ਪ੍ਰਾਣੀ ਭਟਕਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "People wander through 8.4 million incarnations."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਤਰ ਲੋਕ ਚਉਰਾਸੀ ਲਖ ਜੋਨ ਮੇਂ ਫਿਰਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ! ਜੀਵ) ਚੌਰਾਸੀ ਲੱਖ ਜੂਨਾਂ ਵਿਚ ਭਟਕਦੇ ਫਿਰਦੇ ਹਨ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਫਿਰਹਿ = ਭਟਕਦੇ ਫਿਰਦੇ ਹਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Los demás vagan a través de millones de especies,"