[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਰੀ ਦਇਆ; ਸਤਿਗੁਰਿ ਗੁਣਤਾਸਾ ॥੨॥"
page = 191
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "when True Guru, the treasure of excellence showers his benediction."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਦ ਗੁਣਾ ਦਾ ਖ਼ਜਾਨਾ ਸੱਚਾ ਗੁਰੂ ਆਪਣੀ ਮਿਹਰ ਧਾਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "when the True Guru, the Treasure of Excellence, shows His Kindness. ||2||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਬ ਸਰਬ ਗੁਨ ਸਮੁੰਦ੍ਰ ਪੂਰੇ ਸਤਿਗੁਰੋਂ ਨੈ ਕ੍ਰਿਪਾ ਕਰੀ ॥੨॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਗੁਣਾਂ ਦੇ ਖ਼ਜ਼ਾਨੇ ਸਤਿਗੁਰੂ ਨੇ ਜਿਸ ਮਨੁੱਖ ਉਤੇ ਮਿਹਰ ਕੀਤੀ ॥੨॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਤਿਗੁਰਿ ਗੁਣਤਾਸਾ = ਗੁਣਾਂ ਦੇ ਖ਼ਜ਼ਾਨੇ ਸਤਿਗੁਰੂ ਨੇ ॥੨॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "cuando el Verdadero Guru, el Tesoro de Virtud, es Compasivo contigo. (2)"