[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੰਤ ਕੈ ਊਪਰਿ; ਦੇਇ ਪ੍ਰਭੁ ਹਾਥ ॥"
page = 867
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Lord shields the saint with His Hand."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੇ ਹੱਥ ਨਾਲ ਸੁਆਮੀ ਆਪਣੇ ਸਾਧੂ ਦੀ ਰੱਖਿਆ ਕਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "God gives His hand to shelter the Saints."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੰਤੋਂ ਕੇ ਊਪਰ ਪ੍ਰਭੂ ਹਾਥ ਦੇਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਪ੍ਰਭੂ ਆਪਣਾ ਹੱਥ (ਆਪਣੇ) ਸੰਤ ਉੱਤੇ ਰੱਖਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕੈ ਊਪਰਿ = ਦੇ ਉੱਤੇ। ਦੇਇ = ਦੇਂਦੀ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Él sostiene siempre"