[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਰਬ ਸੁਖਾ ਸੁਖ; ਹਰਿ ਕੈ ਨਾਇ ॥"
page = 1180
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "All comforts are contained in the comfort of the Lord's Name."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਾਰੇ ਆਰਾਮ ਸੁਆਮੀ ਦੇ ਇਸ ਨਾਮ ਦੇ ਅੰਦਰ ਆ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "All comforts are contained in the Comfort of the Lord's Name."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹਰੀ ਨਾਮ ਕੇ ਸੁਖ ਕੇ ਅੰਤਰ ਸਮਗ੍ਰ ਸੁਖ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸਾਰੇ ਵੱਡੇ ਤੋਂ ਵੱਡੇ ਸੁਖ ਪਰਮਾਤਮਾ ਦੇ ਨਾਮ ਵਿਚ ਹੀ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨਾਇ = ਨਾਮ ਵਿਚ। ਹਰਿ ਕੇ ਨਾਇ = ਹਰੀ ਦੇ ਨਾਮ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "todas las dichas están contenidas en la Dicha del Naam, el Nombre del Señor."