[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਾਜਨ ਤੇਰੇ ਚਰਨ ਕੀ; ਹੋਇ ਰਹਾ ਸਦ ਧੂਰਿ ॥"
page = 518
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "My friend, may I ever be the dust of Thine Feet."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ ਮਿੱਤ੍ਰ, ਮੈਂ ਹਮੇਸ਼ਾਂ ਹੀ ਤੇਰੇ ਪੈਰਾਂ ਦੀ ਧੂੜ ਬਣਿਆ ਰਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O Friend, I pray that I may remain forever the dust of Your Feet."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਯਾਰੇ! ਮੈਂ ਤੇਰੇ ਚਰਨੋਂ ਕੀ ਨਿਤ੍ਯ ਧੂਰਿ ਬਨਾ ਰਹੂੰ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਸੱਜਣ! ਮੈਂ ਸਦਾ ਤੇਰੇ ਪੈਰਾਂ ਦੀ ਖ਼ਾਕ ਹੋਇਆ ਰਹਾਂ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਧੂਰਿ = ਧੂੜ, ਖ਼ਾਕ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Amigo, añoro volverme el Polvo de Tus Pies."