[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਜੀਵਨ ਮੁਕਤਿ ਕਰਾਇ, ਸਬਦੁ ਸਿਞਾਣਿਆ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Identifying the word they get liberated and"

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਜੀਵਨ ਮੁਕਤ ਹੋਕੇ ਸਬਦ ਬ੍ਰਹਮ ਨੂੰ ਹੀ ਸਾਰੇ ਪਛਾਣਦੇ ਹਨ।"