[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਬ ਕਿਸ ਕਉ; ਇਹੁ ਜਾਨਸਿ ਮੰਦਾ ॥"
page = 235
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "When he deems others bad,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਦ ਉਹ ਹੋਰਨਾ ਨੂੰ ਬੁਰਾ ਸਮਝਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "When he believes others to be bad,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜਬ ਕਿਸੀ ਕੋ ਇਹ ਮੰਦਾ ਜਾਨਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਦ ਤਕ ਮਨੁੱਖ ਹਰ ਕਿਸੇ ਨੂੰ ਭੈੜਾ ਸਮਝਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਿਸ ਕਉ = ਕਿਸੇ ਨੂੰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Cuando alguien considera que otro es malo,"