[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਹਾਲ ਵਿਚ ਰੱਬ ਰੱਖੇ, ਉਹੀ ਠੀਕ ਹੈ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਜ਼ਾਣ ਕਿ ਦਰ ਹਰ ਹਾਲ ਹੱਕ ਦਾਰਦ ਰਵਾ-ਸਤ ॥੧੧੧॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Also bless me with the company (of such persons) that can dispel all my worries and griefs. (463)"