[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਫਕੜੁ, ਹਿੰਦੂ ਮੁਸਲਮਾਣੈ ॥੧੬॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Thus the (classifications of) Muslims and Hindus"

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "(ਏਸੇ ਕਰਕੇ) ਹਿੰਦੂ ਅਤੇ ਮੁਸਲਮਾਨ (ਦੋਵੇਂ ਹੀ) ਫੱਕੜ ਹਨ, (ਭਾਵ ਨਿੰਦਕ ਅਤੇ ਵ੍ਯਰਥ ਹਨ)।"