[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਦੁਹੂੰ ਸੁਤਨ ਕੇ ਕਾਟ ਸਿਰ; ਲਏ ਗੋਦ ਮੈ ਡਾਰਿ ॥"
page = 975

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "She cut of and put the heads of both of them in her lap."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਦੋਹਾਂ ਪੁੱਤਰਾਂ ਦੇ ਸਿਰ ਕਟ ਕੇ ਗੋਦ ਵਿਚ ਪਾ ਲਏ"