[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਭ ਸਤਿਗੁਰ; ਦੀਨ ਦਇਆਲਾ ॥"
page = 628
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Divine True Guru is merciful to the meek."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰੱਬ ਰੂਪ ਸੱਚੇ ਗੁਰੂ ਜੀ ਮਸਕੀਨਾਂ ਉਤੇ ਮਿਹਰਬਾਨ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "God, the True Guru, is Merciful to the meek."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪ੍ਰਭੂ ਸਤਿਗੁਰੂ ਦੀਨੋ ਪਰ ਦ੍ਯਾਲਤਾ ਕਰਨੇ ਵਾਲਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਪ੍ਰਭੂ ਗਰੀਬਾਂ ਉਤੇ ਦਇਆ ਕਰਨ ਵਾਲਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਦਇਆਲਾ = ਦਇਆ ਕਰਨ ਵਾਲਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sí, nuestro Dios, el Verdadero Guru,"