[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਬਖਸ ਅਪੁਨੀ ਕਰਿ ਦੀਨੀ ॥"
page = 628
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "With His grace, he has blessed me."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੇ ਆਪਣੀ ਰਹਿਮਤ ਦੀ ਦਾਤ ਮੈਨੂੰ ਦਿੱਤੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He blessed me with forgiveness."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੋ ਭਗਤੀ ਅਪਣੀ ਬਖਸ਼ੀਸ ਕਰ ਕੇ ਹਮ ਕੋ ਦਈ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੂੰ ਗੁਰੂ ਨੇ ਆਪਣੇ ਦਰ ਤੋਂ ਪ੍ਰਭੂ ਦੀ ਭਗਤੀ ਦੀ ਦਾਤਿ ਦੇ ਦਿੱਤੀ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਬਖਸ = ਬਖ਼ਸ਼ਸ਼, ਦਾਤਿ, ਭਗਤੀ ਦੀ ਦਾਤਿ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y estamos llenos de Su Gracia."