[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਿਤੁ ਕਾਰਣਿ; ਸਿਰਿ ਛਾਈ ਪਾਈ ॥"
page = 951
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "What for has he put ashes on his head?"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕਿਸ ਵਾਸਤੇ ਉਸ ਨੇ ਆਪਣੇ ਸਿਰ ਵਿੱਚ ਸੁਆਹ ਪਾਈ ਹੈ?"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Why does he apply ashes to his forehead?"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕਿਸ ਵਾਸਤੇ ਜੋਗੀ ਨੇ ਸਿਰ ਪਰ ਸੁਆਹ ਪਾਈ, ਭਾਵ ਭੁਖ ਕਿਉਂ ਧਾਰਣੁ ਕੀਆ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਸਿਰ ਉਤੇ ਸੁਆਹ ਉਸ ਨੇ ਕਾਹਦੇ ਲਈ ਪਾਈ ਹੈ?"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਿਰਿ = ਸਿਰ ਉਤੇ। ਛਾਈ = ਸੁਆਹ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "¿Por qué entonces se untan cenizas sobre su frente?"