[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਰਿ ਸੇਵੇ; ਸੋ ਹਰਿ ਕਾ ਲੋਗੁ ॥"
page = 1172
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Whosoever serves God; he alone is the God's man."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਕੋਈ ਭੀ ਵਾਹਿਗੁਰੂ ਦੀ ਘਾਲ ਕਮਾਉਂਦਾ ਹੈ, ਕੇਵਲ ਉਹ ਹੀ ਵਾਹਿਗੁਰੂ ਦਾ ਬੰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "One who serves the Lord is the Lord's person."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਹਰੀ ਕੋ ਸੇਵਤਾ ਹੈ, ਸੋਈ ਹਰੀ ਕਾ ਲੋਗੁ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਹੜਾ ਮਨੁੱਖ ਪਰਮਾਤਮਾ ਦਾ ਸਿਮਰਨ ਕਰਦਾ ਹੈ ਉਹ ਪਰਮਾਤਮਾ ਦਾ ਭਗਤ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੇਵੇ = ਸਿਮਰਦਾ ਹੈ। ਸੋ = ਉਹ ਮਨੁੱਖ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Aquél que sirve a Dios, Él Mismo lo toma como Suyo."