[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਹੂੰ ਤਾਪ ਤਨਹਿ ਸਹੰਤ ॥"
page = 13

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Somewhere heat is endured on the body."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕਿਤੇ (ਕਈ) ਸ਼ਰੀਰ ਉਤੇ ਗਰਮੀ ਸਹਿੰਦੇ ਹਨ,"