[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਾਨ ਤਰਨ ਕਾ; ਇਹੈ ਸੁਆਉ ॥"
page = 293
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "This is the only way to save thy soul."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੀ ਆਤਮਾ ਦਾ ਪਾਰ ਉਤਾਰਾ ਕਰਨ ਦਾ ਕੇਵਲ ਏਹੀ ਤ੍ਰੀਕਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "this is the way to save your mortal soul."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪ੍ਰਾਣੋਂ ਕੇ ਧਾਰਨ ਕਰਨੇ ਹਾਰ ਜੀਵ ਕਾ ਇਹੀ (ਸੁਆਉ) ਪ੍ਰਜੋਜਨ ਹੈ, ਇਸ ਸੰਸਾਰ ਸੇ (ਤਰਨ) ਤਾਰਨੇ ਕਾ ਯਤਨ ਕਰੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜ਼ਿੰਦਗੀ ਨੂੰ (ਵਿਕਾਰਾਂ ਤੋਂ) ਬਚਾਉਣ ਦਾ ਇਹੀ ਵਸੀਲਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੁਆਉ = ਵਸੀਲਾ। ਤਰਨ = ਬਚਾਉਣਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Mantén a Dios cerca de tu ser las veinticuatro horas del día."