[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਆਜੋਤਿ ਵੰਦੰ ॥੨੪੯॥"
page = 655

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "In that holy country, assuming the religious garb, the prayer was being held, thinking of that one wearing the lion-cloth as effulgence.249."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਖੰਡ ਜੋਤਿ ਦੀ ਬੰਦਨਾ ਕਰਨ ਵਾਲਾ ਹੈ ॥੨੪੯॥"