[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਪਾਲਿ ਪੋਸਿ ਕਰਿ ਤਾਹਿ; ਬਡੋ ਕਰਿ ਲੀਜਿਯੈ ॥"
page = 825

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "You will have to look after him and bring him up."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੂੰ ਪਾਲ ਪੋਸ ਕੇ ਵੱਡਾ ਕਰ ਲੈ"