[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਪਿ ਭੁਲਾਵੈ; ਆਪਿ ਮਾਰਗਿ ਪਾਏ ॥"
page = 424
line = 4

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He Himself misleads and Himself puts on the right path."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਆਪੇ ਕੁਰਾਹੇ ਪਾਉਂਦਾ ਹੈ ਅਤੇ ਆਪੇ ਹੀ ਠੀਕ ਰਾਹੇ ਪਾਉਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He Himself misleads us, and He Himself puts us back on the Path."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਆਪ ਹੀ ਭੂਲਾਉਤਾ ਹੈ ਆਪ ਹੀ ਰਸਤੇ ਪਾਉਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰਮਾਤਮਾ ਆਪ ਹੀ ਕੁਰਾਹੇ ਪਾਂਦਾ ਹੈ ਆਪ ਹੀ ਸਹੀ ਰਸਤੇ ਪਾਂਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਾਰਗਿ = ਰਸਤੇ ਉਤੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Señor Mismo nos desvía y nos vuelve a poner en el Verdadero Sendero,"