[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਭ ਸਿਉ. ਲਾਗਿ ਰਹਿਓ ਮੇਰਾ ਚੀਤੁ ॥"
page = 682
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "My mind remains attached with the Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਂਡਾ ਮਨ ਸੁਆਮੀ ਨਾਲ ਜੁੜਿਆ ਰਹਿੰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "My consciousness remains attached to God."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸ ਪ੍ਰਭ ਕੇ ਸਾਥ ਮੇਰਾ ਚਿਤ ਲਾਗ ਰਹਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਮੇਰਾ ਮਨ (ਭੀ) ਉਸ ਪ੍ਰਭੂ ਨਾਲ ਜੁੜਿਆ ਰਹਿੰਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਿਉ = ਨਾਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Mi mente está entonada en mi Señor, Quien es mi Amigo y Compañero desde el principio hasta el fin,"