[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਝੂਠਾ ਡੰਫੁ; ਝੂਠੁ ਪਾਸਾਰੀ ॥"
page = 288
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "are false shows and false displays."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕੂੜੇ ਦਿਖਾਵੇ ਅਤੇ ਕੂੜੇ ਖਿਲਾਰੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "- false shows and false displays."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਸ ਝੂਠੇ (ਡੰਫੁ) ਦੰਭ ਕਰ ਕੇ ਇਹੁ ਜੀਵ ਝੂਠੇ ਪਸਾਰੇ ਵਾਲਾ ਹੋ ਰਹਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਹ ਸਭ ਝੂਠਾ ਦਿਖਾਵਾ ਹੈ, ਇਹ ਅਡੰਬਰ ਰਚਾਉਣ ਵਾਲਾ ਭੀ ਬਿਨਸਨਹਾਰ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਡੰਫੁ = ਦਿਖਾਵਾ। ਪਾਸਾਰੀ = (ਦਿਖਾਵੇ ਦਾ) ਖਿਲਾਰਾ ਖਿਲਾਰਨ ਵਾਲਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y la pompa son sólo engañosos espectáculos."