[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸ੍ਰੀ ਭਗੌਤੀ ਏ ਨਮਹ ॥"
page = 809

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "(In Praise of Bhagauti)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸ੍ਰੀ ਭਗੌਤੀ ਨੂੰ ਨਮਸਕਾਰ:"