[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮਃ ੪ ॥"
page = 311
line = 6

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "4th Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪਾਤਸ਼ਾਹੀ ਚੋਥੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Fourth Mehl:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Mejl Guru Ram Das, Cuarto Canal Divino."