[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਅਪੁਨਾ ਹੋਇਓ ਗੁਰੁ ਮਿਹਰਵਾਨਾ ॥"
page = 621
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "My Guru has become merciful."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰਾ ਗੁਰੂ ਦਇਆਲੂ ਹੋ ਗਿਆ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "My Guru has become merciful."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਅਪਨਾ ਗੁਰੂ ਮਿਹਰਵਾਨ ਹੂਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਜਿਨ੍ਹਾਂ ਮਨੁੱਖਾਂ ਉਤੇ ਪਿਆਰਾ ਗੁਰੂ ਦਇਆਵਾਨ ਹੁੰਦਾ ਹੈ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Cuando el Guru es Compasivo, uno obtiene Bondad, Dicha y Éxtasis,"