[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਸਚੁ ਸਚਾ, ਕੂੜਿ ਕੂੜੇ ਪਾਜੇ ॥੧੮॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "The truth is always true and falsehood is altogether false."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "(ਨਿਯਮ ਹੈ ਕਿ) ਸੱਚ ਸੱਚਾ ਹੈ ਤੇ ਕੂੜ ਦਾ ਪਾਜ ਕੂੜਾ ਹੀ ਹੈ।"