[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹੋਛੀ ਸਰਣਿ ਪਇਆ; ਰਹਣੁ ਨ ਪਾਈ ॥"
page = 371
line = 9

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By seeking paltry protection, I cannot save myself from her."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੁਛ ਪਨਾਹ ਲੈਣ ਦੁਆਰਾ, ਮੈਂ ਆਪਣੇ ਆਪ ਨੂੰ ਉਸ ਪਾਸੋਂ ਬਚਾ ਨਹੀਂ ਸਕਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Seeking meager protection, I am not protected from her."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "(ਹੋਛੀ) ਓਛੀ ਸਰਨ ਪੜਨੇ ਸੇ ਅਰਥਾਤ ਅਨ ਦੇਵਤੋਂ ਕੀ ਸਰਣਾਗਤਿ ਸੇ ਇਸ ਸੇ ਕੋਈ ਰਹਨੇ ਨਹੀਂ ਪਾਉਤਾ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਕਿਸੇ ਕਮਜ਼ੋਰ ਦੀ ਸਰਨ ਪਿਆਂ ਇਹ ਮੈਥੋਂ ਪਰੇ ਨਹੀਂ ਹਟਦੀ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਹੋਛੀ = ਕਮਜ਼ੋਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "ahí prevalece ella con su poder, si uno busca el refugio de esta vana mujer,"