[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੋ ਕਿਛੁ ਵਰਤੈ; ਸਭ ਤੇਰੀ ਰਜਾਇ ॥੧॥"
page = 151
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Whatsoever happens, is all according to Thy will."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਕੁਝ ਭੀ ਹੁੰਦਾ ਹੈ, ਸਮੂਹ ਤੇਰੇ ਭਾਣੇ ਅਨੁਸਾਰ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Whatever happens is all according to Your Will. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਕੁਛੁ ਵਰਤਤਾ ਹੈ, ਸੋ ਤੇਰੀ ਆਗਿਆ ਮੇਂ ਹੈ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਗਤ ਵਿਚ ਜੋ ਕੁਝ ਹੋ ਰਿਹਾ ਹੈ ਸਭ ਤੇਰੀ ਮਰਜ਼ੀ ਨਾਲ ਹੋ ਰਿਹਾ ਹੈ ॥੧॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਰਜਾਇ = ਹੁਕਮ, ਮਰਜ਼ੀ ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "todo sucede por Tu Voluntad.  (1)"