[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਇਸ ਮਿੱਟੀ ਦੇ ਸਰੀਰ ਨੂੰ ਇਸ ਲਈ ਸਥਿਰ ਜਾਣ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਈਂ ਵਜੂਦਿ ਖ਼ਾਕ ਰਾ ਕਾਇਮ ਬਦਾਂ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "And, the head of justice and fair play was elevated and raised high. (94)"