[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੁਖਿ ਸਾਲਾਹੀ ਸਚੇ ਸਾਹਾ ॥"
page = 1077
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Within my mouth, praise I the True Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੇ ਮੂੰਹ ਨਾਲ ਮੈਂ ਸੱਚੇ ਸੁਆਮੀ ਦੀ ਕੀਰਤੀ ਕਰਦਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "With my mouth, I praise my True Lord King."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਸਚੇ ਪਾਤਿਸਾਹੁ! ਤੇਰੇ ਕੋ ਮੁਖ ਕਰ ਕੇ ਮੈਂ ਸਾਲਾਹੋਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਸਦਾ ਕਾਇਮ ਰਹਿਣ ਵਾਲੇ ਪਾਤਿਸ਼ਾਹ! (ਮਿਹਰ ਕਰ) ਮੈਂ ਮੂੰਹੋਂ ਤੇਰੀ ਸਿਫ਼ਤ-ਕਰਦਾ ਰਹਾਂ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੁਖਿ = ਮੂੰਹ ਨਾਲ। ਸਾਲਾਹੀ = ਸਾਲਾਹੀਂ, ਮੈਂ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਕਰਾਂ। ਸਚੇ ਸਾਹਾ = ਹੇ ਸਦਾ-ਥਿਰ ਸ਼ਾਹ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Con mis labios entono siempre Su Alabanza, sí, a Él, Insondable y Sin Fronteras,"