[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਇੱਕ ਜ਼ੱਰਾ ਵੀ ਉਸਦੀ ਰਹਿਮਤ ਅਤੇ ਬਖਸ਼ਿਸ਼ ਤੋਣ ਖਾਲੀ ਨਹੀਣ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਯੱਕ ਜ਼ੱਰਾ ਜ਼ਿ ਫ਼ੈਜ਼ਿ ਰਹਿਮਤਸ਼ ਖ਼ਾਲੀ ਨੀਸਤ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Whosoever has linked and attached his mind to the Almighty,"