[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਸਾਧਸੰਗਤਿ, ਗੁਣ ਹਾਰੁ ਪਰੋਈ ॥੧੭॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "The gurmukhs have prepared the garland of virtues in the holy congregation."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਸਾਧ ਸੰਗਤ ਗੁਣਾਂ ਦਾ ਹਾਰ ਪਰੋਂਦੀ ਹੈ।"