[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਿਸ ਕਉ; ਹੋਤ ਪਰਾਪਤਿ ਸੁਆਮੀ ॥"
page = 286
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "attains to the Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਪ੍ਰਭੂ ਨੂੰ ਪਾ ਲੈਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "shall attain his Lord and Master."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸੀ ਕੌ ਸਤਿਗੁਰੋਂ ਦ੍ਵਾਰੇ ਸ੍ਵਾਮੀ ਪ੍ਰਾਪਤਿ ਹੋਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੂੰ ਮਾਲਿਕ ਪ੍ਰਭੂ ਮਿਲ ਪੈਂਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੁਆਮੀ = ਮਾਲਿਕ, ਪ੍ਰਭੂ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "se alcanza al Señor."