#!/usr/bin/env node
//
// Generates platform icon files from brand/icons.json.
//
//   node brand/scripts/generate-icons.mjs
//
// Plain Node with no dependencies, for the same reason as generate-tokens.mjs: this
// runs from apps/build.sh on a machine that may have no JS toolchain, and a
// generator that cannot run is a generator that gets bypassed.
//
// Why generated rather than a table in a document (ADR-0013): one semantic name maps
// to N platform values, and prose cannot check anything. This can, and does — a
// missing SF Symbol renders as nothing at all, which is a blank button in front of a
// congregation, so the availability check below is the reason the file exists.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const { icons } = JSON.parse(readFileSync(join(root, 'brand/icons.json'), 'utf8'))
const entries = Object.entries(icons)

const banner = (comment) => `${comment} Generated by brand/scripts/generate-icons.mjs — do not edit.
${comment} Source of truth: brand/icons.json`

// ------------------------------------------------------- availability check
//
// The deployment target is read from the project rather than hardcoded: it is the
// number that decides whether a symbol exists at runtime, and a copy of it here
// would be a second source of truth that goes stale the day someone bumps it.

const cmpVersion = (a, b) => {
  const pa = String(a).split('.').map(Number)
  const pb = String(b).split('.').map(Number)
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0)
    if (d !== 0) return d
  }
  return 0
}

const readDeploymentTarget = () => {
  const pbx = join(root, 'apps/ios/ShabadOS.xcodeproj/project.pbxproj')
  if (!existsSync(pbx)) return null
  const m = readFileSync(pbx, 'utf8').match(/IPHONEOS_DEPLOYMENT_TARGET = ([\d.]+);/)
  return m ? m[1] : null
}

const target = readDeploymentTarget()
const problems = []

if (target) {
  for (const [name, def] of entries) {
    const { symbol, minIOS, fallback, fallbackMinIOS } = def.ios
    if (cmpVersion(minIOS, target) <= 0) continue
    if (!fallback) {
      problems.push(`${name}: "${symbol}" needs iOS ${minIOS} but the app targets ${target}, and no fallback is declared`)
    } else if (cmpVersion(fallbackMinIOS, target) > 0) {
      problems.push(`${name}: fallback "${fallback}" needs iOS ${fallbackMinIOS}, also newer than the target ${target}`)
    }
  }
}

if (problems.length) {
  console.error('error: icons unavailable on the deployment target — they would render as nothing:')
  for (const p of problems) console.error(`  ${p}`)
  console.error('\nAdd a "fallback" (with "fallbackMinIOS") in brand/icons.json, or pick an older symbol.')
  process.exit(1)
}

// ---------------------------------------------------------------- Swift

// A custom SVG, where one exists, wins on every platform: the point of drawing one is
// that no native symbol was good enough. Nothing consumes these yet -- they are
// carried through so the decision is visible in the generated files rather than only
// in the JSON.
const customs = entries.filter(([, def]) => def.custom)
if (customs.length) {
  console.warn(`note: ${customs.length} icon(s) use a custom SVG: ${customs.map(([n]) => n).join(', ')}`)
}

const swiftIcon = ([name, def]) => {
  const { symbol, minIOS, fallback } = def.ios
  const doc = `  /// ${def.meaning}`
  if (!fallback) return `${doc}\n  /// SF Symbols, iOS ${minIOS}+.\n  static let ${name} = "${symbol}"`
  return `${doc}
  /// "${symbol}" is iOS ${minIOS}+; falls back to "${fallback}" below that.
  static let ${name} = resolve("${symbol}", fallback: "${fallback}")`
}

const swift = `${banner('//')}

import UIKit

/// Icon names shared with the Android app, keyed by what they *mean* rather than by
/// what they look like. Use \`Image(systemName: AppIcons.zoom)\`.
///
/// Availability is checked at generation time against IPHONEOS_DEPLOYMENT_TARGET,
/// so a symbol newer than the target cannot reach a build without a declared
/// fallback. \`resolve\` handles the remaining case: a device running an OS older
/// than the symbol, where \`UIImage(systemName:)\` returns nil and SwiftUI draws
/// nothing at all rather than complaining.
enum AppIcons {
  private static func resolve(_ preferred: String, fallback: String) -> String {
    UIImage(systemName: preferred) != nil ? preferred : fallback
  }

${entries.map(swiftIcon).join('\n\n')}
}
`

// ---------------------------------------------------------------- Kotlin

const drawableName = (name) => 'ic_' + name.replace(/[A-Z]/g, (c) => '_' + c.toLowerCase())

const kotlinIcon = ([name, def]) => `  /** ${def.meaning}${def.android.verified ? '' : ' UNVERIFIED: Material Symbols name not checked against a real icon set.'} */
  const val ${name} = "${drawableName(name)}"`

const kotlin = `${banner('//')}

package com.shabados.android

/**
 * Icon names shared with the iOS app, keyed by what they *mean* rather than by what
 * they look like.
 *
 * Values are **drawable resource names**, not resource ids: the vector assets are
 * imported by hand (Android Studio > New > Vector Asset > Clip Art) and this file is
 * generated, so it cannot reference an \`R.drawable\` entry that does not exist yet
 * without breaking every build until every icon is imported. Resolve with
 * \`context.resources.getIdentifier\`, or switch these to \`R.drawable.*\` once the
 * full set is in \`res/drawable/\` — at which point a missing icon becomes a compile
 * error, which is better.
 *
 * The Material Symbols name intended for each is in brand/icons.json.
 */
object AppIcons {
${entries.map(kotlinIcon).join('\n\n')}
}
`

const outputs = [
  ['apps/ios/ShabadOS/AppIcons.swift', swift],
  ['apps/android/app/src/main/java/com/shabados/android/AppIcons.kt', kotlin],
]

for (const [path, contents] of outputs) {
  const full = join(root, path)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, contents)
  console.log(`wrote ${path}`)
}

// ------------------------------------------------------------------ warnings
//
// Reported, not fatal: unlike the iOS availability check these describe work that is
// not done yet, and blocking the build on them would only teach people to bypass the
// generator.

const drawableDir = join(root, 'apps/android/app/src/main/res/drawable')
const present = existsSync(drawableDir) ? new Set(readdirSync(drawableDir).map((f) => f.replace(/\.xml$/, ''))) : new Set()
const missing = entries.map(([n]) => drawableName(n)).filter((d) => !present.has(d))
const unverified = entries.filter(([, d]) => !d.android.verified).map(([n]) => n)

if (missing.length) console.warn(`warning: ${missing.length}/${entries.length} Android drawables not yet in res/drawable/ — ${missing.slice(0, 4).join(', ')}${missing.length > 4 ? ', …' : ''}`)
if (unverified.length) console.warn(`warning: ${unverified.length}/${entries.length} Material Symbols names unverified — check in Android Studio > New > Vector Asset > Clip Art`)
