#!/usr/bin/env node
//
// Generates platform token files from brand/tokens.json.
//
//   node brand/scripts/generate-tokens.mjs
//
// Plain Node with no dependencies, deliberately: this has to run from apps/build.sh
// on a machine that may have neither bun nor a JS toolchain set up, and a generator
// that cannot run is a generator that gets bypassed.
//
// The apps share no code (ADR-0010 is undecided), so without this the same decision
// gets written twice and drifts. Anything both apps must agree on belongs here.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const tokens = JSON.parse(readFileSync(join(root, 'brand/tokens.json'), 'utf8'))

const { color, opacity, type } = tokens
const lineHeightRatio = +(type.lineHeight / type.defaultSize).toFixed(4)

const rgb = (hex) => {
  const n = parseInt(hex.replace('#', ''), 16)
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255]
}
const swiftComponents = (hex) => {
  const [r, g, b] = rgb(hex).map((c) => (c / 255).toFixed(4))
  return `red: ${r}, green: ${g}, blue: ${b}`
}
const kotlinHex = (hex) => `0xFF${hex.replace('#', '').toUpperCase()}`

const banner = (comment) => `${comment} Generated by brand/scripts/generate-tokens.mjs — do not edit.
${comment} Source of truth: brand/tokens.json`

// ---------------------------------------------------------------- Swift

const swiftColor = (name, pair) => `  /// light-dark(${pair.light}, ${pair.dark})
  static let ${name} = Color(UIColor { traits in
    traits.userInterfaceStyle == .dark
      ? UIColor(${swiftComponents(pair.dark)}, alpha: 1)
      : UIColor(${swiftComponents(pair.light)}, alpha: 1)
  })`

const swift = `${banner('//')}

import SwiftUI
import UIKit

/// Colour and type shared with the Android app. A UIColor provider is used rather
/// than reading \`@Environment(\\.colorScheme)\` so the value resolves itself —
/// including inside UIKit-backed views that never see the SwiftUI environment.
enum DesignTokens {
${Object.entries(color).map(([k, v]) => swiftColor(k, v)).join('\n\n')}

  static let tonerOpacity: Double = ${opacity.toner}

  static let defaultSize: Double = ${type.defaultSize}
  static let minSize: Double = ${type.minSize}
  static let maxSize: Double = ${type.maxSize}

  /// Total line box as a multiple of font size, so it holds when zoomed.
  /// Gurmukhi stacks vowel signs above and below the base line; at 1.0 the lagaa
  /// matraa collide with the line above.
  static let lineHeightRatio: Double = ${lineHeightRatio}

  static func clamp(_ size: Double) -> Double {
    min(maxSize, max(minSize, size))
  }

  /// SwiftUI's \`lineSpacing\` is *extra* space on top of the font's natural line
  /// height, not the total line box, so the target has to be measured against the
  /// real font metrics. Android's \`lineHeight\` is the total directly.
  static func lineSpacing(for size: Double, fontName: String) -> Double {
    let natural = UIFont(name: fontName, size: size)?.lineHeight ?? size * 1.2
    return max(0, size * lineHeightRatio - natural)
  }
}
`

// --------------------------------------------------------------- Kotlin

const kotlinColor = (name, pair) => `  /** light-dark(${pair.light}, ${pair.dark}) */
  val ${name}Light = Color(${kotlinHex(pair.light)})
  val ${name}Dark = Color(${kotlinHex(pair.dark)})`

const kotlin = `${banner('//')}

package com.shabados.android

import androidx.compose.ui.graphics.Color

/** Colour and type shared with the iOS app. */
object DesignTokens {
${Object.entries(color).map(([k, v]) => kotlinColor(k, v)).join('\n\n')}

  const val TONER_OPACITY = ${opacity.toner}f

  const val DEFAULT_SIZE = ${type.defaultSize}f
  const val MIN_SIZE = ${type.minSize}f
  const val MAX_SIZE = ${type.maxSize}f

  /**
   * Total line box as a multiple of font size, so it holds when zoomed. Gurmukhi
   * stacks vowel signs above and below the base line; at 1.0 the lagaa matraa
   * collide with the line above.
   */
  const val LINE_HEIGHT_RATIO = ${lineHeightRatio}f

  fun clamp(size: Float) = size.coerceIn(MIN_SIZE, MAX_SIZE)
}
`

// ------------------------------------------------- Android XML resources
//
// Compose cannot style the *window* — the surface behind it is set by the framework
// theme in res/values/themes.xml, which needs real colour resources. Without these
// the window stays light in dark mode, showing as a pale flash on launch.

const androidXml = (variant) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by brand/scripts/generate-tokens.mjs — do not edit. -->
<resources>
${Object.entries(color)
  .map(([name, pair]) => `    <color name="${name.replace(/[A-Z]/g, (c) => '_' + c.toLowerCase())}">${pair[variant]}</color>`)
  .join('\n')}
</resources>
`

const outputs = [
  ['apps/ios/ShabadOS/DesignTokens.swift', swift],
  ['apps/android/app/src/main/java/com/shabados/android/DesignTokens.kt', kotlin],
  ['apps/android/app/src/main/res/values/design_tokens.xml', androidXml('light')],
  ['apps/android/app/src/main/res/values-night/design_tokens.xml', androidXml('dark')],
]

for (const [path, contents] of outputs) {
  const full = join(root, path)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, contents)
  console.log(`wrote ${path}`)
}
