[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨਾਮ ਬਿਨਾ; ਨਿਹਫਲ ਸੰਸਾਰ ॥੧॥"
page = 198
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "without God's Name, unfruitful is the advent in this world."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹਰੀ ਨਾਮ ਦੇ ਬਾਝੋਂ ਇਸ ਜਹਾਨ ਅੰਦਰ ਆਉਣਾ ਨਿਸਫਲ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "without the Naam, the Name of the Lord, the world is fruitless. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕਿਉਂਕਿ ਨਾਮ ਸੇ ਬਿਨਾ ਜੋ ਸੰਸਾਰ ਮੇਂ ਔਰ ਕਾਮ ਹੈਂ, ਸੋ ਨਿਸਫਲ ਜਾਨਿਆਂ ਹੈ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰਮਾਤਮਾ ਦੇ ਨਾਮ ਤੋਂ ਬਿਨਾ ਸੰਸਾਰ ਦੇ ਸਾਰੇ ਪਦਾਰਥ ਉਹਨਾਂ ਨੂੰ ਵਿਅਰਥ ਜਾਪਦੇ ਹਨ ॥੧॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨਿਹਫਲ = ਵਿਅਰਥ ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y el mundo sin el Nombre,  se muestra seco y sin fruto. (1)"