[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਢਤ ਕ੍ਰਿਪਾਣ ਬਾਹੰਤ ਧੋਪ ॥"
page = 593

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕ੍ਰਿਪਾਨ ਕਢਦੇ ਹਨ ਅਤੇ ਕਿਰਚਾਂ ('ਧੋਪ') ਵਾਹੁੰਦੇ ਹਨ।"