[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਥ ਜੈਕਾਰ ਸਬਦ ਕਥਨੰ ॥"
page = 117

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "NOW THE WORDS OF VICTORY ARE RELATED:"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੁਣ ਜੈਕਾਰ ਸ਼ਬਦ ਦਾ ਕਥਨ"