[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਲੋਕ ਮਃ ੩ ॥"
page = 85
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Slok, Third Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਲੋਕ, ਤੀਜੀ ਪਾਤਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Salok, Third Mehl:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Slok, Mejl Guru Amar as, Tercer Canal Divino."