[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਰਿ ਜੀਤਿ ਜੀਤਿ ਅਖੰਡ ॥"
page = 155

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "By conquering the unbreakable enemies,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਸ ਨੇ) ਨਾ ਖੰਡੇ ਜਾ ਸਕਣ ਵਾਲੇ ਵੈਰੀਆਂ ਨੂੰ ਜਿਤ ਜਿਤ ਕੇ"