[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਮ ਦਇਆਰ; ਸੁਨਿ ਦੀਨ ਬੇਨਤੀ ॥"
page = 1229
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O Merciful Master, hear Thou the supplication of Thy meek slave."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਮਿਹਰਬਾਨ ਮਾਲਕ! ਤੂੰ ਆਪਣੇ ਮਸਕੀਨ ਗੋਲੇ ਦੀ ਪ੍ਰਾਰਥਨਾ ਸੁਣਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O Merciful Lord, please hear the prayer of the meek and the poor."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਰਾਮ ਦਇਆ ਕੇ ਘਰ! ਮੈਂ ਦੀਨ ਕੀ ਬੇਨਤੀ ਸ੍ਰਵਨ ਕਰੀਏ:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਦਾਸ ਨਾਨਕ! ਹੇ ਦਇਆ ਦੇ ਸੋਮੇ ਪ੍ਰਭੂ! ਮੇਰੀ ਗਰੀਬ ਦੀ ਬੇਨਤੀ ਸੁਣ!"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਰਾਮ ਦਇਆਰ = ਹੇ ਦਇਆਲ ਹਰੀ! ਦੀਨ ਬੇਨਤੀ = ਗਰੀਬ ਦੀ ਬੇਨਤੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Dios Compasivo, escucha la oración de Tu pobre Esclavo"