[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕੂੜੁ ਬੋਲਿ. ਮੁਰਦਾਰੁ ਖਾਇ ॥"
page = 139
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By uttering falsehood, man eats carrion,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਝੂਠ ਬੋਲ ਕੇ ਆਦਮੀ ਜਿਵੇ ਮੁਰਦੇ ਨੂੰ ਖਾਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Telling lies, they eat dead bodies."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਕਾਜੀ! ਜੋ ਝੂਠ ਬੋਲ ਕਰ ਖਾਨਾ ਹੈ, ਸੋ ਮੁਰਦਾਰ ਹੈ, ਭਾਵ ਏਹ ਕਿ ਹਰਾਮ ਖਾਣਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਜੋ ਮਨੁੱਖ) ਝੂਠ ਬੋਲ ਕੇ (ਆਪ ਤਾਂ) ਦੂਜਿਆਂ ਦਾ ਹੱਕ ਖਾਂਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੁਰਦਾਰੁ = ਹਰਾਮ, ਪਰਾਇਆ ਹੱਕ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Diciendo mentiras, comen cuerpos muertos,"