[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੰਮਣੁ ਮਰਣੁ; ਤਿਸੈ ਤੇ ਹੋਈ ॥"
page = 1057
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Coming and going both come from Him alone."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਉਣਾ ਅਤੇ ਜਾਣਾ ਦੋਨੋਂ ਕੇਵਲ ਉਸ ਤੋਂ ਹੀ ਹੁੰਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Birth and death come from Him."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਏਹ ਜੰਮਣਾ ਮਰਨਾ ਤਿਸੀ ਪਰਮੇਸਰ ਤੇ ਹੋਤਾ ਹੈ, ਭਾਵ ਪਰਮੇਸਰ ਦੀ ਆਗਿਆ ਕੋ ਕੌਨ ਦੂਰ ਕਰੇ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਹ ਜਨਮ ਮਰਨ (ਦਾ ਚੱਕਰ) ਉਸ ਪਰਮਾਤਮਾ ਦੀ ਰਜ਼ਾ ਅਨੁਸਾਰ ਹੀ ਹੁੰਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤਿਸੈ ਤੇ = ਉਸ (ਪਰਮਾਤਮਾ) ਤੋਂ ਹੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y de la muerte, pues es solamente a través de Él, el Dios, que ambos llegan a nosotros."