[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਰੋਜ਼ੀ ਦਿਹਿੰਦ ਹੈਂ ॥"
page = 8
line = 13

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Thou art Giver of Sustenance!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਹੇ ਪ੍ਰਭੂ!) ਤੂੰ ਰੋਜ਼ੀ ਦੇਣ ਵਾਲਾ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਕਿ, ਰੋਜੀ ਦਿਹੰਦ ਹੈਂ ॥"