[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਦਲਸਤੁਆਦਿ ਦੋਖੰ ॥"
page = 138

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Thou art the masher of all blemishes from the beginning"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਆਦਿ ਤੋਂ ਹੀ ਤੂੰ ਦੁਖਾਂ ਨੂੰ ਦਲਣ ਵਾਲਾ ਹੈਂ,"