[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਹਰ ਕਿਸੇ ਨੂੰ ਅਜਿਹੀ ਦੌਲਤ ਕਿਸਤਰਾਣ ਨਸੀਬ ਹੋ ਸਕਦੀ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਹਰ ਕਸੇ ਰਾ ਕੈ ਨਸੀਬ ਈਣ ਦੌਲਤ ਅਸਤ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Guru Gobind Singh is even kindlier for the compassionate. (127)"