[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਅਪਨੀ ਪਰਤੀਤਿ; ਆਪ ਹੀ ਖੋਵੈ ॥"
page = 268
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By his own acts, he forfeits his credit."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੇ ਅਮਲ ਦੁਆਰਾ ਉਹ ਆਪਣਾ ਇਤਬਾਰ ਗੁਆ ਲੈਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He himself destroys his own credibility,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸੀ ਤੇ ਸੋ ਜੀਵ ਅਪਨੀ ਪ੍ਰਤੀਤ ਆਪ ਹੀ ਖੋਇ ਲੇਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਇਸ ਤਰ੍ਹਾਂ) ਆਪਣਾ ਇਤਬਾਰ ਆਪ ਹੀ ਗਵਾ ਲੈਂਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਰਤੀਤਿ = ਇਤਬਾਰ। ਖੋਵੈ = ਗਵਾ ਲੈਂਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Él mismo destruye su propia credibilidad"