[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਲਾਜ ਮਰੈ; ਜੋ ਨਾਮੁ. ਨ ਲੇਵੈ ॥"
page = 1148
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He, who contemplates not the Name dies of shame."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਨਾਮ ਦਾ ਸਿਮਰਨ ਨਹੀਂ ਕਰਦਾ ਉਹ ਸ਼ਰਮ ਨਾਲ ਮਰ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "One who does not repeat the Naam, the Name of the Lord, shall die of shame."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਪੁਰਸ ਨਾਮੁ ਨਹੀਂ ਲੇਤਾ ਹੈ, ਸੋ ਲਜਾ ਕਰ ਮਰ ਜਾਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਹੜਾ ਮਨੁੱਖ ਪਰਮਾਤਮਾ ਦਾ ਨਾਮ ਨਹੀਂ ਸਿਮਰਦਾ, ਉਹ ਆਪਣੇ ਆਪ ਵਿਚ ਸ਼ਰਮ ਨਾਲ ਹੌਲਾ ਪੈ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "੫ਦਅਰਥ: ਲਾਜ ਮਰੈ = ਸ਼ਰਮ ਨਾਲ ਮਰ ਜਾਂਦਾ ਹੈ, ਸ਼ਰਮ ਨਾਲ ਹੌਲੇ ਜੀਵਨ ਵਾਲਾ ਹੋ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Aquél que no recita el Naam, el Nombre del Señor, muere en pena,"