[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਲਖ ਚਉਰਾਸੀਹ; ਭ੍ਰਮਤਾ ਫੇਰਿ ॥੩॥"
page = 180
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "In the eighty four lacs of existences he wanders through."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਚੁਰਾਸੀ ਲੱਖ ਜੂਨੀਆਂ ਅੰਦਰ ਉਹ ਭਟਕਦਾ ਫਿਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "he wanders lost through 8.4 million incarnations. ||3||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਯਾਂ ਤੇ ਚਉਰਾਸੀ ਲਾਖ ਜੂਨੋਂ ਮੇਂ ਭ੍ਰਮਤਾ ਫਿਰਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਇਸ ਤਰ੍ਹਾਂ) ਚੌਰਾਸੀ ਲੱਖ ਜੂਨਾਂ ਦੇ ਗੇੜ ਵਿਚ ਭਟਕਦਾ ਫਿਰਦਾ ਹੈ ॥੩॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਫੇਰਿ = ਗੇੜ ਵਿਚ ॥੩॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y divaga a través de las millones de especies de vida, nacimiento tras nacimiento. (3)"