[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਪੇ ਸੋਭਾ; ਸਦ ਹੀ ਪਾਏ ॥"
page = 798
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "They, of themselves attain eternal glory."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਖੁਦ ਹੀ ਸਦੀਵੀ ਕੀਰਤੀ ਨੂੰ ਪਰਾਪਤ ਹੋ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "They obtain eternal glory."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਬ ਤੂੰ ਆਪ ਤੇ ਹੀ ਸਦਾ ਸੋਭਾ ਕੋ ਪ੍ਰਾਪਤਿ ਹੋਵੇਂਗਾ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪ੍ਰਭੂ ਆਪ ਹੀ ਉਹਨਾਂ ਨੂੰ ਸਦਾ ਲਈ ਵਡਿਆਈ ਬਖ਼ਸ਼ਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਆਪੇ = (ਪ੍ਰਭੂ) ਆਪ ਹੀ। ਸਦ = ਸਦਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Son bendecidos con la Gloria para todos los tiempos."