[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਡਾਕਣੀ ਸਾਕਣੀ ਝਾਕਣੀ ਕਾਕਿੜਾ ॥"
page = 681

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "“You are Dakini, Shakini and sweet in speech"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਡਾਕਣੀ, ਸਾਕਣੀ, ਝਾਕਣੀ, ਕਾਕਿੜਾ,"