[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਮਕਲੀ ਬਾਣੀ ਰਵਿਦਾਸ ਜੀ ਕੀ ॥"
page = 973
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Ramkali. Hymns of Sire Ravidas."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਮਕਲੀ। ਸ਼ਬਦ ਪੂਜਯ ਰਵਿਦਾਸ ਜੀ ਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Raamkalee, The Word Of Ravi Daas Jee:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਰਾਮਕਲੀ ਵਿੱਚ ਭਗਤ ਰਵਿਦਾਸ ਜੀ ਦੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ramkali, Palabras de Ravi Das yi."