[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਔਰ ਰਾਨਿਯਨ ਓਰ ਨ ਹੇਰੈ ॥"
page = 933

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Every day Raja started to stay with her and abandoned going to other Ranis."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਹੋਰ ਰਾਣੀਆਂ ਵਲ ਵੇਖਦਾ ਤਕ ਨਹੀਂ ਸੀ।"