[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਧਿਕ ਦਿਯੋ ਤਿਹ ਤ੍ਰਿਯ ਕੇ ਦਾਨਾ ॥"
page = 1326

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਉਸ ਇਸਤਰੀ ਨੂੰ ਬਹੁਤ ਦਾਨ ਦਿੱਤਾ।"