[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬੈਨ ਸੁਨਤ ਸਹਚਰੀ; ਜਾਤਿ ਤਿਹ ਕੌ ਭਈ ॥"
page = 1142

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਗੱਲ ਸੁਣ ਕੇ ਸਖੀ ਉਧਰ ਨੂੰ ਚਲੀ ਗਈ"