[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਗੁਰਸਿਖਾਂ ਗੁਰਸਿਖ; ਸੇਵ ਕਮਾਵਣੀ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "Within the teaching of the Guru, the Sikhs of the Guru serve (others)."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਗੁਰੂ ਦੇ ਸਿੱਖਾਂ ਦੀ ਸੇਵਾ ਗੁਰੂ ਦੇ ਸਿੱਖ ਕਰਦੇ ਹਨ।"