[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪੂਰੇ ਗੁਰ ਕੀ; ਸਾਚੀ ਬਾਣੀ ॥"
page = 663
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "True are the hymns of the Perfect Guru,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੱਚੀ ਹੈ ਬਾਣੀ ਗੁਰਾਂ ਦੀ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "True is the Word of the Perfect Guru's Bani."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪੂਰੇ ਗੁਰੋਂ ਕੀ ਜੋ ਉਪਦੇਸ਼ ਰੂਪ ਸਾਚੀ ਬਾਣੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ!) ਪੂਰੇ ਗੁਰੂ ਦੀ (ਉਚਾਰੀ ਹੋਈ) ਸਦਾ-ਥਿਰ ਪ੍ਰਭੂ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਵਾਲੀ ਬਾਣੀ-"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਾਚੀ = ਸਦਾ-ਥਿਰ ਪ੍ਰਭੂ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਵਾਲੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "La Palabra del Shabd del Guru Perfecto es Verdad,"