[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਇਹ ਸਭ ਕੁਝ ਉਸੇ ਬੰਦਗੀ ਦੀ ਬਦੌਲਤ ਹੀ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਈਂ ਹਮਾ ਅਜ਼ ਦੌਲਤਿ ਈਂ ਬੰਦਗੀਸਤ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Are standing as slaves and servitors with their heads bowed. (76)"