[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਿਸੁ ਭਗਉਤੀ ਕੀ; ਮਤਿ ਊਤਮ ਹੋਵੈ ॥"
page = 274
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Supreme becomes the wisdom of such a Bhagauti."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸ਼੍ਰੇਸ਼ਟ ਹੋ ਜਾਂਦੀ ਹੈ ਇਹੋ ਜਿਹੇ ਭਗਉਤੀ ਦੀ ਸੋਚ-ਸਮਝ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The wisdom of such a Bhagaautee becomes supreme."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸੀ ਭਗਤੀ ਕਰਨੇ ਵਾਰੇ ਕੀ ਬੁਧੀ ਉਤਮ ਹੋਤੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਭਗਉਤੀ ਦੀ ਮਤਿ ਉੱਚੀ ਹੁੰਦੀ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Así es en verdad la vida del Bagauti, quien con mente absorta"