[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨੱਚੇ ਮਰਾਲ ॥"
page = 63

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Kirpal Chnad was in great fury. The horses danced."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਸ ਨੇ) ਘੋੜੇ ਨੂੰ ਨਚਾਇਆ।"