[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬੜੇ ਇਖੁ ਧਾਰੀ ॥"
page = 101

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "They were great archers"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਹ) ਬਹੁਤ ਵੱਡੇ ਧਨੁਸ਼ਧਾਰੀ ਸਨ"