[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਲੋਕੁ ਮਃ ੩ ॥"
page = 149
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Slok, Third Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਲੋਕ ਤੀਜੀ ਪਾਦਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Salok, Third Mehl:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Slok, Mejl Guru Amar Das, Tercer Canal Divino."