[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨ ਰੇਖੇ ॥੧੯੫॥"
page = 10
line = 13

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Lineless Lord  ! 195"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਰੇਖ ਤੋਂ ਪਰੇ ਹੈਂ ॥੧੯੫॥"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨ, ਰੇਖੇ ॥੧੯੫॥"