[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਦਿਲ ਦਾ ਮੰਦਰ ਰੱਬ ਨਾਲ ਵਸ ਗਿਆ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਖ਼ਾਨਾਇ ਦਿਲ ਅਜ਼ ਖ਼ੁਦਾ ਮਾਮੂਰ ਸ਼ੁਦ ॥੨੮੭॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "He sanctifies different regions and is the donor of benedictions,"