[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਬਹੁ. ਨ ਸੂਚਾ; ਕਾਲਾ ਕਾਉ ॥"
page = 839
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The black crow is ever impure."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਿਆਹ ਕੱਵਾ ਕਦੇ ਭੀ ਪਵਿੱਤਰ ਨਹੀਂ ਹੁੰਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "like the black crow, he never becomes pure."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੈਸੇ ਕਾਲਾ ਕਾਂਉ ਕਬੀ ਸੂਚਾ ਨਹੀਂ ਹੋਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਮਨੁੱਖ ਦਾ ਮਨ ਵਿਕਾਰਾਂ ਨਾਲ ਕਾਂ ਵਾਂਗ ਕਾਲਾ ਹੋ ਜਾਏ ਉਹ (ਮਾਇਆ ਵਿਚ ਫਸਿਆ ਰਹਿ ਕੇ) ਕਦੇ ਭੀ ਪਵਿੱਤ੍ਰ ਨਹੀਂ ਹੋ ਸਕਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੂਚਾ = ਪਵਿਤ੍ਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "así como el cuervo negro que siempre está sucio"