[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰਮੁਖਿ ਸਭੁ ਵਾਪਾਰੁ ਭਲਾ; ਜੇ ਸਹਜੇ ਕੀਜੈ ਰਾਮ ॥"
page = 568
line = 10

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "If accomplished through divine knowledge, then, all the dealings of the pious person are good."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੇਕਰ ਬ੍ਰਹਿਮ-ਗਿਆਨ ਦੇ ਰਾਹੀਂ ਕੀਤੇ ਜਾਣ ਤਾਂ ਪਵਿੱਤਰ ਪੁਰਸ਼ ਦੇ ਸਾਰੇ ਵਣਜ ਚੰਗੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "All dealings of the Gurmukh are good, if they are accomplished with poise and grace."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਜੋ (ਸਹਜੇ) ਸੁਭਾਵਕ ਹੀ ਕਰਤੇ ਹੈਂ, ਸੋ ਗੁਰਮੁਖੋਂ ਕਾ ਸਭ ਬਪਾਰ ਭਲਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇ ਗੁਰੂ ਦੀ ਰਾਹੀਂ ਆਤਮਕ ਅਡੋਲਤਾ ਵਿਚ ਟਿਕ ਕੇ (ਹਰਿ-ਨਾਮ ਦਾ) ਵਪਾਰ ਕੀਤਾ ਜਾਏ, ਤਾਂ ਇਹ ਸਾਰਾ ਵਪਾਰ ਮਨੁੱਖ ਲਈ ਭਲਾ ਹੁੰਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਰਮੁਖਿ = ਗੁਰੂ ਦੀ ਸਰਨ ਪੈ ਕੇ। ਵਾਪਾਰੁ = ਨਾਮ ਦਾ ਵਣਜ। ਸਹਜੇ = ਆਤਮਕ ਅਡੋਲਤਾ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El hombre entonado en Dios es bendecido de manera natural."