[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰਮੁਖਿ ਹੋਵੈ; ਸੋ ਤਤੁ ਪਾਏ ॥"
page = 1016
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He, who becomes the Guru-ward, obtains the quintessence,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੋ ਗੁਰੂ-ਅਨੁਸਾਰੀ ਥੀ ਵੰਝਦਾ ਹੈ, ਵੁਹ ਜੋਹਰ ਨੂੰ ਪਾ ਲੈਂਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "One who becomes Gurmukh, obtains the essence of reality;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਗੁਰਮੁਖਿ ਹੋਤੇ ਹੈਂ, ਸੋ ਹੇ ਤਤ ਸਰੂਪ! ਤੇਰੇ ਕੋ ਪਾਵਤੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਹੜਾ ਮਨੁੱਖ ਗੁਰੂ ਦੇ ਸਨਮੁਖ ਹੁੰਦਾ ਹੈ, ਉਹ (ਇਹ) ਅਸਲੀਅਤ ਲੱਭ ਲੈਂਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਰਮੁਖਿ = ਗੁਰੂ ਦੇ ਸਨਮੁਖ। ਸੋ = ਉਹ ਮਨੁੱਖ। ਤਤੁ = ਨਿਚੋੜ, ਅਸਲ ਸਿੱਟਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Aquél que logra la Conciencia de Dios, obtiene la Quintaesencia y purga su ser de su ego negativo."