[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਰੇ ਜੁੱਧ ਘੋਰੰ ॥"
page = 42

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Fighting frightening battles."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਤਾਂ) ਭਿਆਨਕ ਯੁੱਧ ਕਰਦਾ ਹੈ।"