[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੰਕਰ ਸੈਨ ਨ੍ਰਿਪਹਿ ਅਸ ਛਲਾ ॥"
page = 1213

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਇਸ ਤਰ੍ਹਾਂ ਸੰਕਰ ਸੈਨ ਰਾਜੇ ਨੂੰ ਛਲਿਆ ਗਿਆ"