[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਿੰਗੀ ਰਿਖਿ ਬਕਦਾਲਭ ਭਨੇ ॥"
page = 708

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Many sages like Vyas, Prashar, Shringi etc. have mentioned it"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸ੍ਰਿੰਗੀ ਰਿਸ਼ੀ ਅਤੇ ਬਕਦਾਲਭ ਆਦਿਕ (ਤੇਰਾ ਯਸ਼) ਕਹਿੰਦੇ ਹਨ।"