[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸਰਬ ਉਬਾਰਣ ਹੈਂ ॥੧੭੨॥"
page = 9
line = 13

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Lord! Thou art the Saviour of all! 172"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਸਭ ਨੂੰ ਬਚਾਉਣ ਵਾਲਾ ਹੈਂ ॥੧੭੨॥"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਸਰਬ ਉਬਾਰਨ, ਹੈਂ ॥੧੭੨॥"