[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਿਸ ਕਾ; ਪ੍ਰਭੂ ਸੋਇ ਹਾਂ ॥"
page = 410
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "that Lord is of him."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਸ ਦਾ ਉਹ ਵਾਹਿਗੁਰੂ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "God belongs to him."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸ ਕਾ ਹੇ ਪ੍ਰਭੁ! ਸੋ ਤੂੰ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਜੇ ਉਹ ਪ੍ਰਭੂ ਦੀ ਸਰਨ ਆ ਪਏ, ਤਾਂ) ਉਹ ਪ੍ਰਭੂ ਉਸ ਦਾ ਰਾਖਾ ਬਣ ਜਾਂਦਾ ਹੈ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "aún de él es mi Señor su Dios."