[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪੂਰੇ ਗੁਰ ਤੇ; ਇਹ ਮਤਿ ਪਾਏ ॥੭॥"
page = 222
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "From the Perfect Guru, this understanding is obtained."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪੂਰਨ ਗੁਰਾਂ ਪਾਸੋਂ ਇਹ ਸਮਝ ਪ੍ਰਾਪਤ ਹੁੰਦੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "This understanding is obtained from the Perfect Guru. ||7||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪਰੰਤੂ ਐਸੀ (ਮਤਿ) ਸਿਖ੍ਯਾ ਪੁਰਸ਼ ਪੂਰੇ ਗੁਰੋਂ ਸੇ ਪਾਵਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰ ਇਹ ਅਕਲ ਉਹ ਪੂਰੇ ਗੁਰੂ ਤੋਂ ਹੀ ਪ੍ਰਾਪਤ ਕਰਦਾ ਹੈ ॥੭॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਰ ਤੇ = ਗੁਰੂ ਤੋਂ ॥੭॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ésta es la Sabiduría que uno recibe del Verdadero Guru.(7)"