[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਵਹੈ ਯਾਹਿ ਕੰਨ︀ਯਾ ਕਹੁ ਬਰਿ ਹੈ ॥੧੩॥"
page = 870

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He announced, ‘Whosoever wins the war, will marry my daughter.’(13)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਹੀ ਇਸ ਕੰਨਿਆਂ ਨੂੰ ਵਰੇਗਾ ॥੧੩॥"