[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਹ ਦੋਹਾਂ ਜਹਾਨਾਂ ਦੇ ਕੰਮਾਂ ਦਾ ਪ੍ਰਬੰਧ-ਕਰਤਾ ਹੈ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਮੁਹਿੱਮਾਤਿ ਦਾਰੈਨ ਰਾ ਇੰਤਜ਼ਾਮ ॥੧੦੭॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "And, he is the general manager of the tasks and actions of both the worlds. (107)"