[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜਾ ਕਾ ਭਰਵਾਸਾ; ਸਭ ਘਟ ਮਾਹਿ ॥"
page = 1144
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He, whose support is in all the hearts."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਦਾ ਆਸਰਾ ਸਾਰਿਆਂ ਦਿਲਾਂ ਅੰਦਰ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "All hearts rest their faith and hope in Him."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਪੁਨਹ ਜਿਸ ਕਾ ਭਰਵਾਸਾ ਸਰਬ ਘਟੋਂ ਮੇਂ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਪਰਮਾਤਮਾ ਦਾ ਸਹਾਰਾ ਹਰੇਕ ਜੀਵ ਦੇ ਹਿਰਦੇ ਵਿਚ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਭਰਵਾਸਾ = ਸਹਾਰਾ। ਘਟ = ਹਿਰਦਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "sí Aquél en el que los corazones de todos se apoyan,"