[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗਿਆਨੀ ਗੁਰ ਬਿਨੁ; ਭਗਤਿ. ਨ ਹੋਈ ॥"
page = 732
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O divine, without the Guru, the Lord's devotional service cannot be performed."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਬ੍ਰਹਿਮ ਬੇਤੇ! ਗੁਰਾਂ ਦੇ ਬਾਝੋਂ ਬਾਹਿਬ ਦੀ ਪ੍ਰੇਮੀ-ਮਈ ਸੇਵਾ ਕੀਤੀ ਨਹੀਂ ਜਾ ਸਕਦੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O wise ones, without the Guru, there is no devotional worship."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਬ੍ਰਹਮਨੇਸ੍ਟੀ ਬ੍ਰਹਮ ਸ੍ਰੋਤੀ ਗੁਰੂ ਬਿਨਾਂ ਭਗਤੀ ਕੀ ਪ੍ਰਾਪਤੀ ਨਹੀਂ ਹੋਤੀ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਗਿਆਨਵਾਨ! ਗੁਰੂ ਦੀ ਸਰਨ ਪੈਣ ਤੋਂ ਬਿਨਾ ਭਗਤੀ ਨਹੀਂ ਹੋ ਸਕਦੀ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗਿਆਨੀ = ਹੇ ਗਿਆਨਵਾਨ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh erudito, no se puede alabar al Señor sin la Gracia del Guru,"