[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਸਾ ਘਰੁ ੮ ਕਾਫੀ ਮਹਲਾ ੩ ॥"
page = 365
line = 4

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Asa Measure. Kafi. 3rd Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਸਾ। ਕਾਫੀ। ਤੀਜੀ ਪਾਤਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Aasaa, Eighth House, Kaafee, Third Mehl:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਆਸਾ, ਘਰ ੮ ਵਿੱਚ ਗੁਰੂ ਅਮਰਦਾਸ ਜੀ ਦੀ ਬਾਣੀ 'ਕਾਫੀ'।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Asa, Mejl Guru Amar Das, Tercer Canal Divino, Kafi."