[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਇਸਲਈ ਉਹ ਪੂਰਨ ਗਿਆਨਵਾਨਾਂ ਦੇ ਪਿੱਛੇ ਤੁਰਦੇ ਹਨ । "

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਪੈਰਵੀਇ ਆਰਿਫ਼ਿ ਕਾਮਿਲ ਕੁਨੰਦ ॥੩੮੮॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Thousands of Mahayshs and Thousands of Ganayshs"