[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਹ ਇਨਸਾਫ ਅਤੇ ਨਿਆਇ ਦੀ ਅੰਗੂਠੀ ਦਾ ਨਗੀਨਾ ਹੈ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਨਗ਼ੀਂ ਖ਼ਾਤਮਿ ਨਿਸਫ਼ਤੋ ਅਦਲ ਰਾ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "He is the gem of the ring of justice and fairness,"