[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਐਸਾ ਹਰਿ ਧਨੁ. ਸੰਚੀਐ ਭਾਈ ॥"
page = 375
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Such a Divine wealth, one should amass, O brother."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਐਹੋ ਜੇਹੀ ਰੱਬੀ ਦੌਲਤ ਬੰਦੇ ਨੂੰ ਇਕੱਤਰ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ, ਹੇ ਵੀਰ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Gather such a wealth of the Lord, O Siblings of Destiny."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਐਸਾ ਹਰਿ ਨਾਮ ਧਨ (ਸੰਚੀਐ) ਇਕਤ੍ਰ ਕਰੀਐ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਵੀਰ! ਇਹੋ ਜਿਹਾ ਪਰਮਾਤਮਾ ਦਾ ਨਾਮ-ਧਨ ਇਕੱਠਾ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੰਚੀਐ = ਇਕੱਠਾ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ। ਭਾਈ = ਹੇ ਭਾਈ!"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Tal Tesoro Divino debe uno de recolectarlo siempre, oh hermano,"