[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਨੈਨੀ ਪੇਖਤ; ਸਾਧ ਦਇਆਲ ॥"
page = 298
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "with thine eyes see the kind saints."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੀਆਂ ਅੱਖਾਂ ਨਾਲ ਕ੍ਰਿਪਾਲੂ ਸੰਤਾਂ ਨੂੰ ਦੇਖ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "with your eyes, behold the kind, Holy Saints."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਨੇਤ੍ਰੋਂ ਸੇ ਦਿਆਲ ਸੰਤੋਂ ਕਾ ਦਰਸਨ ਦੇਖੀਏ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਅੱਖਾਂ ਨਾਲ ਦਇਆ ਦੇ ਘਰ ਗੁਰੂ ਦਾ ਦਰਸਨ ਕਰੀਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨੈਨੀ = ਅੱਖਾਂ ਨਾਲ। ਸਾਧ = ਗੁਰੂ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y ve a nadie excepto al Santo Compasivo,"