[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕੇਵਲ, ਕਾਲਈ ਕਰਤਾਰ ॥"
page = 711

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The supreme Destroyer is alone the Creator,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਕੇਵਲ ਕਾਲ ਹੀ ਸਭ ਦਾ ਕਰਤਾ ਹੈ।"