[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗਹਿ ਭੁਜਾ; ਪ੍ਰਭ ਜੀ ਲੇਹੁ ॥"
page = 838
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Hold me by the hand and save me o My Sire Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਬਾਂਹੋਂ ਫੜ ਕੇ ਮੇਰੀ ਰੱਖਿਆ ਕਰ, ਹੇ ਮੇਰੇ ਮਹਾਰਾਜ ਮਾਲਕ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Please take my hand, and save me, Dear God."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਤੇ ਹੇ ਪ੍ਰਭ ਜੀ! ਐਸੇ ਅੰਧੇਰੇ ਵਿਚੋਂ ਭੁਜਾ ਪਕੜ ਲੀਜੀਏ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਮੇਰੀ) ਬਾਂਹ ਫੜ ਕੇ (ਮੈਨੂੰ) ਬਚਾ ਲੈ"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗਹਿ = ਫੜ ਕੇ। ਭੁਜਾ = ਬਾਂਹ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Dios, tómame de la mano"