[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਪਣੀ ਕੁਦਰਤਿ; ਆਪੇ ਜਾਣੁ ॥੧॥ ਰਹਾਉ ॥"
page = 743
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Lord Himself knows His omnipotence. Pause."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੀ ਅਪਾਰ ਸ਼ਕਤੀ ਨੂੰ ਪ੍ਰਭੂ ਆਪ ਹੀ ਜਾਣਦਾ ਹੈ। ਠਹਿਰਾਉ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Only He Himself knows His creative omnipotence. ||1||Pause||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਆਪਣੀ ਸਕਤੀ ਕੋ ਤੂੰ ਆਪੇ ਹੀ ਜਾਨਤਾ ਹੈਂ॥੧॥ ਰਹਾਉ ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪਰਮਾਤਮਾ ਆਪਣੀ ਰਚੀ ਸ੍ਰਿਸ਼ਟੀ ਬਾਰੇ ਆਪ ਹੀ ਸਭ ਕੁਝ ਜਾਣਨ ਵਾਲਾ ਹੈ ॥੧॥ ਰਹਾਉ ॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜਾਣੁ = ਜਾਣੂ, ਜਾਣਨ ਵਾਲਾ ॥੧॥ ਰਹਾਉ ॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pues sólo Él conoce Su Omnipotencia Creativa. (1-Pausa)"