[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੂਰਖਿ ਪੜਿ ਪੜਿ; ਦੂਜਾ ਭਾਉ ਦ੍ਰਿੜਾਇਆ ॥"
page = 424
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The fool reads much and holds fast to duality."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੂੜ੍ਹ ਘਣੇਰਾ ਪੜ੍ਹਦਾ ਹੈ, ਅਤੇ ਦਵੈਤ ਭਾਵ ਨੂੰ ਘੁੱਟ ਕੇ ਫੜੀ ਰਖਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The fool reads and reads, but holds tight to duality."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮੂਰਖ ਨੇ ਪੜ ਕਰ ਕੇ ਦ੍ਵੈਤ ਭਾਉ ਕੋ ਦ੍ਰਿੜ ਕੀਆ ਔਰ ਕਰਾਯਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮੂਰਖ ਮਨੁੱਖ ਨੇ (ਗੁਰੂ ਤੋਂ ਖੁੰਝ ਕੇ ਸਿੰਮ੍ਰਿਤੀਆਂ ਸ਼ਾਸਤਰ ਆਦਿਕ) ਪੜ੍ਹ ਪੜ੍ਹ ਕੇ (ਆਪਣੇ ਅੰਦਰ ਸਗੋਂ) ਮਾਇਆ ਦਾ ਪਿਆਰ ਹੀ ਪੱਕਾ ਕੀਤਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੂਰਖਿ = ਮੂਰਖ ਨੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "mantiene su embrujo. Los supuestos sabios leen muchos libros, pero se aferran al otro,"