[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਜੌ ਮੈ ਕਹੋ, ਸੁ ਕਰਿਯਹੁ; ਸਾਜਨ, ਆਇ ਕੈ ॥"
page = 1001

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "‘Whatever I say, my benefactor, you must do."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਸਾਜਨ! ਜੋ ਮੈਂ ਕਹਾਂ, ਉਹੀ ਤੁਸੀਂ ਆ ਕੇ ਕਰਨਾ"