[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਛੋਡਹੁ; ਕਾਮ ਕ੍ਰੋਧੁ ਬੁਰਿਆਈ ॥"
page = 1026
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Renounce thou lust, wrath and wickedness."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਵਿਸ਼ੇ ਭੋਗ, ਗੁੱਸੇ ਅਤੇ ਬਦੀ ਨੂੰ ਤਿਲਾਂਜਲੀ ਦੇ ਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Abandon sexual desire, anger and wickedness."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਸੀ ਤੇ ਬੁਰਾਈ, ਕਾਮ, ਕ੍ਰੋਧ ਕੋ ਛੋਡੋ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਕਾਮ ਕ੍ਰੋਧ ਆਦਿਕ ਮੰਦ ਕਰਮ ਤਿਆਗੋ,"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Abandona la lujuria, el enojo y las acciones malvadas;"