[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸ੍ਰੀ ਮਹਤਾਬ ਮਤੀ ਤਿਹ ਕੰਨ︀ਯਾ ॥"
page = 1326

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਦੀ ਪੁੱਤਰੀ ਦਾ ਨਾਂ ਮਹਤਾਬ ਮਤੀ ਸੀ"