[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਨਮਸਤੰ ਅਨਾਦੇ ॥"
page = 2
line = 3

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Salutation to Thee O Beginningless Lord!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਹੇ ਬਿਨਾ ਆਦਿ (ਮੁੱਢ) ਵਾਲੇ! ਤੈਨੂੰ ਨਮਸਕਾਰ ਹੈ;"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਨਮਸਤੰ, ਅਨਾਦੇ ॥"