[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਦੂਰਿ ਨਾਹੀ; ਦੇਖਹੁ ਕਰਿ ਨੰਦਰਿ ॥"
page = 1026
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He is not far off. See thou Him by casting a glance."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਦੁਰੇਡੇ ਨਹੀਂ। ਨਜ਼ਰ ਪਾ ਕੇ ਤੂੰ ਉਸ ਨੂੰ ਤੱਕ ਲੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He is not far away; look, and see Him."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੇ ਨਦਰ ਕਰ ਦੇਖੋ ਤੌ ਵਾਹਿਗੁਰੂ ਦੂਰ ਨਹੀਂ ਹੈ ਅਰਥਾਤ ਤੁਮਾਰੇ ਅੰਦਰ ਹੀ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਧਿਆਨ ਲਾ ਕੇ ਵੇਖੋ, ਉਹ ਤੁਹਾਥੋਂ ਦੂਰ ਨਹੀਂ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨੰਦਰਿ = ਨਜ਼ਰ, ਨਿਗਾਹ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "pues Él no está lejos de ti, sólo tienes que abrir los ojos."