[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਇਕਨਾ ਬਖਸਿ ਲਏ; ਧੁਰਿ ਲੇਖੈ ॥"
page = 1047
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "There are some, whom the Lord forgives, in accordance with His eternal writ."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕਈਆਂ ਨੂੰ ਪ੍ਰਭੂ ਆਪਣੀ ਪਰਾਪੂਰਬਲੀ ਲਿਖਤਾਕਾਰ ਅਨੁਸਾਰ ਮਾਫ਼ ਕਰ ਦਿੰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Some are forgiven, according to their pre-ordained destiny."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਕਨਾਂ ਕੋ ਲੇਖੇ ਸੇ ਆਦੋਂ ਹੀ ਬਖਸ਼ ਲੇਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਧੁਰੋਂ ਆਪਣੇ ਹੁਕਮ ਵਿਚ ਹੀ ਕਈ ਜੀਵਾਂ ਨੂੰ ਲੇਖੇ ਵਿਚ ਬਖ਼ਸ਼ ਲੈਂਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਲੇਖੈ ਬਖਸਿ ਲਏ = ਲੇਖੇ ਵਿਚ ਬਖ਼ਸ਼ ਲੈਂਦਾ ਹੈ, ਲੇਖਾ ਨਹੀਂ ਪੁੱਛਦਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "a algunos los perdona de acuerdo a Su Eterno Escrito,"