[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਚੁ ਸਾਲਾਹੀ. ਗਹਿਰ ਗੰਭੀਰੈ ॥"
page = 1048
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "I praise my True, Deep and Unfathomable Lord."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਆਪਣੀ ਸੱਚੇ, ਡੂੰਘੇ ਅਤੇ ਬੇਥਾਹ ਸੁਆਮੀ ਦਾ ਜੱਸ ਕਰਦਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I praise the true, profound and unfathomable Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "(ਗਹਿਰ ਗੰਭੀਰੈ) ਪਰਮੇਸਰ ਨਿਸਚੇ ਸਲਾਹੁਣ ਯੋਗ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮੈਂ ਤਾਂ ਉਸ ਅਥਾਹ ਤੇ ਵੱਡੇ ਜਿਗਰੇ ਵਾਲੇ ਪਰਮਾਤਮਾ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਕਰਦਾ ਹਾਂ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਚੁ = ਸਦਾ ਕਾਇਮ ਰਹਿਣ ਵਾਲਾ। ਸਾਲਾਹੀ = ਸਾਲਾਹੀਂ, ਮੈਂ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਕਰਦਾ ਹਾਂ। ਗਹਿਰ = ਗਹਿਰਾ, ਡੂੰਘਾ, ਅਥਾਹ। ਗੰਭੀਰ = ਵੱਡੇ ਜਿਗਰੇ ਵਾਲਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Alabo a mi Verdadero e Insondable Dios,"