[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸੋਰਠੇ ॥"
page = 1408
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Soraths."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੋਰਠੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Sorat'h"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sorad."