[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਦੇਖਿ ਬੀਚਾਰਿ; ਮੇਰਾ ਮਨੁ ਮਾਨਿਆ ॥੬॥"
page = 221
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "By seeing and reflecting over reality, my soul is reconciled to God."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਸਲੀਅਤ ਨੂੰ ਵੇਖਣ ਅਤੇ ਸੋਚਣ ਸਮਝਣ ਦੁਆਰਾ ਮੇਰੀ ਆਤਮਾ ਰੱਬ ਨਾਲ ਹਿਲ ਗਈ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Seeing and reflecting upon it, my mind surrenders. ||6||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਤੇ ਜਬ ਭਲੀ ਪ੍ਰਕਾਰ ਵੀਚਾਰ ਕਰ ਕੇ ਦੇਖਿਆ ਹੈ ਤਬ ਮੇਰਾ ਮਨ ਵਾਹਿਗੁਰੂ ਮੇਂ ਮਾਨਿਆ ਹੈ॥੬॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹਰ ਥਾਂ ਪ੍ਰਭੂ ਦਾ) ਦਰਸਨ ਕਰ ਕੇ ਪ੍ਰਭੂ ਦੇ ਗੁਣਾਂ ਨੂੰ ਵਿਚਾਰ ਕੇ ਉਸ ਦਾ 'ਮੇਰਾ, ਮੇਰਾ' ਆਖਣ ਵਾਲਾ ਮਨ (ਪ੍ਰਭੂ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਵਿਚ) ਗਿੱਝ ਜਾਂਦਾ ਹੈ ॥੬॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੇਰਾ ਮਨੁ = 'ਮੇਰਾ, ਮੇਰਾ' ਆਖਣ ਵਾਲਾ ਮਨ ॥੬॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y percibiendo y reflexionando, su mente cree y tiene Fe debido a su propia experiencia.(6)"