[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਉਤੈ ਸਖਿਨ ਭੂਪਹਿ ਸੁਧਿ ਦਈ ॥"
page = 1343

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਉਧਰ ਸਖੀ ਨੇ ਜਾ ਕੇ ਰਾਜੇ ਨੂੰ ਖ਼ਬਰ ਕਰ ਦਿੱਤੀ"