[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਇਹ ਬੀਚ ਤ੍ਰਿਯਾ ਪਤਿ ਆਨ ਪਰਿਯੋ ॥"
page = 833

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Husband seemed to be coming."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਇਸ ਦੌਰਾਨ ਉਸ ਇਸਤਰੀ ਦਾ ਪਤੀ ਆ ਗਿਆ।"