[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਅੰਤੁ ਨ ਜਾਪੈ ਪਾਰਾਵਾਰੁ ॥"
page = 5
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The bound of His this and yonder end is not known."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਸਦੇ ਇਸ ਤੇ ਉਸ ਕਿਨਾਰੇ ਦਾ ਥਹੁ ਪਤਾ ਜਾਣਿਆ ਨਹੀਂ ਜਾਂਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Its limits here and beyond cannot be perceived."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਉਰਾਰ ਪਾਰ ਕਾ ਭੀ ਅੰਤੁ ਨਹੀਂ ਜਾਨਾ ਜਾਤਾ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਇਸ ਦਾ ਉਰਲਾ ਤੇ ਪਾਰਲਾ ਬੰਨਾ ਕੋਈ ਨਹੀਂ ਦਿੱਸਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪਾਰਾਵਾਰੁ = ਪਾਰਲਾ ਤੇ ਉਰਲਾ ਬੰਨਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sus limites tangibles e intangibles no pueden ser medidos."