[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਮੁਨ ਬਾਲ ਦ੍ਵੈ ਜਿਨ ਮਾਰੀਯੋ ॥"
page = 281

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਪਰ ਉਨ੍ਹਾਂ ਦੋਹਾਂ ਮੁਨੀ ਬਾਲਕਾਂ ਨੂੰ ਮਾਰਨਾ ਨਹੀਂ,"