[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਚਰਨ ਕਮਲ ਕੀ ਓਟ; ਉਧਰੇ ਸਗਲ ਜਨ ॥"
page = 709
line = 17

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Seeking the refuge of the Lord's lotus feet, all men are emancipated."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸੁਆਮੀ ਦੇ ਕੰਵਲ ਚਰਨਾਂ ਦੀ ਪਨਾਹ ਲੈਣ ਦੁਆਰਾ ਸਾਰੇ ਇਨਸਾਨ ਪਰ ਉੱਤਰ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Through the Protection and Support of the Lord's lotus feet, all beings are saved."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸੰਪੂਰਨ ਸੰਤ ਜਨ ਹਰੀ ਕੇ ਚਰਨ ਕਮਲ ਕੀ ਓਟ ਲੇ ਕਰ ਇਸ ਸੰਸਾਰ ਸੇ ਉਧਰੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਪ੍ਰਭੂ ਦੇ ਸੋਹਣੇ ਚਰਨਾਂ ਦਾ ਆਸਰਾ ਲੈ ਕੇ ਸਾਰੇ ਜੀਵ (ਦੁਨੀਆ ਦੀ ਤਪਸ਼ ਤੋਂ) ਬਚ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਓਟ = ਆਸਰਾ। ਸਗਲ = ਸਾਰੇ। ਜਨ = ਮਨੁੱਖ। ਕਮਲ = ਕਉਲ ਫੁੱਲ। ਚਰਨ ਕਮਲ = ਕਉਲ ਫੁੱਲ ਵਰਗੇ ਚਰਨ ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Todos los que buscan los Pies de Loto del Señor son emancipados."