[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪ੍ਰਭ ਭਾਵੈ; ਮਾਨੁਖ ਗਤਿ ਪਾਵੈ ॥"
page = 277
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "If it pleases the Lord man obtains salvation."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜੇਕਰ ਸੁਆਮੀ ਨੂੰ ਚੰਗਾ ਲਗੇ, ਬੰਦਾ ਮੁਕਤੀ ਪਾ ਲੈਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "If it pleases God, one attains salvation."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੇਕਰ ਤਿਸ ਪ੍ਰਭੂ ਕੌ ਭਾਵੈ ਤੌ ਇਹ ਮਾਨਸ ਨਾਮ ਜਾਪ ਸੇਂ ਗਤੀ ਕੋ ਪਾਵਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇ ਪ੍ਰਭੂ ਨੂੰ ਚੰਗੀ ਲੱਗੇ ਤਾਂ ਮਨੁੱਖ ਨੂੰ ਉੱਚੀ ਆਤਮਕ ਅਵਸਥਾ ਦੇਂਦਾ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪ੍ਰਭ ਭਾਵੈ = ਜੇ ਪ੍ਰਭੂ ਨੂੰ ਚੰਗਾ ਲੱਗੇ। ਗਤਿ = ਉੱਚੀ ਆਤਮਕ ਅਵਸਥਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Si a Dios le place, uno logra la Salvación."