[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਨਿਆਇ ਅਤੇ ਇਨਸਾਫ ਦਾ ਮੁਖੜਾ ਚਮਕ ਪਿਆ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਰੁਖ਼ਿ ਅਦਲੋ ਇਨਸਾਫ਼ ਅਫ਼ਰੋਖ਼ਤਾ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "The face of justice, equity and fair play glistened, "