[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਕੇਵਡੁ ਹੈ ਦਰਗਾਹ, ਆਖਿ ਸੁਣਾਈਐ ॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "How the majesty of His court could be described."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "(ਉਸ ਦੀ) ਕਚਹਿਰੀ ਕਿੱਡੀਕੁ ਹੈ ਆਖਕੇ ਸੁਣਾਓ ਤਾਂ ਸਹੀ?"