[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਾਚੇ ਸਾਹ ਕੀ; ਮਨ ਮਹਿ ਟੇਕ ॥੩॥"
page = 197
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Within my mind is the support of the True Lender."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ ਚਿੱਤ ਅੰਦਰ ਸੱਚੇ ਸਾਹੂਕਾਰ ਦਾ ਹੀ ਆਸਰਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Within my mind is the Support of the True Banker. ||3||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਔਰ ਉਸੀ ਸਚੇ ਬਾਦਸ਼ਾਹ ਕੀ ਮਨ ਮੇਂ ਟੇਕ ਹੈ॥੩॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਮਨੁੱਖ ਦੇ ਮਨ ਵਿਚ ਸਦਾ ਕਾਇਮ ਰਹਿਣ ਵਾਲੇ ਸ਼ਾਹ-ਪਰਮਾਤਮਾ ਦਾ ਹੀ ਸਹਾਰਾ ਹੁੰਦਾ ਹੈ ॥੩॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਟੇਕ = ਸਹਾਰਾ ॥੩॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "sí, mi mente se apoya sólo en el Rey Verdadero.(3)"