[[content]]
assets = ["DGDG", "DDTK"]
type = "primary"
data = "ਅਭੇਖ ॥੧੯੨॥"
page = 10
line = 12

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Guiseless Lord ! 192"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਭੇਖ ਤੋਂ ਰਹਿਤ ਹੈਂ ॥੧੯੨॥"

