[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰਮੁਖਿ; ਨਾਮੇ ਲਗੈ ਪਿਆਰੁ ॥੧॥ ਰਹਾਉ ॥"
page = 1129
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "so that I may embrace love for Thine Name, by the Guru, grace. Pause."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਜੋ ਗੁਰਾਂ ਦੀ ਦਇਆ ਦੁਆਰਾ ਮੇਰੀ ਤੇਰੇ ਨਾਮ ਨਾਲ ਪ੍ਰੀਤ ਪੈ ਜਾਵੇ। ਠਹਿਰਾਉ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "that as Gurmukh, I may embrace love for Your Name. ||1||Pause||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਬ ਗੁਰਾਂ ਦ੍ਵਾਰੇ ਨਾਮ ਵਿਖੇ ਪਿਆਰ ਲਗਤਾ ਹੈ॥੧॥ ਰਹਾਉ ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਕਿ ਗੁਰੂ ਦੀ ਸਰਨ ਪੈ ਕੇ (ਮੇਰਾ) ਪਿਆਰ (ਤੇਰੇ) ਨਾਮ ਵਿਚ ਹੀ ਬਣਿਆ ਰਹੇ ॥੧॥ ਰਹਾਉ ॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗੁਰਮੁਖਿ = ਗੁਰੂ ਦੀ ਰਾਹੀਂ। ਨਾਮੇ = ਨਾਮ ਵਿਚ ਹੀ। ਲਗੈ = ਬਣਿਆ ਰਹੇ ॥੧॥ ਰਹਾਉ ॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "para que me vuelva Devoto de Tu Nombre, por la Gracia del Guru. (1-Pausa)"