[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੇ ਟੁੱਟੇ ਹੋਏ ਦਿਲ ਨੂੰ ਆਰਾਮ ਬਖਸ਼ਿਆ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਈਂ ਦਿਲਿ ਬਿਸ਼ਕਸਤਾ ਰਾ ਆਰਾਮ ਦਾਦ ॥੪੧੮॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "And provided succor to the heart-broken. (418)"