[[content]]
assets = ["DGDG", "DDTK"]
type = "primary"
data = "ਨਿਰਭੈ ਨਿਕਾਮ ॥"
page = 6
line = 2

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "All the Sages bow before Thee."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਤੂੰ) ਭੈ-ਰਹਿਤ ਅਤੇ ਨਿਸ਼ਕਾਮ ਹੈਂ,"

