[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਿਸਹਿ ਧਿਆਇ; ਸਦਾ ਮਨ ਅੰਦਰਿ ॥"
page = 269
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "ever meditate on Him within thy mind."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੇ ਚਿੱਤ ਅੰਦਰ ਹਮੇਸ਼ਾਂ ਉਸ ਦਾ ਆਰਾਧਨ ਕਰ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "meditate forever on Him within your mind."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਿਸੀ ਕੋ ਅਪਨੇ ਮਨ ਮੇਂ ਸਦੀਵ ਧਿਆਓ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੂੰ ਸਦਾ ਮਨ ਵਿਚ ਸਿਮਰ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤਿਸਹਿ = ਉਸ ਨੂੰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Permanece inmerso en Él,"