[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਹੁਰਿ ਸਭਨ ਮੈ ਬੈਠਿ; ਆਪੁ ਕੋ ਪੂਜ ਕਹਾਊ ॥"
page = 835

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Being seated (as Raja) I am worshipped."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਫਿਰ ਸਾਰਿਆਂ ਵਿਚ ਬੈਠ ਕੇ (ਮੈਂ) ਪੂਜਣਯੋਗ ਅਖਵਾਉਂਦਾ ਹਾਂ।"