[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤੇਰਾ ਭਰੋਸਾ ਪਿਆਰੇ ॥"
page = 912
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "I only lean on Thee, O my Beloved."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੈਨੂੰ ਸਿਰਫ ਤੇਰਾ ਹੀ ਆਸਰਾ ਹੈ, ਹੇ ਮੇਰੇ ਪ੍ਰੀਤਮ!"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "I place my faith in You alone, O Beloved Lord."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਯਾਰੇ! ਮੇਰੇ ਕੋ ਏਕ ਤੇਰਾ ਹੀ ਆਸਰਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਮੇਰੇ ਪਿਆਰੇ ਪ੍ਰਭੂ! ਮੈਨੂੰ ਸਿਰਫ਼ ਤੇਰਾ ਆਸਰਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਭਰੋਸਾ = ਆਸਰਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Oh Señor, sólo Tú eres mi apoyo;"