[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਧਰਣੀ ਤਲਾ ਮਹਿ ਧੰਨਿ ॥੪੬੭॥"
page = 672

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Well versed in music and full of essence, She was fortunate enough on earth.467."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਹ) ਧਰਤੀ ਦੇ ਤਲ ਵਿਚ ਧੰਨ ਸੀ ॥੪੬੭॥"