[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਅਸੰਖ ਪੂਜਾ; ਅਸੰਖ ਤਪ ਤਾਉ ॥"
page = 3
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Countless are Thine worships and countless they who practise penance."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਣਗਿਣਤ ਹਨ ਤੇਰੀਆਂ ਉਪਾਸ਼ਨਾਂ ਅਤੇ ਅਣਗਿਣਤ ਹਨ ਜੋ ਤਪੱਸਿਆ ਕਰਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Countless worship services, countless austere disciplines."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਅਗਿਣਤ ਪ੍ਰਕਾਰ ਕੀ ਪੂਜਾ ਹੈ, ਅਨੇਕ ਪ੍ਰਕਾਰ ਕਾ ਤਪੁ ਹੈ⁽¹⁾ ਔਰ ਅਨੇਕ ਹੀ ਤਿਸ ਤਪ ਕੇ ਤਾਉ ਸਹਾਰਨੇ ਵਾਲੇ ਤਪੀ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਕਈ ਜੀਵ ਪੂਜਾ ਕਰ ਰਹੇ ਹਨ ਅਤੇ ਅਨਗਿਣਤ ਹੀ ਜੀਵ ਤਪ ਸਾਧ ਰਹੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤਪ = ਤਾਉ-ਤਪਾਂ ਦਾ ਤਪਣਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Incontables las religiones y las maneras de alabar."