[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਰਾਮਕਲੀ ਮਹਲਾ ੪ ਘਰੁ ੧ ॥"
page = 880
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Ramkali 4th Guru."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰਾਮਕਲੀ ਚੌਥੀ ਪਾਤਿਸ਼ਾਹੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Raamkalee, Fourth Mehl, First House:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਰਾਗ ਰਾਮਕਲੀ, ਘਰ ੧ ਵਿੱਚ ਗੁਰੂ ਰਾਮਦਾਸ ਜੀ ਦੀ ਬਾਣੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Ramkali, Mejl Guru Ram Das, Cuarto Canal Divino."