[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਗੰਜ ਭੰਜ ਭਰਮ ਹੈ ॥"
page = 128

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He is invincible and destroys illusions."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਹੇ) ਅਗੰਜ! (ਤੂੰ) ਭਰਮਾਂ ਨੂੰ ਭੰਨਦਾ ਹੈਂ;"