[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਇਸੁ ਤਨ ਮਨ ਮਧੇ; ਮਦਨ ਚੋਰ ॥"
page = 1194
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Within this body and mind, lives the cupid, the god of lust,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਇਸ ਦੇਹਿ ਅਤੇ ਚਿੱਤ ਅੰਦਰ, ਵਿਸ਼ੇ ਭੋਗ ਦਾ ਦੇਵਤਾ ਚੋਰ ਕਾਮਦੇਵ ਰਹਿੰਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Within the body and mind are thieves like sexual desire,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਸ ਸਰੀਰ ਕੇ ਮਧੁ ਜੋ ਮਨੁ ਹੈ ਤਿਸ ਮਨ ਮੇਂ ਕਾਮ ਰੂਪੀ ਚੋਰ ਰਹਿਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਮੇਰੀ 'ਚੰਚਲ ਬੱਧ' ਦੇ ਕਾਰਨ, ਹੁਣ) ਮੇਰੇ ਇਸ ਤਨ ਮਨ ਵਿਚ ਕਾਮਦੇਵ ਚੋਰ ਆ ਵੱਸਿਆ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਧੇ = ਵਿਚ। ਮਦਨ = ਕਾਮਦੇਵ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "En el seno del ser vive Kamdev, el dios de la lujuria,"