[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਦੂਜਾ ਖੇਲੁ ਕਰਿ; ਦਿਖਲਾਇਆ ॥"
page = 73
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "and setting afoot the play of duality hast exhibited it."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਦਵੈਤ-ਭਾਵ ਦੀ ਖੇਡ ਨੂੰ ਸਾਜ ਕੇ ਪ੍ਰਗਟ ਕੀਤਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "You created the play of duality, and staged it."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਅਗ੍ਯਾਨੀ ਜਨੋਂ ਕੋ (ਦੂਜਾ ਖੇਲੁ) ਮਾਇਆ ਕਾ ਖੇਲ ਕਰ ਕੇ ਦਿਖਲਾਇ ਦੀਆ ਹੈ॥☬ਅਬ ਗ੍ਯਾਨੀਓਂ ਕਾ ਨਿਸਚਾ ਕਹਤੇ ਹੈਂ:"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਇਹ ਤੈਥੋਂ ਵੱਖਰਾ ਦਿੱਸਦਾ) ਮਾਇਆ ਦਾ ਜਗਤ-ਤਮਾਸ਼ਾ ਤੂੰ ਆਪ ਹੀ ਬਣਾ ਕੇ ਵਿਖਾ ਦਿੱਤਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਦੂਜਾ ਖੇਲੁ = ਆਪਣੇ ਤੋਂ ਵੱਖਰਾ ਤਮਾਸ਼ਾ। ਕਰਿ = ਕਰ ਕੇ, ਪੈਦਾ ਕਰ ਕੇ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "a través de Ti se desenvuelve el teatro de Maya"