[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਿਜੈ ਸਿੰਘ ਇਕ ਦਿਨ ਗਏ; ਆਖੇਟਕ ਕੇ ਕਾਜ ॥"
page = 984

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "One day Vijay Singh went out for the purpose of hunting,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਬਿਜੈ ਸਿੰਘ ਇਕ ਦਿਨ ਸ਼ਿਕਾਰ ਖੇਡਣ ਗਿਆ"