[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤੇਰੀ ਟੇਕ; ਤੇਰੇ ਗੁਣ ਗਾਹਿ ॥"
page = 1147
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Through Thy prop, sing I Thine praises."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਆਸਰੇ ਰਾਹੀਂ ਮੈਂ ਤੇਰੀਆਂ ਸਿਫਤਾਂ ਗਾਇਨ ਕਰਦਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "With Your Support, I sing Your Glorious Praises."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤੇਰੀ ਹੀ ਓਟ ਮੇਂ ਤੇਰੇ ਗੁਣੋਂ ਕੋ ਗਾਵਤਾ ਹੂੰ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਰਭੂ! (ਸਭ ਜੀਵ) ਤੇਰੇ ਹੀ ਸਹਾਰੇ ਹਨ, ਤੇਰੇ ਹੀ ਗੁਣ ਗਾਂਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਗਾਹਿ = (ਜਿਹੜੇ ਮਨੁੱਖ) ਗਾਂਦੇ ਹਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "sí, eres mi Único Soporte y mi único deseo es cantar Tu Alabanza."