[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਰਾਜੰ ਪ੍ਰਭਾ ਹੈਂ ॥"
page = 6
line = 11

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That Thou art the glory of kingdom!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਹੇ ਪ੍ਰਭੂ!) ਤੂੰ ਰਾਜਿਆਂ ਦਾ ਤੇਜ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਕਿ, ਰਾਜੰ ਪ੍ਰਭਾ ਹੈਂ ॥"