[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕੁਕ੍ਰਿਤ ਕਰਮ ਜੇ ਜਗ ਮੈ ਕਰਹੀਂ ॥"
page = 48

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "And because of evil actions"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਜਿਹੜਾ ਸੰਸਾਰ ਵਿਚ ਮਾੜੇ ਕਰਮ ਕਰਦਾ ਹੈ,"