[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮਹਲਾ ੪ ਗਉੜੀ ਪੂਰਬੀ ॥"
page = 168
line = 16

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "4th Guru, Gauri Purbi."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਪਾਤਸ਼ਾਹੀ ਚੌਥੀ, ਗਊੜੀ ਪੂਰਬੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Fourth Mehl, Gauree Poorbee:"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Gauri Purbi, Mejl Guru Ram Das, Cuarto Canal Divino."