[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਾਜ ਮੇਧਿ ਇਕੀਸ ਪ੍ਰਕਾਰਾ ॥"
page = 286

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Ten Rajsu Yajnas and twenty-one kinds of Ashvamedha Yajna were performed."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਜਿਹੜੇ ਜਨਮੇਜਾ ਵੀ ਨਾ ਕਰ ਸਕਿਆ।"