[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਤਾਂ ਤੇਰਾ ਮਨੋਰਥ ਅਵੱਸ਼ ਸਮਪੂਰਨ ਹੋ ਜਾਵੇਗਾ ।"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਗੌਹਰਿ ਮਕਸੂਦ ਤੂ ਹਾਸਿਲ ਸ਼ਵਦ ॥੩੬੪॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Every such person who with a chaste mind and firm faith"