[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਨ ਮਹਿ ਹੋਤੀ; ਕੋਟਿ ਉਪਾਧਿ ॥"
page = 327
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "There were millions if ills in the body."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਰੀਰ ਅੰਦਰ ਕ੍ਰੋੜਾ ਹੀ ਰੋਗ ਸਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "My body was afflicted with millions of diseases."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਤਨ ਮੇਂ ਕ੍ਰੌੜਾਂ ਪ੍ਰਕਾਰ ਕੀ ਉਪਾਧਿ ਹੋਤੀ ਥੀ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਮੇਰੇ ਸਰੀਰ ਵਿਚ ਵਿਕਾਰਾਂ ਦੇ) ਕ੍ਰੋੜਾਂ ਬਖੇੜੇ ਸਨ;"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਤਨ ਮਹਿ = ਸਰੀਰ ਵਿਚ। ਹੋਤੀ = ਹੁੰਦੀਆਂ ਸਨ। ਕੋਟਿ ਉਪਾਧਿ = ਕ੍ਰੋੜਾਂ ਬਖੇੜੇ (ਵਿਕਾਰਾਂ ਦੇ)।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Millones de aflicciones que infestaron mi cuerpo se convirtieron en Éxtasis,"