[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮਰਣਾ ਮੁਲਾ; ਮਰਣਾ ॥"
page = 24
line = 8

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Death, O Maulvi! death must come."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੌਤ, ਹੇ ਮੇਲਵੀ! ਮੌਤ ਜ਼ਰੂਰ ਆਏਗੀ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Death, O Mullah-death will come,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਮੁਲਾਂ! ਤੂੰ  ਐਸੇ ਨਿਸਚੈ ਕਰੁ ਕਿ ਮੁਲਾਂ ਨੇ ਭੀ ਮਰਨਾ ਹੈ ਔਰੁ ਕਾਜੀ ਨੇ ਭੀ ਮਰਨਾ ਹੈ ਵਾ ਸਰਬ ਪ੍ਰਪੰਚ ਨੇ ਭੀ ਮਰਨਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਮੁੱਲਾਂ! ਮੌਤ (ਦਾ ਡਰ) ਹਰੇਕ ਦੇ ਸਿਰ ਉੱਤੇ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੁਲਾ = ਹੇ ਮੁੱਲਾਂ! ਮਰਣਾ = ਮੌਤ, ਮੌਤ ਦਾ ਡਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "La muerte le llegará a todos, oh Mulá."