[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਕਿ ਚੰਦ੍ਰੰ ਪ੍ਰਭਾ ਛੈ ॥੩੧੫॥"
page = 660

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "She was mercurial and glorious.315."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਜਾਂ ਚੰਦ੍ਰਮਾ ਦੀ ਪ੍ਰਭਾ ਹੈ ॥੩੧੫॥"