[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਤਬ ਹੀ ਪੈਰਿ ਨਦੀ ਤਹ ਆਵੈ ॥"
page = 941

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "At the Sunset, she used to swim across the river and there (to see him)."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤਦੋਂ ਉਹ ਨਦੀ ਤਰ ਕੇ ਉਥੇ ਆ ਜਾਂਦੀ।"