[[content]]
assets = ["DGDG", "DDTK"]
type = "primary"
data = "ਅਲੈ ॥"
page = 10
line = 10

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "O Indestructible Lord !"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਵਿਨਾਸ਼ੀ,"

