[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਹਸਿ ਹਸਿ ਸੋਗੁ ਕਰਤ ਬੇਗਾਨਾ ॥੧॥"
page = 389
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He laugh in glee, while mourning for others."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੋਰਨਾਂ ਦਾ ਮਾਤਮ ਕਰਦਾ ਹੋਇਆ ਉਹ ਖੁਸ਼ੀ ਵਿੱਚ ਹੱਸਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "he laughs with glee, while mourning for others. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਸੀ ਪ੍ਰਕਾਰ ਜੋ ਲਾਭਕਰ ਹਸ ਹਸ ਪੜਤਾ ਹੈ ਹਾਨਿ ਕਰ ਸੋਗ ਕਰਤਾ ਹੈ, ਸੋ ਬੇਗਾਨਾ ਮੂਰਖ ਹੈ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੇਹੜਾ ਕੋਈ ਓਪਰਾ ਮਨੁੱਖ (ਉਸ ਦੇ ਮਰਨ ਤੇ ਅਫ਼ਸੋਸ ਕਰਨ ਆਉਂਦਾ ਹੈ ਉਹ) ਹੱਸ ਹੱਸ ਕੇ ਅਫ਼ਸੋਸ ਕਰਦਾ ਹੈ ॥੧॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਹਸਿ = ਹੱਸ ਕੇ। ਸੋਗੁ = (ਕਿਸੇ ਦੀ ਮੌਤ ਉੱਤੇ) ਅਫ਼ਸੋਸ। ਬੇਗਾਨਾ = ਓਪਰਾ ਮਨੁੱਖ ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "se ríe mientras lamenta el dolor de otros. (1)"