[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੁਕਬਿ ਤੁਪਕ ਕੇ ਨਾਮ ਪਛਾਨਹੁ ॥੯੪੯॥"
page = 774

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Saying firstly the word “Nishi-patnani”, add the words “Sat-char-ari-shatru” at the end know the names of Tupak.949."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਇਸ ਨੂੰ) ਕਵੀ ਜਨੋ, ਤੁਪਕ ਦਾ ਨਾਮ ਸਮਝੋ ॥੯੪੯॥"