[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਵੈਦ ਨ ਭੋਲੇ ਦਾਰੂ ਲਾਇ ॥੧॥"
page = 1256
line = 14

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "O ignorant physician, minister thou not any medicine to me."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਹੇ ਬੇਸਮਝ ਹਕੀਮ! ਤੂੰ ਮੈਨੂੰ ਕੋਈ ਦਵਾਈ ਨਾਂ ਦੇ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "O foolish doctor, don't give me medicine. ||1||"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਭੋਲੇ ਵੈਦ! ਦਾਰੂ ਨ ਲਗਾਉ॥੧॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭੋਲੇ ਵੈਦ! ਤੂੰ ਦਵਾਈ ਨਾਹ ਦੇਹ (ਕਿਸ ਕਿਸ ਰੋਗ ਦਾ ਤੂੰ ਇਲਾਜ ਕਰੇਂਗਾ?) ॥੧॥"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਵੈਦ ਭੋਲੇ = ਹੇ ਭੋਲੇ ਅੰਞਾਣ ਵੈਦ! ਦਾਰੂ ਨ ਲਾਇ = ਦਵਾਈ ਨਾਹ ਦੇਹ ॥੧॥"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "y enfermedades, el cuerpo se destruye."