[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਰਮ ਧਰਮ ਕਰਿ; ਮੁਕਤਿ ਮੰਗਾਹੀ ॥"
page = 1024
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Practising religious rituals, they sought salvation,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮਜ਼ਹਬੀ ਕਰਮਕਾਡ ਕਰਨ ਦੁਆਰਾ, ਉਹ ਕਲਿਆਣ ਦੀ ਚਾਹਨਾਂ ਕਰਦੇ ਸਨ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Practicing religious rituals, they sought liberation,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਕਰਮ ਧਰਮ ਕਰ ਕੇ ਮੁਕਤੀ ਮਾਂਗਤੇ ਥੇ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਦੁਆਪੁਰ  ਵਾਲੇ ਮਨੁੱਖ ਦਾਨ-ਪੁੰਨ ਤੀਰਥ ਆਦਿਕ) ਕਰਮ ਕਰ ਕੇ ਮੁਕਤੀ ਮੰਗਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮੰਗਾਹੀ = ਮੰਗਦੇ ਹਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Esperaban lograr la liberación a través de actos guiados por el intelecto,"