[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਤਬ ਲਗੁ; ਨਿਹਚਲੁ ਨਾਹੀ ਚੀਤੁ ॥"
page = 278
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "so long his mind is not at rest."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਦੋਂ ਤਾਈਂ ਉਸ ਦਾ ਮਨ ਸਥਿਰ ਨਹੀਂ ਹੁੰਦਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "his mind shall not come to rest."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤਬ ਤਕ ਇਸ ਕਾ ਚਿਤ ਅਚਲ ਨਹੀਂ ਹੋਤਾ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਤਦ ਤਕ ਇਸ ਦਾ ਮਨ ਟਿਕਾਣੇ ਨਹੀਂ ਆਉਂਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਨਿਹਚਲੁ = ਅਡੋਲ, ਟਿਕਾਣੇ, ਥਾਂ ਸਿਰ। ਚੀਤੁ = ਚਿੱਤ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "no hallará reposo en su mente."