[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੋਤਿ ਸਰੂਪੀ; ਤਤ ਅਨੂਪ ॥"
page = 344
line = 1

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Master is the embodiment of light, essence of all, and incomparable."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮਾਲਕ ਪ੍ਰਕਾਸ਼ ਦਾ ਸਾਰਿਆਂ ਦਾ ਜੌਹਰ ਅਤੇ ਲਾਸਾਨੀ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He is the Embodiment of light, the incomparable essence."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋਤਿ ਪ੍ਰਕਾਸ ਰੂਪ ਹੈ ਔਰ ਤਤ ਰੂਪ ਉਪਮਾ ਸੇ ਰਹਤ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੋ ਨਿਰਾ ਨੂਰ ਹੀ ਨੂਰ ਹੈ, ਜੋ ਸਾਰੇ ਜਗਤ ਦਾ ਅਸਲਾ ਹੈ, ਜਿਸ ਵਰਗਾ ਹੋਰ ਕੋਈ ਨਹੀਂ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜੋਤਿ ਸਰੂਪੀ = ਉਹ ਪ੍ਰਭੂ ਜੋ ਨਿਰਾ ਨੂਰ ਹੀ ਨੂਰ ਹੈ। ਤਤ = ਅਸਲਾ, ਸਭ ਦਾ ਮੁੱਢ। ਅਨੂਪ = ਜਿਸ ਵਰਗਾ ਹੋਰ ਕੋਈ ਨਹੀਂ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "la Encarnación de Luz,"