[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਐਸੀ ਢੀਠ ਨਾਰਿ ਤੇ ਡਰਿਯੈ ॥੨੨॥"
page = 866

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "‘God be benevolent and one must be fearful of such a person.’(22)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਜਿਹੀ ਢੀਠ ਨਾਰ ਤੋਂ ਡਰਨਾ ਹੀ ਭਲਾ ॥੨੨॥"