[[content]]
assets = ["GSNL"]
type = "translation"
language = "pa"
data = "ਇਹੀ ਰੱਬ ਦੀ ਯਾਦ ਹੈ, ਹੋਰ ਕੋਈ ਯਾਦ ਨਹੀਣ,"

[[content]]
assets = ["GSNL"]
type = "primary"
data = "ਯਾਦਿ ਹੱਕ ਈਨਸਤੋ ਦੀਗਰ ਯਾਦ ਨੀਸਤ ॥"

[[content]]
assets = ["KEGP"]
type = "translation"
language = "en"
data = "Great is the true Guru who has blessed persons like me the eternal life only"