[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਦੇਸਨ ਦੇਸ ਨਰੇਸ ਦਏ ਸੰਗਿ ॥"
page = 218

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਦੇਸ਼ਾਂ ਦੇਸ਼ਾਂ ਦੇ ਰਾਜੇ (ਉਸ ਦੇ) ਨਾਲ ਕਰ ਦਿੱਤੇ"