[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੋ ਧੁਰਿ ਰਖਿਅਨੁ. ਮੇਲਿ ਮਿਲਾਇ ॥"
page = 665
line = 12

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "They, whom the Primal Being keeps united in His union,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਨ੍ਹਾਂ ਨੂੰ ਆਦੀ ਨਿਰੰਕਾਰ ਆਪਣੇ ਮਿਲਾਪ ਅੰਦਰ ਮਿਲਾਈ ਰੱਖਦਾ ਹੈ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Those whom the Primal Lord keeps united in His Union,"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਜਨ ਧੁਰੋਂ ਸਤ ਸੰਗਤ ਕੇ ਮੇਲ ਮੇਂ ਮਿਲਾਇ ਕਰ ਰਾਖ ਲਏ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਜਿਨ੍ਹਾਂ ਮਨੁੱਖਾਂ ਨੂੰ ਉਸ (ਪਰਮਾਤਮਾ) ਨੇ ਧੁਰ ਤੋਂ ਹੀ ਆਪਣੇ ਚਰਨਾਂ ਵਿਚ ਜੋੜ ਰੱਖਿਆ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਰਖਿਅਨੁ = ਉਸ (ਪਰਮਾਤਮਾ) ਨੇ ਰੱਖੇ ਹਨ। ਮਿਲਾਇ ਰਖਿਅਨੁ = ਉਸ ਨੇ ਮਿਲਾ ਰੱਖੇ ਹਨ। ਜੋ = ਜਿਨ੍ਹਾਂ (ਮਨੁੱਖਾਂ) ਨੂੰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "A quienes el Ser Primordial conserva Consigo en Su Unión,"