[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮਿਥਿਆ; ਨਾਹੀ ਰਸਨਾ ਪਰਸ ॥"
page = 274
line = 3

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "He, whose tongue touches not falsehood,"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਜਿਸ ਦੀ ਜੀਭਾ ਝੂਠ ਦੇ ਨਾਲ ਲਗਦੀ ਤਕ ਨਹੀਂ,"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "One whose tongue does not touch falsehood;"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਅਪਰਸ ਰਸਨਾ ਸੇ ਝੂਠ ਨਹੀਂ ਬੋਲਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਜੋ ਮਨੁੱਖ ਜੀਭ ਨਾਲ ਝੂਠ ਨੂੰ ਛੋਹਣ ਨਹੀਂ ਦੇਂਦਾ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਮਿਥਿਆ = ਝੂਠ। ਪਰਸ = ਛੋਹ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Los labios no hablan falsedad en aquél que ama al Señor"