[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਇਕਿ ਆਵਹਿ; ਇਕਿ ਜਾਵਹਿ ਆਈ ॥"
page = 353
line = 5

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Some are born, and some having been born, die away."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਕਈ ਜੰਮਦੇ ਹਨ ਅਤੇ ਕਈ ਜੰਮ ਕੇ ਮਰ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Some come, and after they come, they go."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਫਿਰਿ ਕੈਸਾ ਹੈ ਸੰਸਾਰ ਸਮੁੰਦ੍ਰ ਏਕ ਤੋ ਜਨਮ ਲੈਕਰ ਆਉਂਦੇ ਹੈਂ ਏਕ ਆਇ ਕਰ ਚਲੇ ਜਾਂਦੇ ਹੈਂ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਅਨੇਕਾਂ ਜੀਵ ਜਗਤ ਵਿਚ ਜਨਮ ਲੈਂਦੇ ਹਨ ਤੇ (ਉੱਚੀ ਆਤਮਕ ਅਵਸਥਾ ਦੀ ਪ੍ਰਾਪਤੀ ਤੋਂ ਬਿਨਾ) ਨਿਰੇ ਜੰਮਦੇ ਹੀ ਹਨ ਤੇ (ਫਿਰ ਇਥੋਂ) ਚਲੇ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਇਕਿ = {ਪੜਨਾਂਵ 'ਇਕ' ਤੋਂ ਬਹੁ-ਵਚਨ} ਕਈ, ਅਨੇਕਾਂ ਜੀਵ। ਆਵਹਿ = ਜਗਤ ਵਿਚ ਜਨਮ ਲੈਂਦੇ ਹਨ। ਆਈ = ਆ ਕੇ, ਜਨਮ ਲੈ ਕੇ। ਜਾਵਹਿ = (ਖ਼ਾਲੀ ਹੀ) ਚਲੇ ਜਾਂਦੇ ਹਨ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Algunos nacen para morir y volver a morir"