[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਖੇਮ ਕੁਸਲ ਭਇਆ ਇਸਨਾਨਾ ॥"
page = 624
line = 2

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "With peace and pleasure, I, now, take the bath."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਰਾਮ ਅਤੇ ਅਨੰਦ ਨਾਲ ਹੁਣ, ਮੈਂ ਨਹਾਉਂਦਾ ਹਾਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "With joy and pleasure, I take my purifying bath."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਇਸੀ ਸੇ ਸੁਖ ਅਨੰਦ ਸਾਥ ਇਸਨਾਨ ਭਇਆ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ ਅੰਦਰ ਆਤਮਕ ਸੁਖ ਆਨੰਦ ਬਣ ਗਿਆ ਹੈ-ਇਹ ਹੈ ਇਸ਼ਨਾਨ (ਜੋ ਮੈਂ ਗੁਰੂ-ਸਰ ਵਿਚ ਕੀਤਾ ਹੈ)।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਖੇਮ ਕੁਸਲ = ਆਤਮਕ ਸੁਖ ਆਨੰਦ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Estoy en Éxtasis como si me hubiera dado un Baño Eterno."