[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਜਨੁ ਖੇਲ ਫਾਗਿ ਧਮਾਰ ॥੩੦੬॥"
page = 582

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Someone is coming running and is not retracing even two steps backwards, they are striking blows like playing Holi.306."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਮਾਨੋ ਫਾਗ ਖੇਡ ਰਹੇ ਹੋਣ ॥੩੦੬॥"