[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਜੀਅ ਪ੍ਰਾਨ ਧਨੁ; ਹਰਿ ਕੋ ਨਾਮੁ ॥"
page = 376
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "God's Name is my soul, life and wealth."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਰੱਬ ਦਾ ਨਾਮ ਮੇਰੀ ਆਤਮਾ ਜਿੰਦ-ਜਾਨ ਅਤੇ ਦੌਲਤ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Naam, the Name of the Lord, is my soul, my life, my wealth."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਮੇਰਾ ਜੀਉ, ਪ੍ਰਾਨ, ਧਨ ਸਭ ਹਰਿ ਕੋ ਨਾਮ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ!) ਜਿੰਦ ਵਾਸਤੇ ਪ੍ਰਾਣਾਂ ਵਾਸਤੇ ਪਰਮਾਤਮਾ ਦਾ ਨਾਮ (ਹੀ ਅਸਲ) ਧਨ ਹੈ,"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜੀਅ ਧਨੁ = ਜਿੰਦ ਦਾ ਧਨ। ਪ੍ਰਾਨ ਧਨੁ = ਪ੍ਰਾਣਾਂ ਲਈ ਧਨ। ਕੋ = ਦਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "El Nombre del Señor es mi vida"