[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਤਿਲਕੜੀਆ ਛੰਦ ॥"
page = 248

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "TILKARIYA STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਤਿਲਕੜੀਆ ਛੰਦ"