[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਕਵਨੁ ਅਸਥਾਨੁ; ਜੋ. ਕਬਹੁ ਨ ਟਰੈ ॥"
page = 237
line = 7

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Which is the Place that never perishes?"

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਉਹ ਕਿਹੜੀ ਥਾਂ ਹੈ ਜਿਹੜੀ ਕਦਾਚਿੱਤ ਨਾਸ਼ ਨਹੀਂ ਹੁੰਦੀ?"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "What is that place which never perishes?"

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਗੁਰੋ! ਵਹੁ ਕੌਨ ਸਾ ਅਸਥਾਨ ਹੈ, ਜੋ ਕਬੀ ਨਾਸ ਨਹੀਂ ਹੋਤਾ?"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ!) ਉਹ ਕੇਹੜਾ ਥਾਂ ਹੈ ਜੇਹੜਾ ਸਦਾ ਅਟੱਲ ਰਹਿੰਦਾ ਹੈ?"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਕਵਨੁ = ਕੇਹੜਾ? ਨ ਟਰੈ = ਨਾਸ ਨਹੀਂ ਹੁੰਦਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "¿Cuál es el lugar que no tenemos que dejar?"