[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਇਤਿ ਦਲੀਪ ਰਾਜ ਸਮਾਪਤੰ ॥੮॥੫॥"
page = 624

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "End of the description of the rule of Dileep and his departure for heaven."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਇਥੇ ਦਲੀਪ ਰਾਜੇ ਦੇ ਰਾਜ ਦੀ ਸਮਾਪਤੀ ॥੮॥੫॥"