[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੰਗੀਤ ਪਧਿਸਟਕਾ ਛੰਦ ॥"
page = 250

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "SANGEET PADHISTAKA STANZA"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਸੰਗੀਤ ਪਧਿਸਟਕਾ ਛੰਦ"