[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਸਾਧਸੰਗਤਿ ਵਿਟਹੁ, ਕੁਰਬਾਣੀ ॥੬॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "I am sacrifice unto the holy congregation."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "(੯) ਸਾਧ ਸੰਗਤ ਤੋਂ ਕੁਰਬਾਨ ਜਾਈਏ।"