[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਬਿਖਿਆ ਮੈਲੁ; ਬਿਖਿਆ ਵਾਪਾਰੁ ॥"
page = 1262
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "and he deals in sins, the filthy sins."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਅਤੇ ਉਹ ਪਾਪਾ, ਗੰਦੇ ਪਾਪਾਂ ਦਾ ਵਣਜ ਕਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He deals in corruption, filth and vice."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਜੋ ਬਿਸ੍ਯ ਮੈਲ ਰੂਪ ਹੈ ਬਿਸ੍ਯੋਂ ਕਾ ਵਾਪਾਰੁ ਕਰਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਉਹਨਾਂ ਦੇ ਮਨ ਨੂੰ) ਮਾਇਆ (ਦੇ ਮੋਹ) ਦੀ ਮੈਲ (ਸਦਾ ਚੰਬੜੀ ਰਹਿੰਦੀ ਹੈ)। (ਉਹਨਾਂ ਨੇ ਇਸ ਵਿਚਾਰ ਨੂੰ) ਮਾਇਆ ਕਮਾਣ ਦਾ ਹੀ ਵਪਾਰ ਬਣਾਇਆ ਹੁੰਦਾ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਬਿਖਿਆ = ਮਾਇਆ। ਵਪਾਰੁ = ਵਣਜ, ਕਾਰ-ਵਿਹਾਰ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Él vive en medio de la corrupción, la suciedad y el vicio,"