[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਭਾਗੜਦੰਗ ਭਾਗੇ ਕਾਗੜਦੰਗ ਕੇਤੰ ॥"
page = 260

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "In this way the war was conquered and in this war many warriors fled away"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਨੇਕਾਂ (ਵੈਰੀ) ਭੱਜ ਗਏ।"