[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਸੇ ਹਮਲਾ ਕਰਦੰਦ ਬਸੇ ਜ਼ਖ਼ਮ ਖ਼ੁਰਦ ॥"
page = 1391

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "He made several attacks"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਉਸ ਨੇ ਬਹੁਤ ਹਮਲੇ ਕੀਤੇ ਅਤੇ ਬਹੁਤ ਸਾਰੇ ਜ਼ਖ਼ਮ ਖਾਏ।"