[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਇਤਿ ਨਲਿਨੀ ਸੁਕ ਉਨੀਸਵੋ ਗੁਰੂ ਬਰਨਨੰ ॥੧੯॥"
page = 670

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "End of the description of the adoption of the Parrot as the Nineteenth Guru."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਇਥੇ 'ਨਲਨੀ ਸੁਕ' ਉਨ੍ਹੀਵੇਂ ਗੁਰੂ ਦਾ ਵਰਣਨ ਸਮਾਪਤ ॥੧੯॥"