[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਅਭੰਜ ਹੈਂ ॥"
page = 3
line = 6

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Thou art Unbreakable Lord!"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਟੁੱਟ ਹੈਂ,"

[[content]]
assets = ["DDTK"]
type = "primary"
data = "ਅਭੰਜ ਹੈਂ ॥"