[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਮੈ. ਹੋਰੁ ਨ ਕੋਈ; ਤੁਧੈ ਜੇਹਾ ॥"
page = 112
line = 18

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "For me, there is none else like Thee."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਮੇਰੇ ਨਹੀਂ ਹੋਰਸ ਕੋਈ ਤੇਰੇ ਵਰਗਾ ਨਹੀਂ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "For me, there is no other like You."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਜੈਸਾ ਮੇਰੇ ਕੋ ਔਰ ਕੋਈ ਪ੍ਰਤੀਤ ਨਹੀਂ ਹੋਤਾ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "ਹੇ ਪ੍ਰਭੂ! ਤੇਰੇ ਵਰਗਾ ਮੈਨੂੰ ਹੋਰ ਕੋਈ ਨਹੀਂ ਦਿੱਸਦਾ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਜੇਹਾ = ਵਰਗਾ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Para mí no hay nadie como Tú;"