[[content]]
assets = ["VGRG"]
type = "primary"
data = "ਪੈਰੀ ਪੈ, ਜਗੁ ਪੈਰੀ ਪਾਇਆ ॥੧੦॥"

[[content]]
assets = ["JVBG"]
type = "translation"
language = "en"
data = "He humbly bows at the Guru's feet and the whole world falls at his feet."

[[content]]
assets = ["VBGS"]
type = "translation"
language = "pa"
data = "ਪੈਰੀ ਪੈਕੇ ਜਗਤ ਨੂੰ ਨਿਵਾ ਲੈਂਦੇ ਹਨ (ਨਿੰਮ੍ਰਤਾ ਨਾਲ ਕਾਰਜ ਰਾਸ ਕਰਦੇ ਹਨ)।"