[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਗੁਰ ਕੀ ਬਾਣੀ ਸਿਉ; ਰੰਗੁ ਲਾਇ ॥"
page = 387
line = 13

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Embrace through the love for Guru's hymns."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੂੰ ਗੁਰਾਂ ਦੀ ਬਾਣੀ ਨਾਲ ਪਿਆਰ ਪਾ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "Embrace love for the Word of the Guru's Bani."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਗੁਰੋਂ ਕੀ ਬਾਣੀ ਸੇ (ਰੰਗੁ) ਪ੍ਰੇਮ ਲਗਾਉ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ!) ਸਤਿਗੁਰੂ ਦੀ ਬਾਣੀ ਨਾਲ ਪਿਆਰ ਜੋੜ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸਿਉ = ਨਾਲ। ਰੰਗੁ = ਪਿਆਰ। ਲਾਇ = ਜੋੜ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Así que ama y revolotea en la Palabra del Guru,"