[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਸਭ ਤੁਝ ਹੀ ਅੰਤਰਿ; ਸਗਲ ਸੰਸਾਰੈ ॥"
page = 1139
line = 15

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "Within Thee are contained all the beings and the entire world."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਤੇਰੇ ਅੰਦਰ ਹੀ ਰਮੇ ਹਨ ਸਮੂਹ ਜੀਵ ਅਤੇ ਸਾਰਾ ਸੰਸਾਰ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "All beings, and the entire universe, is within You."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਸਰਬ ਪ੍ਰਕਾਰ ਸੰਸਾਰ ਸਭ ਤੇਰੇ ਹੀ ਅੰਤਰ ਭੂਤ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਕਿਉਂਕਿ) ਸਾਰੇ ਸੰਸਾਰ ਵਿਚ ਸਾਰੀ (ਉਤਪੱਤੀ) ਤੇਰੇ ਹੀ ਅਧੀਨ ਹੈ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਸੰਸਾਰੈ = ਸੰਸਾਰ ਵਿਚ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Sí, en Ti oh Señor, está contenido el Universo entero."