[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਪੂਰਾ ਨਿਆਉ ਕਰੇ; ਕਰਤਾਰੁ ॥"
page = 199
line = 11

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "The Creator administers perfect justice."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਸਿਰਜਣਹਾਰ ਮੁਕੰਮਲ ਇਨਸਾਫ ਕਰਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "The Creator administers true justice."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਹੇ ਭਾਈ! ਕਰਤਾਰ ਪੂਰਾ ਨਿਆਇ ਕਰਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਹੇ ਭਾਈ!) ਜੀਵਾਂ ਨੂੰ ਪੈਦਾ ਕਰਨ ਵਾਲਾ ਪਰਮਾਤਮਾ (ਸਦਾ) ਨਿਆਂ ਕਰਦਾ ਹੈ (ਐਸਾ ਨਿਆਂ) ਜਿਸ ਵਿਚ ਕੋਈ ਉਕਾਈ ਨਹੀਂ ਹੁੰਦੀ।"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਪੂਰਾ = ਜਿਸ ਵਿਚ ਕੋਈ ਉਕਾਈ ਨਹੀਂ ਹੁੰਦੀ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "Perfecta es la Justicia del Señor Creador,"