[[content]]
assets = ["SSA2"]
type = "primary"
data = "ਆਪਨ ਚਲਿਤੁ; ਆਪ ਹੀ ਕਰੈ ॥"
page = 281
line = 19

[[content]]
assets = ["SBMS"]
type = "translation"
language = "en"
data = "His plays He Himself enacts."

[[content]]
assets = ["SBMS"]
type = "translation"
language = "pa"
data = "ਆਪਣੇ ਕੌਤਕ ਉਹ ਆਪੇ ਹੀ ਰਚਦਾ ਹੈ।"

[[content]]
assets = ["DSSK"]
type = "translation"
language = "en"
data = "He Himself stages His own drama."

[[content]]
assets = ["NKFT"]
type = "translation"
language = "pa"
data = "ਅਪਨੇ ਚਰਿਤ੍ਰੋਂ ਕੋ ਵਹੁ ਪ੍ਰਭੂ ਆਪ ਹੀ ਕਰਤਾ ਹੈ॥"

[[content]]
assets = ["PSST"]
type = "translation"
language = "pa"
data = "(ਇਹ ਜਨਮ ਮਰਣ ਦਾ ਤਾਂ) ਪ੍ਰਭੂ ਆਪ ਹੀ ਖੇਲ ਕਰ ਰਿਹਾ ਹੈ;"

[[content]]
assets = ["PSST"]
type = "note"
language = "pa"
data = "ਚਲਿਤੁ = ਤਮਾਸ਼ਾ, ਖੇਲ।"

[[content]]
assets = ["SNST"]
type = "translation"
language = "es"
data = "todo forma parte del Juego Perfecto de Dios."