[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਗੀਧ ਪਿਸਾਚ ਗਏ ਕਰਿ ਭਛਨ ॥੩੧੩॥"
page = 1381

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਗਿੱਧਾਂ ਅਤੇ ਪਿਸਾਚ ਖਾ ਗਏ ॥੩੧੩॥"