[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਿੜਾਲਛ ਬੀਰੰ ॥"
page = 101

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "The third was the brave biralachh,"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਅਤੇ (ਤੀਜਾ) ਬਹਾਦਰ ਬਿੜਾਲਛ ਸੀ।"