[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਜ਼ਫ਼ਰਨਾਮਹ ॥"
page = 1389

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "ZAFARNAMAH (The Epistle of Victory)"

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਜ਼ਫ਼ਰਨਾਮਹ"