[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਸੂਰਾ ਦੁਰੰਤ ॥੭੬॥"
page = 620

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "That most powerful Lord is extremely Glorious and the warriors of all the four directions fear Him.76."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "ਬੇਅੰਤ ਸੂਰਮਿਆਂ ਨੂੰ ॥੭੬॥"