[[content]]
assets = ["DGDG"]
type = "primary"
data = "ਬਡ ਮਹੀਪ ਦਸ ਚਾਰ ਨਿਧਾਨਾ ॥"
page = 148

[[content]]
assets = ["DSKO"]
type = "translation"
language = "en"
data = "Who was a great monarch and adept in fourteen learnings."

[[content]]
assets = ["RSJD"]
type = "translation"
language = "pa"
data = "(ਉਹ) ਵੱਡਾ ਮਹੀਪ ਅਤੇ ਚੌਦਾਂ ਵਿਦਿਆਵਾਂ ਦਾ ਖ਼ਜ਼ਾਨਾ ਸੀ।"